const fs = require('fs');
const path = require('path');

const outDir = path.join(__dirname, '../src/lib/translations');
const existing = require('../existing_translations.json');

// --- ARABIC (ar) ---
const ar = {
  ...existing.ar,
  nav_select_lang: "اختر اللغة (Select Language)",
  nav_current_lang: "اللغة الحالية",
  badge_client_engine: "محرك محلي بالكامل في المتصفح",
  badge_security: "أمان فائق",
  home_why_sec1_title: "أمان محلي 100% على جهازك",
  home_why_sec1_desc: "يقوم mypickpdf بمعالجة الملفات مباشرة داخل ذاكرة المتصفح باستخدام WebAssembly. لا يتم نقل أي ملفات سرية إلى أي خادم خارجي.",
  home_why_sec2_title: "معالجة فورية دون أي انتظار",
  home_why_sec2_desc: "لا حاجة لانتظار رفع الملفات عبر الشبكة. يستفيد من قوة معالجة جهازك لمعالجة عشرات الصفحات في ثانية أو ثانيتين.",
  home_faq_title: "الأسئلة الشائعة (FAQ)",
  home_faq_subtitle: "إرشادات الاستخدام وسياسة الأمان الخاصة بـ mypickpdf",
  home_faq_q1: "هل mypickpdf مجاني حقًا بنسبة 100% وبدون تسجيل؟",
  home_faq_a1: "نعم! mypickpdf مجاني تمامًا إلى الأبد بدون أي تسجيل أو تسجيل دخول أو رسوم خفية.",
  home_faq_q2: "هل يتم تخزين المستندات المحولة على أي خادم؟",
  home_faq_a2: "مستحيل تمامًا. تتم معالجة جميع الملفات حصرًا داخل ذاكرة جهازك ويتم نقل 0 بايت إلى الخارج.",
  home_faq_q3: "هل يمكن تعديل ملفات Office المحولة (Word, Excel, PPT)؟",
  home_faq_a3: "بالتأكيد! ملفات Word و Excel و PowerPoint المستخرجة متوافقة تمامًا ويمكن تحريرها بحرية في Microsoft Office.",
  home_to_pdf_sub: "(Word, Excel, PPT, صور ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, صور, PDF/A)",
  share_title: "هل ترغب في التوصية بنا لأصدقائك وزملائك؟ 🐾",
  share_desc: "انسخ الرابط في ثانية واحدة واحفظه في الإشارات المرجعية!",
  share_btn: "مشاركة الرابط",
  share_copied: "تم النسخ! 🐾",
  share_bookmark: "إشارة مرجعية",
  share_bookmark_tip: "اضغط على Ctrl + D (في Mac: Cmd + D) لحفظ هذه الصفحة فورًا!",
  uploaded_card_success: "تم تحميل الملفات بنجاح وبأمان تام!",
  uploaded_card_local_badge: "تحميل محلي 100%",
  uploaded_card_change_file: "تغيير الملف",
  uploaded_card_and_more: "+ {count} ملفات أخرى",
  uploaded_card_total_pages: "الإجمالي {count} صفحات",
  uploaded_card_file_size: "الحجم",
  uploaded_card_no_server: "بدون رفع على الخوادم (عزل تام في الذاكرة)",
  processing_complete: "اكتمل",
  processing_bubble: "نقوم بإعداد وتنسيق مستندك بأقصى سرعة! 🐾",
  howto_badge: "دليل سريع",
  howto_heading_suffix: " — كيفية الاستخدام",
  howto_subtitle: "أنجز مهامك في 3 خطوات بسيطة دون الحاجة لتثبيت برامج ثقيلة.",
  faq_badge: "سؤال وجواب",
  faq_title: "الأسئلة الشائعة (FAQ)",
  faq_subtitle: "تعرف على إجابات حول استخدام الأدوات وحماية خصوصيتك.",
  guides_portal_badge: "دليل mypickpdf الرسمي",
  guides_portal_title: "إتقان مهام الـ PDF والمستندات (40+ دليلاً عملياً)",
  guides_portal_subtitle: "من دمج السير الذاتية والفواتير إلى ترقيم الأطروحات والأمان المحلي: تعلم كل شيء عبر أكثر من 40 دليلاً احترافياً.",
  guides_search_placeholder: "ابحث في الأدلة أو الكلمات المفتاحية (مثال: دمج، ضغط، جوال...)",
  guides_cat_all: "الكل",
  guides_cat_edit: "تعديل PDF",
  guides_cat_convert: "تحويل Office",
  guides_cat_security: "الأمان والخصوصية",
  guides_cat_media: "الوسائط و GIF",
  guides_cat_mobile: "نصائح الجوال",
  guides_read_article: "قراءة الدليل",
  guides_direct_tool: "فتح الأداة",
  guides_back_to_list: "العودة للقائمة",
  guides_quick_cta_title: "جرب بنفسك الآن مباشرة!",
  guides_share: "مشاركة هذا الدليل",
  guides_copied: "تم نسخ الرابط بنجاح!"
};

// --- GREEK (el) ---
const el = {
  brand_name: "mypickpdf (Κόκκινο Πάντα PDF)",
  nav_brand_tag: "100% Δωρεάν & Ασφαλή Εργαλεία PDF με το Κόκκινο Πάντα",
  nav_all_tools: "Όλα τα εργαλεία PDF",
  nav_convert_pdf: "Μετατροπή PDF",
  nav_to_pdf: "Μετατροπή σε PDF",
  nav_from_pdf: "Μετατροπή από PDF",
  nav_privacy_badge: "0% Αποθήκευση σε Διακομιστή",
  nav_free_badge: "Απεριόριστα Δωρεάν, Χωρίς Σύνδεση",
  nav_guides: "Οδηγοί",
  nav_core_tools: "Εργαλεία Επεξεργασίας PDF",
  nav_media_tools: "Εργαλεία Βίντεο & Πολυμέσων",
  nav_select_lang: "Επιλογή γλώσσας (Select Language)",
  nav_current_lang: "Τρέχουσα γλώσσα",
  badge_free_utility: "100% Δωρεάν Εφαρμογή",
  badge_no_server: "Χωρίς αποστολή σε διακομιστή (Τοπική επεξεργασία)",
  badge_no_login: "Χωρίς εγγραφή ή σύνδεση",
  badge_unlimited_free: "Ταχύτατο & Απεριόριστα Δωρεάν",
  badge_client_engine: "100% Μηχανή Πελάτη στο Πρόγραμμα Περιήγησης",
  badge_security: "Ασφάλεια",
  tool_merge: "Συγχώνευση PDF",
  tool_merge_desc: "Συνδυάστε πολλαπλά αρχεία PDF σε ένα ενιαίο έγγραφο",
  tool_split: "Διαχωρισμός PDF",
  tool_split_desc: "Εξαγάγετε συγκεκριμένες σελίδες ή διαχωρίστε κάθε σελίδα",
  tool_compress: "Συμπίεση PDF",
  tool_compress_desc: "Μειώστε το μέγεθος αρχείου PDF διατηρώντας τη μέγιστη ποιότητα",
  tool_rotate: "Περιστροφή PDF",
  tool_rotate_desc: "Περιστρέψτε το έγγραφο PDF κατά 90 ή 180 μοίρες",
  tool_ocr: "OCR PDF (Αναγνώριση κειμένου)",
  tool_ocr_desc: "Εξαγάγετε επεξεργάσιμο κείμενο από σαρωμένα PDF και εικόνες",
  tool_page_numbers: "Προσθήκη αριθμών σελίδας",
  tool_page_numbers_desc: "Εισαγάγετε αρίθμηση σελίδων στις επιθυμητές θέσεις",
  tool_watermark: "Προσθήκη υδατογραφήματος",
  tool_watermark_desc: "Προσθέστε υδατογράφημα κειμένου ή εικόνας στα έγγραφά σας",
  tool_compress_video: "Συμπίεση βίντεο",
  tool_compress_video_desc: "Μειώστε το μέγεθος βίντεο MP4 και MOV έως και 80% χωρίς απώλεια ποιότητας",
  tool_video_to_gif: "Βίντεο σε GIF",
  tool_video_to_gif_desc: "Μετατρέψτε κλιπ βίντεο σε κινούμενα αρχεία GIF υψηλής ποιότητας",
  tool_img_to_pdf: "Εικόνα σε PDF",
  tool_img_to_pdf_desc: "Μετατρέψτε εικόνες JPG και PNG σε έγγραφα PDF",
  tool_word_to_pdf: "Word σε PDF",
  tool_word_to_pdf_desc: "Μετατρέψτε έγγραφα Word (.docx) σε PDF άμεσα",
  tool_ppt_to_pdf: "PowerPoint σε PDF",
  tool_ppt_to_pdf_desc: "Μετατρέψτε παρουσιάσεις PowerPoint (.pptx) σε PDF",
  tool_excel_to_pdf: "Excel σε PDF",
  tool_excel_to_pdf_desc: "Μετατρέψτε υπολογιστικά φύλλα Excel (.xlsx) σε PDF",
  tool_html_to_pdf: "HTML σε PDF",
  tool_html_to_pdf_desc: "Αποδώστε κώδικα ιστοσελίδων HTML απευθείας σε PDF",
  tool_pdf_to_img: "PDF σε εικόνα",
  tool_pdf_to_img_desc: "Αποθηκεύστε κάθε σελίδα PDF ως εικόνα JPG υψηλής ανάλυσης",
  tool_pdf_to_word: "PDF σε Word",
  tool_pdf_to_word_desc: "Μετατρέψτε PDF σε επεξεργάσιμο έγγραφο Word (.docx)",
  tool_pdf_to_ppt: "PDF σε PowerPoint",
  tool_pdf_to_ppt_desc: "Μετατρέψτε PDF σε διαφάνειες PowerPoint (.pptx)",
  tool_pdf_to_excel: "PDF σε Excel",
  tool_pdf_to_excel_desc: "Εξαγάγετε πίνακες PDF σε υπολογιστικό φύλλο Excel (.xlsx)",
  tool_pdf_to_pdfa: "PDF σε PDF/A",
  tool_pdf_to_pdfa_desc: "Μετατρέψτε στο πρότυπο ISO PDF/A για μακροχρόνια αρχειοθέτηση",
  tool_pdf_to_hwp: "PDF σε HWP/HWPX",
  tool_pdf_to_hwp_desc: "Μετατρέψτε PDF σε επίσημο κορεατικό πρότυπο εγγράφων",
  btn_select_files: "Επιλογή αρχείων",
  drop_title_default: "Σύρετε τα αρχεία εδώ",
  drop_subtitle_default: "ή κάντε κλικ στο κουμπί παρακάτω για να επιλέξετε αρχεία",
  drop_note_privacy: "🔒 100% τοπική επεξεργασία στο πρόγραμμα περιήγησης (χωρίς αποθήκευση)",
  drop_note_limit: "Υποστήριξη απεριόριστου μεγέθους αρχείων",
  drop_badge_secure: "100% Ασφαλής Τοπική Φόρτωση",
  drop_mascot_bubble: "Αφήστε τα εδώ! 🐾",
  drop_drag_title: "Αφήστε για άμεση φόρτωση!",
  drop_drag_desc: "Είτε στο κουμπί είτε στο πλαίσιο, το αρχείο φορτώνεται με ασφάλεια",
  drop_action_drop: "Αφήστε εδώ (Drop)",
  btn_download_again: "Λήψη αρχείου",
  btn_reset: "Επαναφορά όλων",
  btn_add_files: "Προσθήκη αρχείων",
  processing_title: "Το Κόκκινο Πάντα επεξεργάζεται το έγγραφό σας με ασφάλεια...",
  processing_desc: "Παρακαλώ περιμένετε. Η λήψη θα ξεκινήσει αυτόματα μόλις ολοκληρωθεί.",
  processing_badge: "100% επεξεργασία στη μνήμη του προγράμματος περιήγησης",
  processing_complete: "Ολοκληρώθηκε",
  processing_bubble: "Ετοιμάζουμε το έγγραφό σας με κορυφαία ταχύτητα! 🐾",
  uploaded_card_success: "Τα αρχεία φορτώθηκαν με ασφάλεια και επιτυχία!",
  uploaded_card_local_badge: "100% Τοπική Φόρτωση",
  uploaded_card_change_file: "Αλλαγή αρχείου",
  uploaded_card_and_more: "+ άλλα {count}",
  uploaded_card_total_pages: "Σύνολο {count} σελίδες",
  uploaded_card_file_size: "Μέγεθος",
  uploaded_card_no_server: "Μηδενική αποστολή σε διακομιστή (Απομόνωση μνήμης)",
  home_mascot_bubble: "Γεια σας! Είμαι το Κόκκινο Πάντα 🐾 Αφήστε οποιοδήποτε έγγραφο σε εμένα!",
  home_hero_tag: "100% Δωρεάν λύση PDF στο πρόγραμμα περιήγησης με το Κόκκινο Πάντα",
  home_hero_title1: "Το πιο αξιολάτρευτο, ταχύτατο και ασφαλές",
  home_hero_title2: "Online σύνολο εργαλείων mypickpdf",
  home_hero_desc: "Μετατρέψτε, συμπιέστε και επεξεργαστείτε Word, Excel, PowerPoint και εικόνες από και προς PDF με το γλυκό μας πάντα. 100% ιδιωτική επεξεργασία που αφήνει 0 byte σε διακομιστές.",
  home_tools_title: "Δημοφιλή Προτεινόμενα Εργαλεία PDF",
  home_tools_subtitle: "Επιλέξτε το εργαλείο που χρειάζεστε και ξεκινήστε αμέσως",
  home_use_now: "Χρήση τώρα",
  home_convert_btn: "Μετατροπή",
  home_extract_btn: "Εξαγωγή",
  sponsor_snack_btn: "Κέρασμα σνακ στο Κόκκινο Πάντα ☕",
  home_why_title: "Γιατί εκατομμύρια χρήστες επιλέγουν το mypickpdf;",
  home_table_title: "Σύγκριση: Πληρωμένες ιστοσελίδες vs mypickpdf",
  home_why_sec1_title: "100% Τοπική Ασφάλεια στο Επίπεδο Χρήστη",
  home_why_sec1_desc: "Το mypickpdf επεξεργάζεται τα αρχεία απευθείας στη μνήμη του προγράμματος περιήγησης μέσω WebAssembly. Τα εμπιστευτικά έγγραφα δεν φτάνουν ποτέ σε εξωτερικούς διακομιστές.",
  home_why_sec2_title: "Άμεση Επεξεργασία Χωρίς Καθυστέρηση",
  home_why_sec2_desc: "Χωρίς αναμονή μεταφόρτωσης στο διαδίκτυο. Χρησιμοποιεί την ισχύ της συσκευής σας για να επεξεργαστεί δεκάδες σελίδες σε 1-2 δευτερόλεπτα.",
  home_faq_title: "Συχνές Ερωτήσεις (FAQ)",
  home_faq_subtitle: "Οδηγίες χρήσης και πολιτική ασφαλείας του mypickpdf",
  home_faq_q1: "Είναι το mypickpdf πραγματικά 100% δωρεάν χωρίς σύνδεση;",
  home_faq_a1: "Ναι! Το mypickpdf είναι απολύτως δωρεάν για πάντα. Χωρίς εγγραφή, χωρίς σύνδεση και χωρίς κρυφές χρεώσεις.",
  home_faq_q2: "Αποθηκεύονται τα μετατρεπόμενα έγγραφα σε κάποιο διακομιστή;",
  home_faq_a2: "Σε καμία περίπτωση. Όλα τα έγγραφα υποβάλλονται σε επεξεργασία αποκλειστικά στη μνήμη της συσκευής σας και μεταφέρονται 0 byte προς τα έξω.",
  home_faq_q3: "Είναι επεξεργάσιμα τα εξαγόμενα αρχεία Office (Word, Excel, PPT);",
  home_faq_a3: "Φυσικά! Τα αρχεία Word, Excel και PowerPoint που εξάγονται μπορούν να ανοίξουν και να τροποποιηθούν ελεύθερα στο Microsoft Office.",
  home_to_pdf_sub: "(Word, Excel, PPT, Εικόνες ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, Εικόνες, PDF/A)",
  share_title: "Θέλετε να μας προτείνετε σε φίλους και συναδέλφους; 🐾",
  share_desc: "Αντιγράψτε τον σύνδεσμο σε 1 δευτερόλεπτο και αποθηκεύστε στους σελιδοδείκτες!",
  share_btn: "Κοινοποίηση συνδέσμου",
  share_copied: "Αντιγράφηκε! 🐾",
  share_bookmark: "Σελιδοδείκτης",
  share_bookmark_tip: "Πατήστε Ctrl + D (σε Mac: Cmd + D) για να προσθέσετε τη σελίδα στους σελιδοδείκτες σας!",
  video_title: "Συμπίεση βίντεο (MP4 / MOV)",
  video_header_sub: "Μείωση μεγέθους αρχείων MP4 / MOV",
  video_desc: "Μειώστε το μέγεθος βίντεο έως και 80% για αποστολή σε συνομιλίες ή email χωρίς απώλεια ποιότητας. 100% τοπικά.",
  video_tag: "Νέα Δυνατότητα",
  video_drop_title: "Επιλέξτε αρχείο βίντεο για συμπίεση",
  video_drop_subtitle: "Υποστηρίζονται μορφές MP4, MOV, WebM, MKV (χωρίς μεταφόρτωση στο διαδίκτυο)",
  video_badge_local: "100% Τοπική Επεξεργασία (Χωρίς αποθήκευση σε διακομιστή)",
  video_badge_hardware: "Κωδικοποίηση υψηλής ταχύτητας με επιτάχυνση υλικού",
  video_badge_mobile: "Πλήρης υποστήριξη για smartphone (iPhone/Android)",
  video_step_level: "Επιλέξτε επίπεδο συμπίεσης",
  video_step_level_desc: "Επιλέξτε την ιδανική ισορροπία μεταξύ ποιότητας εικόνας και μεγέθους αρχείου",
  video_opt_extreme_title: "Μέγιστη συμπίεση (για chat & email)",
  video_opt_extreme_sub: "Εξοικονόμηση μεγέθους έως 70~85%",
  video_opt_extreme_desc: "Ιδανικό για αποστολή σε εφαρμογές ανταλλαγής μηνυμάτων και συνημμένα email.",
  video_opt_extreme_badge: "Ελάχιστο μέγεθος",
  video_opt_rec_title: "Ισορροπημένη συμπίεση (Προτεινόμενο)",
  video_opt_rec_sub: "Εξοικονόμηση μεγέθους περίπου 40~60%",
  video_opt_rec_desc: "Η καλύτερη επιλογή με καθαρή εικόνα και ουσιαστική μείωση βάρους.",
  video_opt_rec_badge: "Κορυφαία επιλογή",
  video_opt_less_title: "Διατήρηση υψηλής ποιότητας (Ελαφριά συμπίεση)",
  video_opt_less_sub: "Εξοικονόμηση μεγέθους περίπου 20~30%",
  video_opt_less_desc: "Διατηρεί στο μέγιστο την αρχική ευκρίνεια και τις λεπτομέρειες.",
  video_opt_less_badge: "Προτεραιότητα ποιότητας",
  video_selected: "Επιλέχθηκε",
  video_btn_compress: "Συμπίεση βίντεο τώρα",
  video_compressing: "Γίνεται συμπίεση...",
  video_btn_reset: "Συμπίεση νέου βίντεο",
  video_result_title: "Η συμπίεση ολοκληρώθηκε!",
  video_result_desc: "Το μέγεθος του αρχείου μειώθηκε σημαντικά χάρη στην επιτάχυνση του προγράμματος περιήγησης.",
  video_original: "Αρχικό μέγεθος",
  video_compressed: "Μέγεθος μετά τη συμπίεση",
  video_saved: "Εξοικονόμηση",
  howto_badge: "Γρήγορος οδηγός",
  howto_heading_suffix: " — Πώς χρησιμοποιείται;",
  howto_subtitle: "Ολοκληρώστε την εργασία σας σε 3 απλά βήματα χωρίς εγκατάσταση βαριών προγραμμάτων.",
  faq_badge: "Ερωτήσεις & Απαντήσεις",
  faq_title: "Συχνές Ερωτήσεις (FAQ)",
  faq_subtitle: "Βρείτε απαντήσεις σχετικά με τη λειτουργία των εργαλείων και την προστασία των δεδομένων σας.",
  guides_portal_badge: "Επίσημο εγχειρίδιο mypickpdf",
  guides_portal_title: "Κατακτήστε τη διαχείριση PDF και εγγράφων (40+ Οδηγοί)",
  guides_portal_subtitle: "Από τη συνένωση βιογραφικών και τιμολογίων έως την αρίθμηση διατριβών και την ασφάλεια: μάθετε τα πάντα.",
  guides_search_placeholder: "Αναζήτηση οδηγού ή λέξης-κλειδιού (π.χ. συγχώνευση, συμπίεση...)",
  guides_cat_all: "Όλα",
  guides_cat_edit: "Επεξεργασία PDF",
  guides_cat_convert: "Μετατροπή Office",
  guides_cat_security: "Ασφάλεια & Απόρρητο",
  guides_cat_media: "Πολυμέσα & GIF",
  guides_cat_mobile: "Συμβουλές για Κινητά",
  guides_read_article: "Διαβάστε τον οδηγό",
  guides_direct_tool: "Άνοιγμα εργαλείου",
  guides_back_to_list: "Επιστροφή στη λίστα",
  guides_quick_cta_title: "Δοκιμάστε το μόνοι σας τώρα!",
  guides_share: "Κοινοποίηση οδηγού",
  guides_copied: "Ο σύνδεσμος αντιγράφηκε!",
  ad_label: "Διαφήμιση / ADVERTISEMENT",
  ad_placeholder_title: "Χώρος χορηγούμενης διαφήμισης",
  ad_placeholder_desc: "Χώρος διαφημίσεων για τη διατήρηση της υπηρεσίας δωρεάν.",
  footer_security_title: "Εγγύηση Απόλυτης Ιδιωτικότητας & Ασφάλειας Εγγράφων",
  footer_security_desc: "Το mypickpdf δεν ανεβάζει ούτε αποθηκεύει ποτέ τα αρχεία σας σε απομακρυσμένους διακομιστές. Όλες οι λειτουργίες εκτελούνται 100% στο πρόγραμμα περιήγησής σας.",
  footer_privacy_leak: "0% Διαρροή δεδομένων προς τα έξω",
  footer_about: "Μια σύγχρονη διαδικτυακή εφαρμογή με το χαριτωμένο Κόκκινο Πάντα που επιτρέπει σε όλους να επεξεργάζονται και να μετατρέπουν αρχεία PDF δωρεάν και χωρίς εγγραφή.",
  footer_col_tools: "Δημοφιλή Εργαλεία",
  footer_col_tech: "Τεχνολογία & Ασφάλεια",
  footer_col_legal: "Υποστήριξη & Όροι",
  footer_privacy_link: "Πολιτική Απορρήτου",
  footer_terms_link: "Όροι Χρήσης",
  footer_contact_link: "Επικοινωνία & Προτάσεις",
  footer_rights: "All rights reserved. Με την επιφύλαξη παντός δικαιώματος."
};

// --- BULGARIAN (bg) ---
const bg = {
  brand_name: "mypickpdf (Червена Панда PDF)",
  nav_brand_tag: "100% Безплатни & Сигурни PDF Инструменти с Червената Панда",
  nav_all_tools: "Всички PDF инструменти",
  nav_convert_pdf: "Конвертиране на PDF",
  nav_to_pdf: "Конвертиране в PDF",
  nav_from_pdf: "Конвертиране от PDF",
  nav_privacy_badge: "0% Съхранение на Сървър",
  nav_free_badge: "Неограничено Безплатно, Без Вход",
  nav_guides: "Ръководства",
  nav_core_tools: "Инструменти за Редакция на PDF",
  nav_media_tools: "Видео и Мултимедийни Инструменти",
  nav_select_lang: "Избор на език (Select Language)",
  nav_current_lang: "Текущ език",
  badge_free_utility: "100% Безплатно Приложение",
  badge_no_server: "Без качване на сървър (Локална сигурност)",
  badge_no_login: "Без регистрация и вход",
  badge_unlimited_free: "Свръхбързо и Неограничено Безплатно",
  badge_client_engine: "100% Клиентски браузърен механизъм",
  badge_security: "Сигурност",
  tool_merge: "Обединяване на PDF",
  tool_merge_desc: "Обединете няколко PDF файла в един документ",
  tool_split: "Разделяне на PDF",
  tool_split_desc: "Извлечете избрани страници или разделете всяка страница поотделно",
  tool_compress: "Компресиране на PDF",
  tool_compress_desc: "Намалете размера на PDF файла, запазвайки най-високо качество",
  tool_rotate: "Завъртане на PDF",
  tool_rotate_desc: "Завъртете вашия PDF документ на 90 или 180 градуса",
  tool_ocr: "PDF OCR (Разпознаване на текст)",
  tool_ocr_desc: "Извличайте редактируем текст от сканирани PDF файлове и изображения",
  tool_page_numbers: "Добавяне на номера на страници",
  tool_page_numbers_desc: "Поставете номерация на страниците на желани позиции",
  tool_watermark: "Добавяне на воден знак",
  tool_watermark_desc: "Добавете текстов или графичен воден знак към документите си",
  tool_compress_video: "Компресиране на видео",
  tool_compress_video_desc: "Намалете размера на MP4 и MOV видеоклипове до 80% без загуба на качество",
  tool_video_to_gif: "Видео към GIF",
  tool_video_to_gif_desc: "Превръщайте видеоклипове във висококачествени анимирани GIF файлове",
  tool_img_to_pdf: "Изображение в PDF",
  tool_img_to_pdf_desc: "Конвертирайте JPG и PNG изображения в PDF файлове",
  tool_word_to_pdf: "Word в PDF",
  tool_word_to_pdf_desc: "Конвертирайте Word (.docx) документи в PDF незабавно",
  tool_ppt_to_pdf: "PowerPoint в PDF",
  tool_ppt_to_pdf_desc: "Превръщайте PowerPoint (.pptx) презентации в PDF",
  tool_excel_to_pdf: "Excel в PDF",
  tool_excel_to_pdf_desc: "Превръщайте електронни таблици Excel (.xlsx) в чисти PDF файлове",
  tool_html_to_pdf: "HTML в PDF",
  tool_html_to_pdf_desc: "Рендирайте уеб страници HTML директно в PDF формат",
  tool_pdf_to_img: "PDF в изображение",
  tool_pdf_to_img_desc: "Запазете всяка страница от PDF като изображение с висока резолюция JPG",
  tool_pdf_to_word: "PDF в Word",
  tool_pdf_to_word_desc: "Конвертирайте PDF в редактируем документ на Word (.docx)",
  tool_pdf_to_ppt: "PDF в PowerPoint",
  tool_pdf_to_ppt_desc: "Конвертирайте PDF в презентационни слайдове на PowerPoint (.pptx)",
  tool_pdf_to_excel: "PDF в Excel",
  tool_pdf_to_excel_desc: "Извличайте таблици от PDF в работен лист на Excel (.xlsx)",
  tool_pdf_to_pdfa: "PDF в PDF/A",
  tool_pdf_to_pdfa_desc: "Конвертирайте в ISO стандарт PDF/A за дългосрочно архивиране",
  tool_pdf_to_hwp: "PDF в HWP/HWPX",
  tool_pdf_to_hwp_desc: "Конвертирайте PDF в официален корейски документен стандарт",
  btn_select_files: "Изберете файлове",
  drop_title_default: "Плъзнете и пуснете файловете тук",
  drop_subtitle_default: "или кликнете върху бутона по-долу, за да изберете файлове",
  drop_note_privacy: "🔒 100% локална обработка в браузъра (без запазване на сървър)",
  drop_note_limit: "Поддръжка на неограничен размер на файловете",
  drop_badge_secure: "100% Сигурно Локално Зареждане",
  drop_mascot_bubble: "Пуснете ги точно тук! 🐾",
  drop_drag_title: "Пуснете мишката за незабавно зареждане!",
  drop_drag_desc: "В полето или върху бутона — файлът ще се зареди сигурно и бързо",
  drop_action_drop: "Пуснете тук (Drop)",
  btn_download_again: "Изтегляне на файл",
  btn_reset: "Нулиране на всичко",
  btn_add_files: "Добавяне на файлове",
  processing_title: "Червената Панда обработва документа ви сигурно...",
  processing_desc: "Моля, изчакайте. Изтеглянето ще започне автоматично след приключване.",
  processing_badge: "100% локална обработка в паметта на браузъра",
  processing_complete: "Завършено",
  processing_bubble: "Подготвяме документа ви с максимална скорост! 🐾",
  uploaded_card_success: "Файловете са заредени успешно и безопасно!",
  uploaded_card_local_badge: "100% Локално Заредено",
  uploaded_card_change_file: "Смяна на файл",
  uploaded_card_and_more: "+ още {count}",
  uploaded_card_total_pages: "Общо {count} страници",
  uploaded_card_file_size: "Размер",
  uploaded_card_no_server: "Без качване на сървър (Изолирана памет)",
  home_mascot_bubble: "Здравейте! Аз съм Червената Панда 🐾 Поверете ми всеки документ!",
  home_hero_tag: "100% Безплатно PDF решение в браузъра заедно с Червената Панда",
  home_hero_title1: "Най-сладкият, бърз и надежден",
  home_hero_title2: "Онлайн пакет mypickpdf",
  home_hero_desc: "Конвертирайте, компресирайте и редактирайте Word, Excel, PowerPoint и изображения от и към PDF с нашата мила панда. 100% защитена обработка в браузъра, която оставя 0 байта на сървърите.",
  home_tools_title: "Популярни Препоръчани Инструменти",
  home_tools_subtitle: "Изберете инструмента, от който се нуждаете, и започнете веднага",
  home_use_now: "Използвайте сега",
  home_convert_btn: "Конвертирай",
  home_extract_btn: "Извлечи",
  sponsor_snack_btn: "Почерпете Червената Панда с лакомство ☕",
  home_why_title: "Защо милиони потребители избират mypickpdf?",
  home_table_title: "Сравнение: Платени сайтове срещу mypickpdf",
  home_why_sec1_title: "100% Локална Сигурност от Страна на Клиента",
  home_why_sec1_desc: "mypickpdf обработва файловете директно в оперативната памет на браузъра чрез WebAssembly. Вашите поверителни документи никога не достигат външни сървъри.",
  home_why_sec2_title: "Мигновена Обработка Без Чакане",
  home_why_sec2_desc: "Без чакане на мрежово качване. Използва мощността на вашето собствено устройство за обработка на десетки страници за 1-2 секунди.",
  home_faq_title: "Често Задавани Въпроси (FAQ)",
  home_faq_subtitle: "Ръководство за употреба и правила за сигурност на mypickpdf",
  home_faq_q1: "mypickpdf наистина ли е 100% безплатен и без нужда от вход?",
  home_faq_a1: "Да! mypickpdf е напълно безплатен завинаги. Без регистрация, без вход и без скрити такси.",
  home_faq_q2: "Запазват ли се конвертираните документи на сървър?",
  home_faq_a2: "Никога. Всички документи се обработват единствено в паметта на вашето устройство и 0 байта се прехвърлят навън.",
  home_faq_q3: "Могат ли да се редактират конвертираните Office файлове (Word, Excel, PPT)?",
  home_faq_a3: "Разбира се! Извлечените Word, Excel и PowerPoint файлове са напълно съвместими и могат свободно да се редактират в Microsoft Office.",
  home_to_pdf_sub: "(Word, Excel, PPT, Изображения ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, Изображения, PDF/A)",
  share_title: "Искате ли да препоръчате сайта на приятели и колеги? 🐾",
  share_desc: "Копирайте линка за 1 секунда и го добавете в отметките за бърз достъп!",
  share_btn: "Споделяне на връзка",
  share_copied: "Копирано! 🐾",
  share_bookmark: "Отметка",
  share_bookmark_tip: "Натиснете Ctrl + D (Mac: Cmd + D), за да запазите страницата в отметките си веднага!",
  video_title: "Компресиране на видео (MP4 / MOV)",
  video_header_sub: "Намаляване на размера на MP4 / MOV",
  video_desc: "Намалете размера на видеоклиповете с до 80% за чат или имейл без загуба на качество. 100% локално в браузъра.",
  video_tag: "Нова Функция",
  video_drop_title: "Изберете видеофайл за компресиране",
  video_drop_subtitle: "Поддържат се всички формати MP4, MOV, WebM, MKV (без качване на сървър)",
  video_badge_local: "100% Локална Обработка (Без съхранение на сървър)",
  video_badge_hardware: "Хардуерно ускорено високоскоростно кодиране",
  video_badge_mobile: "Пълна поддръжка за смартфони (iPhone/Android)",
  video_step_level: "Изберете ниво на компресиране",
  video_step_level_desc: "Изберете перфектния баланс между качество на картината и размер на файла",
  video_opt_extreme_title: "Максимално компресиране (за чат и имейл)",
  video_opt_extreme_sub: "Спестяване на размер до 70~85%",
  video_opt_extreme_desc: "Идеално за споделяне в приложения за съобщения и прикачени файлове към имейли.",
  video_opt_extreme_badge: "Най-малък размер",
  video_opt_rec_title: "Балансирано компресиране (Препоръчително)",
  video_opt_rec_sub: "Спестяване на размер около 40~60%",
  video_opt_rec_desc: "Най-препоръчваният избор с кристално качество и забележимо намаляване на теглото.",
  video_opt_rec_badge: "Най-препоръчвано",
  video_opt_less_title: "Запазване на високо качество (Леко компресиране)",
  video_opt_less_sub: "Спестяване на размер около 20~30%",
  video_opt_less_desc: "Запазва максимално оригиналната резолюция и детайли.",
  video_opt_less_badge: "Приоритет качество",
  video_selected: "Избрано",
  video_btn_compress: "Компресирай видеото сега",
  video_compressing: "Компресиране на видео...",
  video_btn_reset: "Компресиране на ново видео",
  video_result_title: "Компресирането приключи успешно!",
  video_result_desc: "Размерът на файла беше значително намален благодарение на браузърното ускорение.",
  video_original: "Първоначален размер",
  video_compressed: "Размер след компресиране",
  video_saved: "Спестено място",
  howto_badge: "Бързо ръководство",
  howto_heading_suffix: " — Как се използва?",
  howto_subtitle: "Завършете задачата си в 3 прости стъпки, без да инсталирате тежък софтуер.",
  faq_badge: "Въпроси и Отговори",
  faq_title: "Често Задавани Въпроси (FAQ)",
  faq_subtitle: "Намерете отговори за работата с нашите инструменти и защитата на вашите данни.",
  guides_portal_badge: "Официален наръчник на mypickpdf",
  guides_portal_title: "Овладейте работата с PDF и документи (40+ Ръководства)",
  guides_portal_subtitle: "От обединяване на автобиографии и фактури до номерация на дисертации и локална сигурност: научете всичко.",
  guides_search_placeholder: "Търсене на статия или ключова дума (напр. обединяване, компресиране...)",
  guides_cat_all: "Всички",
  guides_cat_edit: "Редактиране на PDF",
  guides_cat_convert: "Конвертиране на Office",
  guides_cat_security: "Сигурност и Поверителност",
  guides_cat_media: "Медия и GIF",
  guides_cat_mobile: "Съвети за мобилни устройства",
  guides_read_article: "Прочети статията",
  guides_direct_tool: "Отвори инструмента",
  guides_back_to_list: "Назад към списъка",
  guides_quick_cta_title: "Опитайте сами още сега!",
  guides_share: "Споделете това ръководство",
  guides_copied: "Връзката е копирана успешно!",
  ad_label: "Реклама / ADVERTISEMENT",
  ad_placeholder_title: "Спонсорирано рекламно каре",
  ad_placeholder_desc: "Рекламно пространство за поддържане на услугата напълно безплатна.",
  footer_security_title: "Гаранция за Пълна Поверителност и Сигурност на Документите",
  footer_security_desc: "mypickpdf никога не качва и не съхранява вашите файлове на отдалечени сървъри. Всички действия се извършват 100% във вашия собствен браузър.",
  footer_privacy_leak: "0% Изтичане на данни навън",
  footer_about: "Модерна уеб услуга с очарователната Червена Панда, която позволява на всеки без вход и безплатно да редактира и конвертира PDF документи.",
  footer_col_tools: "Популярни Инструменти",
  footer_col_tech: "Технологии и Сигурност",
  footer_col_legal: "Поддръжка и Условия",
  footer_privacy_link: "Политика за Поверителност",
  footer_terms_link: "Условия за Ползване",
  footer_contact_link: "Контакт и Предложения",
  footer_rights: "All rights reserved. Всички права запазени."
};

// --- SWAHILI (sw) ---
const sw = {
  brand_name: "mypickpdf (Panda Mwekundu PDF)",
  nav_brand_tag: "Zana za PDF 100% za Bure na Salama na Panda Mwekundu",
  nav_all_tools: "Zana Zote za PDF",
  nav_convert_pdf: "Geuza PDF",
  nav_to_pdf: "Geuza kuwa PDF",
  nav_from_pdf: "Geuza kutoka PDF",
  nav_privacy_badge: "0% Hifadhi ya Seva",
  nav_free_badge: "Bure Bila Kikomo, Hakuna Kuingia",
  nav_guides: "Miongozo",
  nav_core_tools: "Zana za Kuhariri PDF",
  nav_media_tools: "Zana za Video na Vyombo vya Habari",
  nav_select_lang: "Chagua Lugha (Select Language)",
  nav_current_lang: "Lugha ya Sasa",
  badge_free_utility: "Matumizi 100% Bure",
  badge_no_server: "Hakuna kutuma kwenye seva (Usindikaji salama wa ndani)",
  badge_no_login: "Hakuna usajili wala kuingia",
  badge_unlimited_free: "Haraka Sana na Bure Bila Kikomo",
  badge_client_engine: "Injini 100% ya Kivinjari cha Mtumiaji",
  badge_security: "Usalama",
  tool_merge: "Unganisha PDF",
  tool_merge_desc: "Unganisha faili nyingi za PDF kuwa hati moja kamili",
  tool_split: "Gawanya PDF",
  tool_split_desc: "Toa kurasa maalum au gawanya kila ukurasa peke yake",
  tool_compress: "Finyaza PDF",
  tool_compress_desc: "Punguza ukubwa wa faili ya PDF huku ukidumisha ubora wa juu",
  tool_rotate: "Zungusha PDF",
  tool_rotate_desc: "Zungusha hati yako ya PDF kwa nyuzi 90 au 180",
  tool_ocr: "PDF OCR (Utambuzi wa Maandishi)",
  tool_ocr_desc: "Toa maandishi yanayoweza kuhaririwa kutoka kwa PDF na picha zilizochanganuliwa",
  tool_page_numbers: "Ongeza nambari za kurasa",
  tool_page_numbers_desc: "Weka nambari za kurasa katika nafasi unazotaka kwa urahisi",
  tool_watermark: "Ongeza alama ya siri",
  tool_watermark_desc: "Ongeza alama ya siri ya maandishi au picha kwenye hati zako",
  tool_compress_video: "Finyaza Video",
  tool_compress_video_desc: "Punguza ukubwa wa video za MP4 na MOV hadi 80% bila kupoteza ubora",
  tool_video_to_gif: "Video hadi GIF",
  tool_video_to_gif_desc: "Geuza vipande vya video kuwa faili za picha za GIF za ubora wa juu",
  tool_img_to_pdf: "Picha hadi PDF",
  tool_img_to_pdf_desc: "Geuza picha za JPG na PNG kuwa hati za PDF zenye ubora",
  tool_word_to_pdf: "Word hadi PDF",
  tool_word_to_pdf_desc: "Geuza hati za Word (.docx) kuwa PDF papo hapo",
  tool_ppt_to_pdf: "PowerPoint hadi PDF",
  tool_ppt_to_pdf_desc: "Geuza maonyesho ya PowerPoint (.pptx) kuwa hati za PDF",
  tool_excel_to_pdf: "Excel hadi PDF",
  tool_excel_to_pdf_desc: "Geuza lahajedwali za Excel (.xlsx) kuwa faili nadhifu za PDF",
  tool_html_to_pdf: "HTML hadi PDF",
  tool_html_to_pdf_desc: "Tengeneza msimbo wa kurasa za wavuti za HTML kuwa PDF moja kwa moja",
  tool_pdf_to_img: "PDF hadi Picha",
  tool_pdf_to_img_desc: "Hifadhi kila ukurasa wa PDF kama picha safi ya JPG",
  tool_pdf_to_word: "PDF hadi Word",
  tool_pdf_to_word_desc: "Geuza PDF kuwa hati inayoweza kuhaririwa ya Word (.docx)",
  tool_pdf_to_ppt: "PDF hadi PowerPoint",
  tool_pdf_to_ppt_desc: "Geuza PDF kuwa slaidi za uwasilishaji za PowerPoint (.pptx)",
  tool_pdf_to_excel: "PDF hadi Excel",
  tool_pdf_to_excel_desc: "Toa majedwali ya PDF kuwa lahajedwali ya Excel (.xlsx)",
  tool_pdf_to_pdfa: "PDF hadi PDF/A",
  tool_pdf_to_pdfa_desc: "Geuza kuwa muundo wa kiwango cha ISO PDF/A kwa uhifadhi wa muda mrefu",
  tool_pdf_to_hwp: "PDF hadi HWP/HWPX",
  tool_pdf_to_hwp_desc: "Geuza PDF kuwa muundo rasmi wa hati za Kikorea",
  btn_select_files: "Chagua Faili",
  drop_title_default: "Vuta na udondoshe faili hapa",
  drop_subtitle_default: "au bofya kitufe cha chini kuchagua faili kutoka kifaa chako",
  drop_note_privacy: "🔒 Usindikaji 100% ndani ya kivinjari (hakuna kuhifadhiwa kwenye seva)",
  drop_note_limit: "Inasaidia ukubwa wa faili bila kikomo",
  drop_badge_secure: "100% Upakiaji Salama wa Ndani",
  drop_mascot_bubble: "Dondosha hapa moja kwa moja! 🐾",
  drop_drag_title: "Achia panya ili kupakia mara moja!",
  drop_drag_desc: "Kwenye kitufe au kwenye kisanduku, faili itapakiwa kwa usalama na haraka",
  drop_action_drop: "Dondosha Hapa (Drop)",
  btn_download_again: "Pakua Faili",
  btn_reset: "Weka Upya Yote",
  btn_add_files: "Ongeza Faili",
  processing_title: "Panda Mwekundu anashughulikia hati yako kwa usalama...",
  processing_desc: "Tafadhali subiri kidogo. Upakuaji utaanza kiotomatiki ukikamilika.",
  processing_badge: "Usindikaji 100% ndani ya kumbukumbu ya kivinjari",
  processing_complete: "Imekamilika",
  processing_bubble: "Tunatayarisha hati yako kwa kasi ya ajabu! 🐾",
  uploaded_card_success: "Faili zimepakiwa kwa mafanikio na usalama kamili!",
  uploaded_card_local_badge: "100% Imepakiwa Ndani",
  uploaded_card_change_file: "Badilisha Faili",
  uploaded_card_and_more: "+ zingine {count}",
  uploaded_card_total_pages: "Jumla ya kurasa {count}",
  uploaded_card_file_size: "Ukubwa",
  uploaded_card_no_server: "Hakuna kutumwa kwa seva (Kumbukumbu imetengwa)",
  home_mascot_bubble: "Hujambo! Mimi ni Panda Mwekundu 🐾 Nipe hati yoyote nishughulikie!",
  home_hero_tag: "Suluhisho la PDF 100% Bure Ndani ya Kivinjari na Panda Mwekundu",
  home_hero_title1: "Mrembo Zaidi, Mwepesi na Salama Zaidi",
  home_hero_title2: "Kifurushi cha Mtandaoni cha mypickpdf",
  home_hero_desc: "Geuza, finyaza na hariri Word, Excel, PowerPoint na picha kwenda na kutoka PDF na panda wetu mzuri. Usindikaji 100% wa faragha ndani ya kivinjari ambao hauachi baiti 0 kwenye seva.",
  home_tools_title: "Zana Maarufu Zinazopendekezwa",
  home_tools_subtitle: "Chagua zana unayohitaji na uanze mara moja",
  home_use_now: "Tumia Sasa",
  home_convert_btn: "Geuza",
  home_extract_btn: "Toa",
  sponsor_snack_btn: "Mnunulie Panda Mwekundu vitafunwa ☕",
  home_why_title: "Kwa nini mamilioni ya watumiaji wanachagua mypickpdf?",
  home_table_title: "Ulinganisho: Tovuti Zinazolipwa dhidi ya mypickpdf",
  home_why_sec1_title: "Usalama 100% Ndani ya Kifaa cha Mtumiaji",
  home_why_sec1_desc: "mypickpdf inachakata faili moja kwa moja kwenye kumbukumbu ya kivinjari chako kupitia WebAssembly. Hati zako za siri hazifikii seva za nje kamwe.",
  home_why_sec2_title: "Usindikaji wa Papo Hapo Bila Kuchelewa",
  home_why_sec2_desc: "Hakuna kusubiri kupakia kwenye mtandao. Inatumia nguvu ya kifaa chako kuchakata makumi ya kurasa kwa sekunde 1-2.",
  home_faq_title: "Maswali Yanayoulizwa Mara kwa Mara (FAQ)",
  home_faq_subtitle: "Mwongozo wa matumizi na sera ya usalama ya mypickpdf",
  home_faq_q1: "Je, mypickpdf ni bure 100% bila kuhitaji kujiandikisha?",
  home_faq_a1: "Ndiyo! mypickpdf ni bure kabisa daima. Hakuna usajili, hakuna kuingia na hakuna ada zilizofichwa.",
  home_faq_q2: "Je, hati zilizogeuzwa zinahifadhiwa kwenye seva yoyote?",
  home_faq_a2: "Hapana kabisa. Hati zote zinachakatwa ndani ya kumbukumbu ya kifaa chako pekee na baiti 0 zinahamishiwa nje.",
  home_faq_q3: "Je, faili za Office (Word, Excel, PPT) zilizogeuzwa zinaweza kuhaririwa?",
  home_faq_a3: "Bila shaka! Faili za Word, Excel na PowerPoint zilizotolewa zinaoana kikamilifu na zinaweza kuhaririwa kwa uhuru kwenye Microsoft Office.",
  home_to_pdf_sub: "(Word, Excel, PPT, Picha ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, Picha, PDF/A)",
  share_title: "Je, ungependa kupendekeza kwa marafiki na wafanyakazi wenzako? 🐾",
  share_desc: "Nakili kiungo kwa sekunde 1 na uweke alama kwenye kivinjari kwa ufikiaji wa haraka!",
  share_btn: "Shiriki Kiungo",
  share_copied: "Imenakiliwa! 🐾",
  share_bookmark: "Weka Alama",
  share_bookmark_tip: "Bonyeza Ctrl + D (Kwenye Mac: Cmd + D) ili kuhifadhi ukurasa huu mara moja!",
  video_title: "Finyaza video (MP4 / MOV)",
  video_header_sub: "Punguza ukubwa wa faili za MP4 / MOV",
  video_desc: "Punguza ukubwa wa video hadi 80% kwa ajili ya gumzo au barua pepe bila kupoteza ubora. 100% ndani ya kivinjari.",
  video_tag: "Kipengele Kipya",
  video_drop_title: "Chagua faili ya video ya kufinyaza",
  video_drop_subtitle: "Inasaidia video zote za MP4, MOV, WebM, MKV (hakuna kupakia kwenye seva)",
  video_badge_local: "Usindikaji 100% Ndani ya Kifaa (Hakuna hifadhi ya seva)",
  video_badge_hardware: "Usimbaji wa Kasi ya Juu Ulioharakishwa na Kifaa",
  video_badge_mobile: "Msaada Kamili kwa Simu za Mkononi (iPhone/Android)",
  video_step_level: "Chagua Kiwango cha Mfinyazo",
  video_step_level_desc: "Chagua uwiano unaofaa kati ya ubora wa picha na ukubwa wa faili",
  video_opt_extreme_title: "Mfinyazo wa Juu (kwa gumzo na barua pepe)",
  video_opt_extreme_sub: "Uokoaji wa ukubwa hadi 70~85%",
  video_opt_extreme_desc: "Inafaa kabisa kwa kushiriki kupitia programu za ujumbe na viambatisho vya barua pepe.",
  video_opt_extreme_badge: "Ukubwa Mdogo Zaidi",
  video_opt_rec_title: "Mfinyazo Uliosawazishwa (Inapendekezwa)",
  video_opt_rec_sub: "Uokoaji wa ukubwa wa takriban 40~60%",
  video_opt_rec_desc: "Chaguo bora zaidi lenye picha angavu na upunguzaji mkubwa wa uzito wa faili.",
  video_opt_rec_badge: "Inayopendekezwa Zaidi",
  video_opt_less_title: "Dumisha Ubora wa Juu (Mfinyazo Mwepesi)",
  video_opt_less_sub: "Uokoaji wa ukubwa wa takriban 20~30%",
  video_opt_less_desc: "Inadumisha azimio asili na maelezo ya kina kwa upeo wa juu.",
  video_opt_less_badge: "Kipaumbele cha Ubora",
  video_selected: "Imechaguliwa",
  video_btn_compress: "Finyaza Video Sasa",
  video_compressing: "Video inafinyazwa...",
  video_btn_reset: "Finyaza Video Mpya",
  video_result_title: "Mfinyazo wa Video Umekamilika!",
  video_result_desc: "Ukubwa wa faili umepunguzwa kwa kiasi kikubwa shukrani kwa kuongeza kasi ya kivinjari.",
  video_original: "Ukubwa wa Asili",
  video_compressed: "Ukubwa Baada ya Mfinyazo",
  video_saved: "Nafasi Iliyookolewa",
  howto_badge: "Mwongozo wa Haraka",
  howto_heading_suffix: " — Jinsi ya Kutumia?",
  howto_subtitle: "Kamilisha kazi yako kwa hatua 3 rahisi bila kusakinisha programu nzito.",
  faq_badge: "Maswali na Majibu",
  faq_title: "Maswali Yanayoulizwa Mara kwa Mara (FAQ)",
  faq_subtitle: "Pata majibu kuhusu matumizi ya zana zetu na ulinzi wa faragha ya data yako.",
  guides_portal_badge: "Kitabu Rasmi cha Mwongozo cha mypickpdf",
  guides_portal_title: "Jifunze Kazi za PDF na Hati kwa Ufasaha (Miongozo 40+)",
  guides_portal_subtitle: "Kuanzia kuunganisha wasifu na ankara hadi nambari za kurasa za nadharia na faragha ya ndani.",
  guides_search_placeholder: "Tafuta mwongozo au neno kuu (mf. unganisha, finyaza, simu...)",
  guides_cat_all: "Yote",
  guides_cat_edit: "Uhariri wa PDF",
  guides_cat_convert: "Ugeuzaji wa Office",
  guides_cat_security: "Usalama na Faragha",
  guides_cat_media: "Vyombo vya Habari & GIF",
  guides_cat_mobile: "Vidokezo vya Simu",
  guides_read_article: "Soma Mwongozo",
  guides_direct_tool: "Fungua Zana",
  guides_back_to_list: "Rudi kwenye Orodha",
  guides_quick_cta_title: "Jaribu wewe mwenyewe sasa hivi!",
  guides_share: "Shiriki Mwongozo Huu",
  guides_copied: "Kiungo kimenakiliwa!",
  ad_label: "Tangazo / ADVERTISEMENT",
  ad_placeholder_title: "Nafasi ya Tangazo Lililofadhiliwa",
  ad_placeholder_desc: "Nafasi ya kuonyesha matangazo ili kuweka huduma hii bila malipo.",
  footer_security_title: "Uhakikisho wa Faragha Kamili na Usalama wa Hati",
  footer_security_desc: "mypickpdf haipakii wala kuhifadhi faili zako kwenye seva za mbali. Shughuli zote hufanyika 100% kwenye kivinjari chako mwenyewe.",
  footer_privacy_leak: "0% Uvujaji wa data kwa nje",
  footer_about: "Huduma ya kisasa ya wavuti pamoja na Panda Mwekundu mzuri inayomruhusu mtu yeyote kuhariri na kugeuza faili za PDF bila malipo na bila kuingia.",
  footer_col_tools: "Zana Maarufu",
  footer_col_tech: "Teknolojia na Usalama",
  footer_col_legal: "Msaada na Masharti",
  footer_privacy_link: "Sera ya Faragha",
  footer_terms_link: "Masharti ya Huduma",
  footer_contact_link: "Wasiliana Nasi na Maoni",
  footer_rights: "All rights reserved. Haki zote zimehifadhiwa."
};

fs.writeFileSync(path.join(outDir, 'ar.ts'), `import { TranslationDictionary } from "./types";\n\nexport const ar: TranslationDictionary = ${JSON.stringify(ar, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'el.ts'), `import { TranslationDictionary } from "./types";\n\nexport const el: TranslationDictionary = ${JSON.stringify(el, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'bg.ts'), `import { TranslationDictionary } from "./types";\n\nexport const bg: TranslationDictionary = ${JSON.stringify(bg, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'sw.ts'), `import { TranslationDictionary } from "./types";\n\nexport const sw: TranslationDictionary = ${JSON.stringify(sw, null, 2)};\n`);

console.log('Generated ar.ts, el.ts, bg.ts, sw.ts');
