const fs = require('fs');
const path = require('path');

const outDir = path.join(__dirname, '../src/lib/translations');

// We load existing translations for ja, zh, id, vi
const existing = require('../existing_translations.json');

// --- HINDI (hi) ---
const hi = {
  brand_name: "mypickpdf (मायपिक पीडीएफ)",
  nav_brand_tag: "रेड पांडा के साथ 100% मुफ़्त और सुरक्षित PDF टूल्स",
  nav_all_tools: "सभी PDF उपकरण",
  nav_convert_pdf: "PDF कनवर्ट करें",
  nav_to_pdf: "PDF में कनवर्ट करें",
  nav_from_pdf: "PDF से कनवर्ट करें",
  nav_privacy_badge: "0% सर्वर स्टोरेज",
  nav_free_badge: "असीमित मुफ़्त, कोई साइन-अप नहीं",
  nav_guides: "गाइड",
  nav_core_tools: "PDF संपादन उपकरण",
  nav_media_tools: "वीडियो और मीडिया टूल्स",
  nav_select_lang: "भाषा चुनें (Select Language)",
  nav_current_lang: "वर्तमान भाषा",
  badge_free_utility: "100% मुफ़्त यूटिलिटी",
  badge_no_server: "कोई सर्वर ट्रांसमिशन नहीं (स्थानीय सुरक्षित)",
  badge_no_login: "कोई लॉगिन या साइन-अप आवश्यक नहीं",
  badge_unlimited_free: "अति-तेज़ असीमित मुफ़्त",
  badge_client_engine: "100% क्लाइंट-साइड इंजन",
  badge_security: "सुरक्षा",
  tool_merge: "PDF मर्ज करें",
  tool_merge_desc: "कई PDF फ़ाइलों को एक दस्तावेज़ में संयोजित करें",
  tool_split: "PDF विभाजित करें",
  tool_split_desc: "विशिष्ट पृष्ठ निकालें या प्रत्येक पृष्ठ को अलग करें",
  tool_compress: "PDF कंप्रेस करें",
  tool_compress_desc: "गुणवत्ता खोए बिना फ़ाइल का आकार कम करें",
  tool_rotate: "PDF रोटेट करें",
  tool_rotate_desc: "दस्तावेज़ को 90° या 180° घुमाएँ",
  tool_ocr: "PDF OCR (टेक्स्ट पहचान)",
  tool_ocr_desc: "स्कैन किए गए दस्तावेज़ों से टेक्स्ट निकालें",
  tool_page_numbers: "पेज नंबर जोड़ें",
  tool_page_numbers_desc: "कस्टम स्थिति में पेज नंबर आसानी से डालें",
  tool_watermark: "वॉटरमार्क जोड़ें",
  tool_watermark_desc: "दस्तावेज़ों में टेक्स्ट या छवि वॉटरमार्क जोड़ें",
  tool_compress_video: "वीडियो कंप्रेस करें",
  tool_compress_video_desc: "गुणवत्ता बनाए रखते हुए MP4/MOV आकार 80% तक कम करें",
  tool_video_to_gif: "वीडियो से GIF",
  tool_video_to_gif_desc: "वीडियो को उच्च गुणवत्ता वाले एनिमेटेड GIF में बदलें",
  tool_img_to_pdf: "छवि से PDF",
  tool_img_to_pdf_desc: "JPG, PNG छवियों को PDF दस्तावेज़ में बदलें",
  tool_word_to_pdf: "Word से PDF",
  tool_word_to_pdf_desc: "DOCX दस्तावेज़ों को तुरंत PDF में कनवर्ट करें",
  tool_ppt_to_pdf: "PowerPoint से PDF",
  tool_ppt_to_pdf_desc: "PPTX प्रस्तुतियों को PDF में बदलें",
  tool_excel_to_pdf: "Excel से PDF",
  tool_excel_to_pdf_desc: "XLSX स्प्रेडशीट को PDF तालिका में बदलें",
  tool_html_to_pdf: "HTML से PDF",
  tool_html_to_pdf_desc: "वेबपेज HTML कोड को सीधे PDF में रेंडर करें",
  tool_pdf_to_img: "PDF से छवि",
  tool_pdf_to_img_desc: "PDF पृष्ठों को उच्च गुणवत्ता वाले JPG में सहेजें",
  tool_pdf_to_word: "PDF से Word",
  tool_pdf_to_word_desc: "PDF को संपादन योग्य DOCX दस्तावेज़ में बदलें",
  tool_pdf_to_ppt: "PDF से PowerPoint",
  tool_pdf_to_ppt_desc: "PDF को संपादन योग्य PPTX स्लाइड में बदलें",
  tool_pdf_to_excel: "PDF से Excel",
  tool_pdf_to_excel_desc: "PDF तालिकाओं को XLSX स्प्रेडशीट में निकालें",
  tool_pdf_to_pdfa: "PDF से PDF/A",
  tool_pdf_to_pdfa_desc: "दीर्घकालिक संग्रहण के लिए ISO मानकीकृत PDF/A",
  tool_pdf_to_hwp: "PDF से HWP/HWPX",
  tool_pdf_to_hwp_desc: "PDF को कोरियाई मानक HWPX/HWP दस्तावेज़ में बदलें",
  btn_select_files: "फ़ाइलें चुनें",
  drop_title_default: "यहाँ फ़ाइलें खींचें और छोड़ें",
  drop_subtitle_default: "या नीचे दिए गए बटन पर क्लिक करके फ़ाइल चुनें",
  drop_note_privacy: "🔒 100% स्थानीय ब्राउज़र प्रोसेसिंग (कोई सर्वर स्टोरेज नहीं)",
  drop_note_limit: "असीमित फ़ाइल आकार समर्थित",
  drop_badge_secure: "100% स्थानीय सुरक्षित अनुलग्नक",
  drop_mascot_bubble: "यहाँ छोड़ें! 🐾",
  drop_drag_title: "छोड़ते ही तुरंत लोड हो जाएगा!",
  drop_drag_desc: "बटन या बॉक्स में कहीं भी छोड़ें, सुरक्षित रूप से लोड होगा",
  drop_action_drop: "यहाँ छोड़ें (Drop)",
  btn_download_again: "फ़ाइल डाउनलोड करें",
  btn_reset: "रीसेट करें",
  btn_add_files: "फ़ाइलें जोड़ें",
  processing_title: "रेड पांडा दस्तावेज़ को सुरक्षित रूप से प्रोसेस कर रहा है...",
  processing_desc: "कृपया प्रतीक्षा करें। पूरा होते ही स्वचालित रूप से डाउनलोड शुरू होगा।",
  processing_badge: "100% ब्राउज़र मेमोरी स्थानीय प्रोसेसिंग",
  processing_complete: "पूर्ण",
  processing_bubble: "अति-तीव्र गति से आपके दस्तावेज़ को तैयार कर रहे हैं! 🐾",
  uploaded_card_success: "फ़ाइलें सुरक्षित और सफलतापूर्वक लोड हो गईं!",
  uploaded_card_local_badge: "100% स्थानीय लोड",
  uploaded_card_change_file: "फ़ाइल बदलें",
  uploaded_card_and_more: "+ {count} और",
  uploaded_card_total_pages: "कुल {count} पृष्ठ",
  uploaded_card_file_size: "आकार",
  uploaded_card_no_server: "शून्य सर्वर अपलोड (मेमोरी आइसोलेशन)",
  home_mascot_bubble: "नमस्ते! मैं रेड पांडा हूँ 🐾 कोई भी दस्तावेज़ मुझे सौंपें!",
  home_hero_tag: "रेड पांडा के साथ 100% मुफ़्त और सुरक्षित इन-ब्राउज़र PDF समाधान",
  home_hero_title1: "सबसे प्यारा, सबसे तेज़ और सबसे सुरक्षित",
  home_hero_title2: "mypickpdf ऑनलाइन सूट",
  home_hero_desc: "हमारे प्यारे रेड पांडा के साथ Word, Excel, PowerPoint और छवियों को PDF में और PDF से कनवर्ट, कंप्रेस और संपादित करें। 100% निजी इन-ब्राउज़र प्रोसेसिंग जो सर्वर पर 0 बाइट छोड़ती है।",
  home_tools_title: "mypickpdf अनुशंसित लोकप्रिय उपकरण",
  home_tools_subtitle: "आवश्यक टूल चुनें और तुरंत शुरू करें",
  home_use_now: "अभी उपयोग करें",
  home_convert_btn: "कनवर्ट करें",
  home_extract_btn: "निकालें",
  sponsor_snack_btn: "रेड पांडा स्नैक प्रायोजन ☕",
  home_why_title: "लाखों उपयोगकर्ता mypickpdf क्यों चुनते हैं?",
  home_table_title: "पारंपरिक सशुल्क साइटें बनाम mypickpdf",
  home_why_sec1_title: "100% क्लाइंट-साइड स्थानीय सुरक्षा",
  home_why_sec1_desc: "mypickpdf वेब असेंबली का उपयोग करके सीधे आपके ब्राउज़र में फ़ाइलें प्रोसेस करता है। कोई भी दस्तावेज़ बाहरी सर्वर पर नहीं भेजा जाता।",
  home_why_sec2_title: "बिना किसी देरी के त्वरित प्रोसेसिंग",
  home_why_sec2_desc: "नेटवर्क अपलोड की कोई प्रतीक्षा नहीं। डिवाइस-स्तरीय कंप्यूटिंग के साथ कुछ ही सेकंड में प्रोसेसिंग।",
  home_faq_title: "अक्सर पूछे जाने वाले प्रश्न (FAQ)",
  home_faq_subtitle: "mypickpdf सेवा उपयोग और सुरक्षा दिशानिर्देश",
  home_faq_q1: "क्या mypickpdf वास्तव में बिना साइन-अप के 100% मुफ़्त है?",
  home_faq_a1: "हाँ! mypickpdf हमेशा के लिए पूरी तरह मुफ़्त है। कोई पंजीकरण नहीं, कोई लॉगिन नहीं और कोई भुगतान नहीं।",
  home_faq_q2: "क्या कनवर्ट किए गए दस्तावेज़ सर्वर पर सहेजे जाते हैं?",
  home_faq_a2: "कभी नहीं। सभी दस्तावेज़ केवल आपके डिवाइस की मेमोरी में प्रोसेस होते हैं और बाहरी सर्वर पर 0 बाइट भेजी जाती है।",
  home_faq_q3: "क्या कनवर्ट की गई Office फ़ाइलें (Word, Excel, PPT) संपादन योग्य हैं?",
  home_faq_a3: "हाँ! निकाली गई Word, Excel और PowerPoint फ़ाइलें Microsoft Office और अन्य प्रोग्रामों में पूरी तरह संपादन योग्य हैं।",
  home_to_pdf_sub: "(Word, Excel, PPT, छवियाँ ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, छवियाँ, PDF/A)",
  share_title: "दोस्तों और सहकर्मियों को सुझाना चाहते हैं? 🐾",
  share_desc: "1 सेकंड में लिंक कॉपी करें और त्वरित पहुँच के लिए बुकमार्क करें!",
  share_btn: "लिंक साझा करें",
  share_copied: "कॉपी किया गया! 🐾",
  share_bookmark: "बुकमार्क",
  share_bookmark_tip: "इस पृष्ठ को तुरंत बुकमार्क करने के लिए Ctrl + D (Mac: Cmd + D) दबाएँ!",
  video_title: "वीडियो कंप्रेस (MP4 / MOV)",
  video_header_sub: "MP4 / MOV फ़ाइल आकार कम करें",
  video_desc: "गुणवत्ता खोए बिना वीडियो का आकार 80% तक कम करें। 100% सुरक्षित स्थानीय इन-ब्राउज़र प्रोसेसिंग।",
  video_tag: "नया फीचर",
  video_drop_title: "कंप्रेस करने के लिए वीडियो फ़ाइल चुनें",
  video_drop_subtitle: "MP4, MOV, WebM, MKV आदि सभी वीडियो समर्थित (कोई सर्वर अपलोड नहीं)",
  video_badge_local: "100% स्थानीय डिवाइस प्रोसेसिंग (कोई सर्वर स्टोरेज नहीं)",
  video_badge_hardware: "हार्डवेयर त्वरित हाई-स्पीड एन्कोडिंग",
  video_badge_mobile: "मोबाइल (iPhone/Android) पूर्ण समर्थन",
  video_step_level: "संपीड़न स्तर चुनें",
  video_step_level_desc: "अपनी आवश्यकतानुसार गुणवत्ता और फ़ाइल आकार चुनें",
  video_opt_extreme_title: "अत्यधिक संपीड़न (शेयरिंग/ईमेल के लिए)",
  video_opt_extreme_sub: "70~85% तक आकार में कमी",
  video_opt_extreme_desc: "चैट, ईमेल और वेब अपलोड के लिए सबसे उपयुक्त।",
  video_opt_extreme_badge: "न्यूनतम आकार",
  video_opt_rec_title: "अनुशंसित संपीड़न (संतुलित)",
  video_opt_rec_sub: "लगभग 40~60% आकार में कमी",
  video_opt_rec_desc: "स्पष्ट गुणवत्ता और प्रभावी आकार का सबसे अनुशंसित संतुलन।",
  video_opt_rec_badge: "सबसे अनुशंसित",
  video_opt_less_title: "उच्च गुणवत्ता बनाए रखें (हल्का संपीड़न)",
  video_opt_less_sub: "लगभग 20~30% आकार में कमी",
  video_opt_less_desc: "मूल विवरण और रिज़ॉल्यूशन को अधिकतम बनाए रखता है।",
  video_opt_less_badge: "गुणवत्ता प्राथमिकता",
  video_selected: "चयनित",
  video_btn_compress: "वीडियो कंप्रेस करें",
  video_compressing: "वीडियो कंप्रेस हो रहा है...",
  video_btn_reset: "नया वीडियो कंप्रेस करें",
  video_result_title: "वीडियो संपीड़न पूर्ण!",
  video_result_desc: "ब्राउज़र त्वरण के साथ फ़ाइल आकार काफी कम हो गया है।",
  video_original: "मूल आकार",
  video_compressed: "संपीड़न के बाद आकार",
  video_saved: "सहेजा गया आकार",
  howto_badge: "त्वरित ट्यूटोरियल",
  howto_heading_suffix: " — उपयोग कैसे करें",
  howto_subtitle: "जटिल सॉफ़्टवेयर स्थापित किए बिना 3 आसान चरणों में कार्य पूरा करें।",
  faq_badge: "प्रश्नोत्तर",
  faq_title: "अक्सर पूछे जाने वाले प्रश्न (FAQ)",
  faq_subtitle: "टूल उपयोग और गोपनीयता सुरक्षा के बारे में उत्तर प्राप्त करें।",
  guides_portal_badge: "mypickpdf आधिकारिक गाइडबुक",
  guides_portal_title: "PDF और दस्तावेज़ वर्कफ़्लो में महारत हासिल करें (40+ गाइड)",
  guides_portal_subtitle: "रिज़्यूमे, टैक्स चालान से लेकर थीसिस नंबरिंग और स्थानीय गोपनीयता तक, 40+ व्यावहारिक गाइडों के साथ सब कुछ सीखें।",
  guides_search_placeholder: "गाइड शीर्षक या कीवर्ड खोजें (उदा: मर्ज, कंप्रेस, मोबाइल...)",
  guides_cat_all: "सभी",
  guides_cat_edit: "PDF संपादन",
  guides_cat_convert: "Office कनवर्ट",
  guides_cat_security: "सुरक्षा और गोपनीयता",
  guides_cat_media: "मीडिया और GIF",
  guides_cat_mobile: "मोबाइल टिप्स",
  guides_read_article: "गाइड पढ़ें",
  guides_direct_tool: "टूल खोलें",
  guides_back_to_list: "गाइड सूची पर वापस जाएँ",
  guides_quick_cta_title: "इसे अभी स्वयं आज़माएँ!",
  guides_share: "गाइड साझा करें",
  guides_copied: "लिंक कॉपी किया गया!",
  ad_label: "विज्ञापन / ADVERTISEMENT",
  ad_placeholder_title: "प्रायोजित विज्ञापन क्षेत्र",
  ad_placeholder_desc: "उच्च मूल्य विज्ञापन प्रदर्शन क्षेत्र।",
  footer_security_title: "पूर्ण गोपनीयता और दस्तावेज़ सुरक्षा गारंटी",
  footer_security_desc: "mypickpdf आपकी फ़ाइलों को किसी भी दूरस्थ सर्वर पर कभी नहीं भेजता या संग्रहीत नहीं करता है। सभी कार्य 100% स्थानीय ब्राउज़र में निष्पादित होते हैं।",
  footer_privacy_leak: "0% डेटा रिसाव",
  footer_about: "प्यारे रेड पांडा के साथ बिना किसी लागत और लॉगिन के PDF संपादित और कनवर्ट करने की अगली पीढ़ी की वेब उपयोगिता सेवा।",
  footer_col_tools: "लोकप्रिय उपकरण",
  footer_col_tech: "प्रौद्योगिकी और सुरक्षा",
  footer_col_legal: "कानूनी और सहायता",
  footer_privacy_link: "गोपनीयता नीति",
  footer_terms_link: "सेवा की शर्तें",
  footer_contact_link: "संपर्क और सुझाव",
  footer_rights: "All rights reserved. सर्वाधिकार सुरक्षित।"
};

// --- TRADITIONAL CHINESE (zh-TW) ---
const zhTW = {
  brand_name: "mypickpdf (小熊貓PDF)",
  nav_brand_tag: "與可愛小熊貓一起享受 100% 免費安全 PDF 工具",
  nav_all_tools: "所有 PDF 工具",
  nav_convert_pdf: "轉換 PDF",
  nav_to_pdf: "轉為 PDF",
  nav_from_pdf: "從 PDF 轉換",
  nav_privacy_badge: "零伺服器儲存",
  nav_free_badge: "免登入、無限制免費",
  nav_guides: "實用指南",
  nav_core_tools: "PDF 編輯工具",
  nav_media_tools: "影片與多媒體工具",
  nav_select_lang: "選擇語言 (Select Language)",
  nav_current_lang: "當前語言",
  badge_free_utility: "100% 免費工具",
  badge_no_server: "無伺服器傳輸（本機安全處理）",
  badge_no_login: "免註冊、免登入",
  badge_unlimited_free: "極速無限免費",
  badge_client_engine: "100% 瀏覽器客戶端引擎",
  badge_security: "隱私安全",
  tool_merge: "合併 PDF",
  tool_merge_desc: "將多個 PDF 文件合併為一個檔案",
  tool_split: "分割 PDF",
  tool_split_desc: "提取特定頁面或單獨分割每一頁",
  tool_compress: "壓縮 PDF",
  tool_compress_desc: "在保持最佳品質的前提下大幅縮小檔案大小",
  tool_rotate: "旋轉 PDF",
  tool_rotate_desc: "將 PDF 文件旋轉 90度或 180度",
  tool_ocr: "PDF OCR 文字辨識",
  tool_ocr_desc: "精準提取掃描文件中的所有文字",
  tool_page_numbers: "新增頁碼",
  tool_page_numbers_desc: "在指定位置批次插入頁碼與格式",
  tool_watermark: "新增浮水印",
  tool_watermark_desc: "為文件添加自訂文字或機密浮水印",
  tool_compress_video: "影片壓縮",
  tool_compress_video_desc: "不損畫質將 MP4/MOV 影片容量最高縮小 80%",
  tool_video_to_gif: "影片轉 GIF",
  tool_video_to_gif_desc: "將短片轉為社群適用的高畫質動態圖",
  tool_img_to_pdf: "圖片轉 PDF",
  tool_img_to_pdf_desc: "將 JPG、PNG 圖片轉為高解析度 PDF",
  tool_word_to_pdf: "Word 轉 PDF",
  tool_word_to_pdf_desc: "將 Word (.docx) 文件秒轉為 PDF",
  tool_ppt_to_pdf: "PPT 轉 PDF",
  tool_ppt_to_pdf_desc: "將 PowerPoint 簡報轉為 PDF 文件",
  tool_excel_to_pdf: "Excel 轉 PDF",
  tool_excel_to_pdf_desc: "將 Excel 試算表轉換為精美 PDF",
  tool_html_to_pdf: "HTML 轉 PDF",
  tool_html_to_pdf_desc: "將網頁 HTML 程式碼直接算繪為 PDF",
  tool_pdf_to_img: "PDF 轉圖片",
  tool_pdf_to_img_desc: "將 PDF 每一頁儲存為高畫質 JPG 圖片",
  tool_pdf_to_word: "PDF 轉 Word",
  tool_pdf_to_word_desc: "將 PDF 轉為可自由編輯的 Word (.docx)",
  tool_pdf_to_ppt: "PDF 轉 PPT",
  tool_pdf_to_ppt_desc: "將 PDF 轉為可編輯的 PowerPoint 簡報",
  tool_pdf_to_excel: "PDF 轉 Excel",
  tool_pdf_to_excel_desc: "將 PDF 表格資料擷取至 Excel 試算表",
  tool_pdf_to_pdfa: "PDF 轉 PDF/A",
  tool_pdf_to_pdfa_desc: "轉換為適合長期歸檔的 ISO 標準 PDF/A",
  tool_pdf_to_hwp: "PDF 轉 HWP/HWPX",
  tool_pdf_to_hwp_desc: "將 PDF 轉換為公文標準韓語文件",
  btn_select_files: "選擇檔案",
  drop_title_default: "將檔案拖放到此處",
  drop_subtitle_default: "或點擊下方按鈕選擇檔案",
  drop_note_privacy: "🔒 100% 瀏覽器本機處理（絕不儲存於伺服器）",
  drop_note_limit: "支援無限檔案大小",
  drop_badge_secure: "100% 本機安心上傳",
  drop_mascot_bubble: "請放這裡吧！🐾",
  drop_drag_title: "放開滑鼠即可立即載入！",
  drop_drag_desc: "無論放在按鈕或框框內，皆能安全快速解析",
  drop_action_drop: "直接拖放到此處",
  btn_download_again: "下載檔案",
  btn_reset: "全部重設",
  btn_add_files: "新增檔案",
  processing_title: "小熊貓正在安全轉換您的文件...",
  processing_desc: "請稍候，轉換完成後將自動開始下載。",
  processing_badge: "100% 瀏覽器記憶體本機運算",
  processing_complete: "完成",
  processing_bubble: "正在以極速為您精心處理！🐾",
  uploaded_card_success: "檔案已安全成功載入！",
  uploaded_card_local_badge: "100% 本機載入完畢",
  uploaded_card_change_file: "更換檔案",
  uploaded_card_and_more: "等 {count} 個檔案",
  uploaded_card_total_pages: "共 {count} 頁",
  uploaded_card_file_size: "大小",
  uploaded_card_no_server: "零伺服器傳輸（記憶體安全隔離）",
  home_mascot_bubble: "你好！我是小熊貓 🐾 有任何文件請儘管交給我！",
  home_hero_tag: "與可愛小熊貓相伴的 100% 免費瀏覽器 PDF 工具箱",
  home_hero_title1: "最可愛、最極速且最安全的",
  home_hero_title2: "mypickpdf 線上套裝工具",
  home_hero_desc: "與可愛的小熊貓吉祥物一起輕鬆轉換 Word、Excel、PPT、圖片與 PDF。完全於瀏覽器內部處理，伺服器不留存任何位元組。",
  home_tools_title: "mypickpdf 熱門推薦工具",
  home_tools_subtitle: "點選您需要的工具，即可立即開始處理",
  home_use_now: "立即使用",
  home_convert_btn: "立即轉換",
  home_extract_btn: "立即擷取",
  sponsor_snack_btn: "贊助小熊貓點心 ☕",
  home_why_title: "為什麼全球用戶都選擇 mypickpdf？",
  home_table_title: "傳統付費網站 vs mypickpdf 深度對比",
  home_why_sec1_title: "100% 客戶端本機隱私保護",
  home_why_sec1_desc: "mypickpdf 採用 WebAssembly 直接在瀏覽器記憶體中運算，任何機密文件絕不離開您的裝置。",
  home_why_sec2_title: "即時處理，零上傳等待",
  home_why_sec2_desc: "省去漫長的網路傳輸等待，運用裝置原生算力數秒內處理數十頁文件。",
  home_faq_title: "常見問題 (FAQ)",
  home_faq_subtitle: "mypickpdf 服務使用指南與安全性說明",
  home_faq_q1: "mypickpdf 真的完全免費且無需登入嗎？",
  home_faq_a1: "是的！mypickpdf 承諾永久 100% 免費，絕無註冊、登入限制或隱藏扣款。",
  home_faq_q2: "轉換文件時檔案會被上傳到伺服器嗎？",
  home_faq_a2: "絕不。所有轉檔與編輯皆在瀏覽器記憶體本機完成，外部伺服器儲存量為 0 Byte。",
  home_faq_q3: "轉換後的 Office 檔案（Word/Excel/PPT）可以編輯嗎？",
  home_faq_a3: "當然可以！提取出的 .docx, .xlsx, .pptx 檔案皆相容於 Microsoft Office 與各大辦公軟體，可自由編輯。",
  home_to_pdf_sub: "(Word, Excel, PPT, 圖片 ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, 圖片, PDF/A)",
  share_title: "想推薦給身邊的好友與同事嗎？🐾",
  share_desc: "1 秒複製連結並加入書籤，隨時快速開啟！",
  share_btn: "分享連結",
  share_copied: "複製成功！🐾",
  share_bookmark: "加入書籤",
  share_bookmark_tip: "按下 Ctrl + D（Mac: Cmd + D）即可立即收藏本站！",
  video_title: "影片壓縮 (MP4 / MOV)",
  video_header_sub: "輕鬆縮小 MP4 / MOV 檔案大小",
  video_desc: "不傷畫質最高縮小 80% 影片容量，方便社群傳送與信件夾帶。100% 本機瀏覽器處理。",
  video_tag: "全新功能",
  video_drop_title: "選擇要壓縮的影片檔案",
  video_drop_subtitle: "支援 MP4、MOV、WebM、MKV 等常見格式（無伺服器上傳）",
  video_badge_local: "100% 本機裝置處理（不佔雲端空間）",
  video_badge_hardware: "硬體加速高速編碼",
  video_badge_mobile: "手機平板（iPhone / Android）完美支援",
  video_step_level: "選擇壓縮等級",
  video_step_level_desc: "請依據您對畫質與檔案大小的需求進行選擇",
  video_opt_extreme_title: "極限壓縮（適合社群與郵件）",
  video_opt_extreme_sub: "最高節省 70~85% 容量",
  video_opt_extreme_desc: "大幅減輕檔案體積，極致適合通訊軟體傳輸與社群上傳。",
  video_opt_extreme_badge: "體積最小",
  video_opt_rec_title: "推薦平衡（最佳標準）",
  video_opt_rec_sub: "約節省 40~60% 容量",
  video_opt_rec_desc: "在清晰高畫質與顯著容量瘦身之間取得完美黃金平衡點。",
  video_opt_rec_badge: "最強推薦",
  video_opt_less_title: "維持高畫質（輕度壓縮）",
  video_opt_less_sub: "約節省 20~30% 容量",
  video_opt_less_desc: "最大程度保留原始畫面細節與解析度，僅優化過剩碼率。",
  video_opt_less_badge: "畫質優先",
  video_selected: "已選擇",
  video_btn_compress: "開始壓縮影片",
  video_compressing: "影片壓縮中...",
  video_btn_reset: "壓縮新影片",
  video_result_title: "影片壓縮完成！",
  video_result_desc: "透過瀏覽器原生硬體加速，檔案容量已大幅縮減。",
  video_original: "原始大小",
  video_compressed: "壓縮後大小",
  video_saved: "已節省",
  howto_badge: "操作教學",
  howto_heading_suffix: " — 如何使用？",
  howto_subtitle: "無需安裝複雜軟體，僅需簡易 3 步驟即可輕鬆搞定。",
  faq_badge: "常見問答",
  faq_title: "常見問題 (FAQ)",
  faq_subtitle: "了解 mypickpdf 的工具使用訣竅與隱私安全保障。",
  guides_portal_badge: "mypickpdf 官方實戰指南",
  guides_portal_title: "PDF 與文件處理全方位精通（40+ 篇精選）",
  guides_portal_subtitle: "涵蓋履歷合併、發票整理、論文編碼、機密防護等 40 多篇實用技巧，助您輕鬆提升工作效率。",
  guides_search_placeholder: "搜尋指南標題或關鍵字（如：合併、壓縮、發票、手機...）",
  guides_cat_all: "全部",
  guides_cat_edit: "PDF 編輯",
  guides_cat_convert: "Office 轉換",
  guides_cat_security: "安全與隱私",
  guides_cat_media: "影音多媒體",
  guides_cat_mobile: "行動版技巧",
  guides_read_article: "閱讀指南",
  guides_direct_tool: "前往工具",
  guides_back_to_list: "返回指南列表",
  guides_quick_cta_title: "現在就親自體驗看看！",
  guides_share: "分享本篇指南",
  guides_copied: "連結已成功複製！",
  ad_label: "廣告贊助 / ADVERTISEMENT",
  ad_placeholder_title: "廣告最佳化版位",
  ad_placeholder_desc: "高品質廣告展示區域。",
  footer_security_title: "極致的隱私權與文件資安承諾",
  footer_security_desc: "mypickpdf 絕不會將您的文件上傳或儲存至任何伺服器。所有運算皆 100% 於您本機瀏覽器內安全執行。",
  footer_privacy_leak: "0% 數據外洩風險",
  footer_about: "與可愛小熊貓攜手，打造免登入、無費用負擔、極速簡便的次世代線上文件工具服務。",
  footer_col_tools: "熱門轉換工具",
  footer_col_tech: "技術架構與安全",
  footer_col_legal: "支援與政策規約",
  footer_privacy_link: "隱私權保護政策",
  footer_terms_link: "服務使用條款",
  footer_contact_link: "聯絡我們與建議",
  footer_rights: "All rights reserved. 版權所有，翻印必究。"
};

// --- SIMPLIFIED CHINESE (zh-CN) ---
const zhCN = {
  ...existing.zh,
  nav_select_lang: "选择语言 (Select Language)",
  nav_current_lang: "当前语言",
  badge_client_engine: "100% 浏览器客户端引擎",
  badge_security: "隐私安全",
  home_why_sec1_title: "100% 客户端本地安全",
  home_why_sec1_desc: "mypickpdf 采用 WebAssembly 直接在浏览器内存中运行，机密文档绝不上传至任何外部服务器。",
  home_why_sec2_title: "即时处理，无需上传等待",
  home_why_sec2_desc: "省去漫长的网络上传等待，借助设备本地算力在数秒内极速处理数十页文件。",
  home_faq_title: "常见问题 (FAQ)",
  home_faq_subtitle: "mypickpdf 服务使用与安全政策指南",
  home_faq_q1: "mypickpdf 真的完全免费且无需登录吗？",
  home_faq_a1: "是的！mypickpdf 永久 100% 免费，绝无注册、登录或付费门槛。",
  home_faq_q2: "转换文件时文件会被保存到服务器吗？",
  home_faq_a2: "绝不可能。所有转换与编辑均在浏览器本地内存中完成，服务器数据存储量为 0 Byte。",
  home_faq_q3: "转换后的 Office 文件（Word/Excel/PPT）可以编辑吗？",
  home_faq_a3: "当然可以！导出的 .docx, .xlsx, .pptx 格式与各大办公软件完全兼容，可自由修改与编辑。",
  home_to_pdf_sub: "(Word, Excel, PPT, 图片 ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, 图片, PDF/A)",
  share_title: "想推荐给身边的朋友与同事吗？🐾",
  share_desc: "1 秒复制链接并加入书签，随时快速访问！",
  share_btn: "分享链接",
  share_copied: "复制成功！🐾",
  share_bookmark: "加入书签",
  share_bookmark_tip: "按下 Ctrl + D（Mac: Cmd + D）即可立即收藏本站！",
  uploaded_card_success: "文件已安全成功加载！",
  uploaded_card_local_badge: "100% 本地加载完成",
  uploaded_card_change_file: "更换文件",
  uploaded_card_and_more: "等 {count} 个文件",
  uploaded_card_total_pages: "共 {count} 页",
  uploaded_card_file_size: "大小",
  uploaded_card_no_server: "零服务器上传（内存隔离保护）",
  processing_complete: "完成",
  processing_bubble: "正在以极速为您精心处理！🐾",
  howto_badge: "操作教程",
  howto_heading_suffix: " — 如何使用？",
  howto_subtitle: "无需安装复杂软件，只需 3 步即可轻松搞定。",
  faq_badge: "问答专区",
  faq_title: "常见问题 (FAQ)",
  faq_subtitle: "查阅有关 mypickpdf 工具使用与安全性的解答。"
};

// --- JAPANESE (ja) ---
const ja = {
  ...existing.ja,
  nav_select_lang: "言語選択 (Select Language)",
  nav_current_lang: "現在の言語",
  badge_client_engine: "100% ブラウザクライアントエンジン",
  badge_security: "セキュリティ",
  home_why_sec1_title: "100% クライアントローカル完結の安全性",
  home_why_sec1_desc: "mypickpdfはWebAssemblyとブラウザメモリ内で処理を行うため、ファイルが外部サーバーに送信されることはなく機密文書も安心です。",
  home_why_sec2_title: "待ち時間ゼロの即時処理",
  home_why_sec2_desc: "ネットワークのアップロード待ちなしに、お使いの端末の処理能力で数十ページを1〜2秒で高速変換します。",
  home_faq_title: "よくあるご質問 (FAQ)",
  home_faq_subtitle: "mypickpdfのご利用案内およびセキュリティポリシー",
  home_faq_q1: "mypickpdfは本当にログインや登録なしで完全無料ですか？",
  home_faq_a1: "はい！mypickpdfはログイン、会員登録、課金誘導を一切行わず、生涯100%無制限で無料提供しています。",
  home_faq_q2: "変換された文書データがサーバーに保存されることはありますか？",
  home_faq_a2: "絶対にありません。高度なWebAssemblyによりブラウザ内でのみ直接処理されるため、サーバー転送量は完全0バイトです。",
  home_faq_q3: "変換後のOfficeファイル（Word, Excel, PPT）は編集可能ですか？",
  home_faq_a3: "はい！抽出されたWord（.docx）、Excel（.xlsx）、PowerPoint（.pptx）は通常のMicrosoft Office等で自由にご編集いただけます。",
  home_to_pdf_sub: "(Word, Excel, PPT, 画像 ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, 画像, PDF/A)",
  share_title: "ご友人や同僚におすすめしませんか？🐾",
  share_desc: "1秒でリンクをコピー＆ブックマークして快適アクセス！",
  share_btn: "リンクを共有",
  share_copied: "コピー完了！🐾",
  share_bookmark: "ブックマーク",
  share_bookmark_tip: "キーボードの Ctrl + D (Mac: Cmd + D) で瞬時にブックマーク追加できます！",
  uploaded_card_success: "ファイルが安全かつ正常に読み込まれました！",
  uploaded_card_local_badge: "100% ローカル読み込み完了",
  uploaded_card_change_file: "別のファイルに変更",
  uploaded_card_and_more: "他 {count} 件",
  uploaded_card_total_pages: "合計 {count} ページ",
  uploaded_card_file_size: "サイズ",
  uploaded_card_no_server: "サーバー転送ゼロ（ブラウザメモリ隔離）",
  processing_complete: "完了",
  processing_bubble: "超高速でドキュメントを仕上げています！🐾",
  howto_badge: "かんたん手順",
  howto_heading_suffix: "の使い方",
  howto_subtitle: "複雑なソフトのインストール不要、わずか3ステップで完了します。",
  faq_badge: "Q&A",
  faq_title: "よくある質問 (FAQ)",
  faq_subtitle: "mypickpdfの機能やセキュリティに関する疑問をご確認ください。"
};

// Save files
fs.writeFileSync(path.join(outDir, 'hi.ts'), `import { TranslationDictionary } from "./types";\n\nexport const hi: TranslationDictionary = ${JSON.stringify(hi, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'zh-TW.ts'), `import { TranslationDictionary } from "./types";\n\nexport const zhTW: TranslationDictionary = ${JSON.stringify(zhTW, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'zh-CN.ts'), `import { TranslationDictionary } from "./types";\n\nexport const zhCN: TranslationDictionary = ${JSON.stringify(zhCN, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'ja.ts'), `import { TranslationDictionary } from "./types";\n\nexport const ja: TranslationDictionary = ${JSON.stringify(ja, null, 2)};\n`);

console.log('Generated hi.ts, zh-TW.ts, zh-CN.ts, ja.ts');
