const fs = require('fs');
const path = require('path');

const outDir = path.join(__dirname, '../src/lib/translations');
const existing = require('../existing_translations.json');

// --- THAI (th) ---
const th = {
  brand_name: "mypickpdf (แพนด้าแดง PDF)",
  nav_brand_tag: "เครื่องมือ PDF ฟรี 100% ปลอดภัย ไร้กังวลกับแพนด้าแดง",
  nav_all_tools: "เครื่องมือ PDF ทั้งหมด",
  nav_convert_pdf: "แปลง PDF",
  nav_to_pdf: "แปลงเป็น PDF",
  nav_from_pdf: "แปลงจาก PDF",
  nav_privacy_badge: "ไม่บันทึกข้อมูลบนเซิร์ฟเวอร์ 0%",
  nav_free_badge: "ฟรีไม่จำกัด ไม่ต้องลงชื่อเข้าใช้",
  nav_guides: "คู่มือการใช้งาน",
  nav_core_tools: "เครื่องมือแก้ไข PDF",
  nav_media_tools: "เครื่องมือวิดีโอและมีเดีย",
  nav_select_lang: "เลือกภาษา (Select Language)",
  nav_current_lang: "ภาษาปัจจุบัน",
  badge_free_utility: "ยูทิลิตี้ฟรี 100%",
  badge_no_server: "ไม่มีการส่งข้อมูลไปเซิร์ฟเวอร์ (ประมวลผลในเครื่อง)",
  badge_no_login: "ไม่ต้องสมัครสมาชิกหรือเข้าสู่ระบบ",
  badge_unlimited_free: "ฟรีไม่จำกัดความเร็วสูง",
  badge_client_engine: "เอนจินประมวลผลบนเบราว์เซอร์ 100%",
  badge_security: "ความปลอดภัย",
  tool_merge: "รวม PDF",
  tool_merge_desc: "รวมไฟล์ PDF หลายไฟล์ให้เป็นเอกสารเดียวอย่างง่ายดาย",
  tool_split: "แยก PDF",
  tool_split_desc: "แยกหน้าเฉพาะหรือแบ่งไฟล์ PDF แต่ละหน้าอย่างรวดเร็ว",
  tool_compress: "บีบอัด PDF",
  tool_compress_desc: "ลดขนาดไฟล์ PDF โดยยังคงคุณภาพสูงสุด",
  tool_rotate: "หมุน PDF",
  tool_rotate_desc: "หมุนเอกสาร PDF 90 องศาหรือ 180 องศา",
  tool_ocr: "PDF OCR (ตรวจจับข้อความ)",
  tool_ocr_desc: "ดึงข้อความจากเอกสาร PDF หรือรูปภาพที่สแกน",
  tool_page_numbers: "ใส่เลขหน้า",
  tool_page_numbers_desc: "แทรกหมายเลขหน้าในตำแหน่งที่กำหนดได้อย่างง่ายดาย",
  tool_watermark: "ใส่ลายน้ำ",
  tool_watermark_desc: "เพิ่มข้อความหรือลายน้ำความลับลงในเอกสาร",
  tool_compress_video: "บีบอัดวิดีโอ",
  tool_compress_video_desc: "ลดขนาดวิดีโอ MP4, MOV ได้สูงสุดถึง 80% โดยไม่สูญเสียความคมชัด",
  tool_video_to_gif: "แปลงวิดีโอเป็น GIF",
  tool_video_to_gif_desc: "แปลงคลิปวิดีโอเป็นไฟล์ภาพเคลื่อนไหว GIF คุณภาพสูง",
  tool_img_to_pdf: "แปลงรูปภาพเป็น PDF",
  tool_img_to_pdf_desc: "แปลงภาพ JPG, PNG ให้เป็นเอกสาร PDF คมชัด",
  tool_word_to_pdf: "Word เป็น PDF",
  tool_word_to_pdf_desc: "แปลงเอกสาร Word (.docx) เป็น PDF ทันที",
  tool_ppt_to_pdf: "PowerPoint เป็น PDF",
  tool_ppt_to_pdf_desc: "แปลงสไลด์ PPTX เป็นเอกสาร PDF อย่างสมบูรณ์",
  tool_excel_to_pdf: "Excel เป็น PDF",
  tool_excel_to_pdf_desc: "แปลงตารางคำนวณ XLSX ให้เป็นเอกสาร PDF",
  tool_html_to_pdf: "HTML เป็น PDF",
  tool_html_to_pdf_desc: "แปลงโค้ดเว็บ HTML ให้กลายเป็น PDF",
  tool_pdf_to_img: "PDF เป็นรูปภาพ",
  tool_pdf_to_img_desc: "บันทึกแต่ละหน้าของ PDF เป็นไฟล์ภาพ JPG ความละเอียดสูง",
  tool_pdf_to_word: "PDF เป็น Word",
  tool_pdf_to_word_desc: "แปลง PDF ให้เป็นเอกสาร Word (.docx) ที่แก้ไขได้",
  tool_pdf_to_ppt: "PDF เป็น PowerPoint",
  tool_pdf_to_ppt_desc: "แปลงเอกสาร PDF เป็นสไลด์ PowerPoint (.pptx)",
  tool_pdf_to_excel: "PDF เป็น Excel",
  tool_pdf_to_excel_desc: "ดึงตารางจาก PDF ไปเป็นสเปรดชีต Excel (.xlsx)",
  tool_pdf_to_pdfa: "PDF เป็น PDF/A",
  tool_pdf_to_pdfa_desc: "แปลงเป็นรูปแบบมาตรฐาน ISO PDF/A สำหรับจัดเก็บระยะยาว",
  tool_pdf_to_hwp: "PDF เป็น HWP/HWPX",
  tool_pdf_to_hwp_desc: "แปลง PDF เป็นเอกสารมาตรฐานฮันกึล (.hwpx / .hwp)",
  btn_select_files: "เลือกไฟล์",
  drop_title_default: "ลากและวางไฟล์ที่นี่",
  drop_subtitle_default: "หรือคลิกปุ่มด้านล่างเพื่อเลือกไฟล์จากอุปกรณ์",
  drop_note_privacy: "🔒 ประมวลผลในเบราว์เซอร์ 100% (ไม่มีการบันทึกบนเซิร์ฟเวอร์)",
  drop_note_limit: "รองรับขนาดไฟล์ไม่จำกัด",
  drop_badge_secure: "โหลดไฟล์ปลอดภัยในเครื่อง 100%",
  drop_mascot_bubble: "วางตรงนี้ได้เลย! 🐾",
  drop_drag_title: "ปล่อยมือเพื่อโหลดไฟล์ทันที!",
  drop_drag_desc: "วางลงในกล่องหรือปุ่มได้อย่างปลอดภัย รวดเร็วทันใจ",
  drop_action_drop: "ปล่อยไฟล์ที่นี่ (Drop)",
  btn_download_again: "ดาวน์โหลดไฟล์",
  btn_reset: "รีเซ็ตทั้งหมด",
  btn_add_files: "เพิ่มไฟล์",
  processing_title: "แพนด้าแดงกำลังแปลงเอกสารของคุณอย่างปลอดภัย...",
  processing_desc: "กรุณารอสักครู่ เมื่อเสร็จแล้วระบบจะเริ่มดาวน์โหลดโดยอัตโนมัติ",
  processing_badge: "ประมวลผลบนหน่วยความจำของเบราว์เซอร์ 100%",
  processing_complete: "เสร็จสมบูรณ์",
  processing_bubble: "กำลังปรับแต่งเอกสารของคุณด้วยความเร็วสูง! 🐾",
  uploaded_card_success: "โหลดไฟล์สำเร็จและปลอดภัยแล้ว!",
  uploaded_card_local_badge: "โหลดในเครื่อง 100%",
  uploaded_card_change_file: "เปลี่ยนไฟล์",
  uploaded_card_and_more: "และอีก {count} ไฟล์",
  uploaded_card_total_pages: "รวม {count} หน้า",
  uploaded_card_file_size: "ขนาด",
  uploaded_card_no_server: "ไม่มีการอัปโหลดไปเซิร์ฟเวอร์ (แยกหน่วยความจำ)",
  home_mascot_bubble: "สวัสดี! ฉันคือแพนด้าแดง 🐾 ส่งเอกสารใดๆ ให้ฉันดูแลได้เลย!",
  home_hero_tag: "โซลูชัน PDF บนเบราว์เซอร์ ฟรี 100% ร่วมกับแพนด้าแดงสุดน่ารัก",
  home_hero_title1: "น่ารักที่สุด รวดเร็ว และปลอดภัยที่สุด",
  home_hero_title2: "ชุดเครื่องมือออนไลน์ mypickpdf",
  home_hero_desc: "แปลงไฟล์ Word, Excel, PowerPoint และรูปภาพเป็น PDF บีบอัดและแก้ไขได้อย่างง่ายดาย ปลอดภัย 100% ในเบราว์เซอร์ ไม่ทิ้งข้อมูลบนเซิร์ฟเวอร์แม้แต่ไบต์เดียว",
  home_tools_title: "เครื่องมือยอดนิยมที่แนะนำ",
  home_tools_subtitle: "เลือกงานที่ต้องการและเริ่มใช้งานได้ทันที",
  home_use_now: "ใช้งานทันที",
  home_convert_btn: "แปลงไฟล์",
  home_extract_btn: "ดึงข้อมูล",
  sponsor_snack_btn: "เลี้ยงขนมแพนด้าแดง ☕",
  home_why_title: "ทำไมผู้ใช้ทั่วโลกจึงเลือก mypickpdf?",
  home_table_title: "เปรียบเทียบเว็บไซต์แบบเสียเงินทั่วไป vs mypickpdf",
  home_why_sec1_title: "ความปลอดภัยในเครื่องผู้ใช้ 100%",
  home_why_sec1_desc: "mypickpdf ใช้ WebAssembly ทำงานในหน่วยความจำของเบราว์เซอร์โดยตรง เอกสารสำคัญของคุณจะไม่ถูกส่งไปยังเซิร์ฟเวอร์ภายนอก",
  home_why_sec2_title: "ประมวลผลทันที ไม่ต้องรออัปโหลด",
  home_why_sec2_desc: "ไม่ต้องเสียเวลารออัปโหลดเครือข่าย ใช้พลังประมวลผลของอุปกรณ์จัดการเอกสารหลายสิบหน้าในเวลาเพียง 1-2 วินาที",
  home_faq_title: "คำถามที่พบบ่อย (FAQ)",
  home_faq_subtitle: "คำแนะนำการใช้งานและนโยบายความปลอดภัยของ mypickpdf",
  home_faq_q1: "mypickpdf ใช้งานได้ฟรีจริงโดยไม่ต้องลงทะเบียนหรือไม่?",
  home_faq_a1: "ใช่! mypickpdf ให้บริการฟรีตลอดชีพ 100% ไม่ต้องลงชื่อเข้าใช้ ไม่ต้องกรอกข้อมูลส่วนตัว และไม่มีค่าใช้จ่ายแอบแฝง",
  home_faq_q2: "ไฟล์ที่แปลงจะถูกจัดเก็บไว้บนเซิร์ฟเวอร์หรือไม่?",
  home_faq_a2: "ไม่มีทาง เอกสารทั้งหมดถูกประมวลผลเฉพาะในหน่วยความจำของอุปกรณ์ และส่งข้อมูลภายนอก 0 ไบต์",
  home_faq_q3: "ไฟล์ Office (Word, Excel, PPT) ที่แปลงแล้วสามารถแก้ไขได้หรือไม่?",
  home_faq_a3: "ได้แน่นอน! ไฟล์ Word, Excel และ PowerPoint ที่แปลงแล้วสามารถเปิดและแก้ไขได้อย่างอิสระบน Microsoft Office และโปรแกรมอื่นๆ",
  home_to_pdf_sub: "(Word, Excel, PPT, รูปภาพ ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, รูปภาพ, PDF/A, HWP)",
  share_title: "ต้องการแนะนำให้เพื่อนและเพื่อนร่วมงานหรือไม่? 🐾",
  share_desc: "คัดลอกลิงก์ใน 1 วินาที & บุ๊กมาร์กไว้เพื่อเข้าถึงอย่างรวดเร็ว!",
  share_btn: "แชร์ลิงก์",
  share_copied: "คัดลอกเรียบร้อย! 🐾",
  share_bookmark: "บุ๊กมาร์ก",
  share_bookmark_tip: "กด Ctrl + D (Mac: Cmd + D) เพื่อบุ๊กมาร์กหน้านี้ทันที!",
  video_title: "บีบอัดวิดีโอ (MP4 / MOV)",
  video_header_sub: "ลดขนาดไฟล์ MP4 / MOV",
  video_desc: "ลดขนาดวิดีโอลงสูงสุด 80% เพื่อส่งทางแชทหรือแนบอีเมลโดยยังคงความคมชัด ประมวลผลในเบราว์เซอร์ 100%",
  video_tag: "ฟีเจอร์ใหม่",
  video_drop_title: "เลือกไฟล์วิดีโอที่ต้องการบีบอัด",
  video_drop_subtitle: "รองรับวิดีโอ MP4, MOV, WebM, MKV ทุกรูปแบบ (ไม่มีการอัปโหลดไปเซิร์ฟเวอร์)",
  video_badge_local: "ประมวลผลในเครื่อง 100% (ไม่บันทึกลงเซิร์ฟเวอร์)",
  video_badge_hardware: "การเข้ารหัสความเร็วสูงด้วยฮาร์ดแวร์",
  video_badge_mobile: "รองรับมือถือ (iPhone/Android) เต็มรูปแบบ",
  video_step_level: "เลือกระดับการบีบอัด",
  video_step_level_desc: "เลือกระดับคุณภาพและขนาดไฟล์ตามที่คุณต้องการ",
  video_opt_extreme_title: "บีบอัดสูงสุด (สำหรับแชทและอีเมล)",
  video_opt_extreme_sub: "ลดขนาดไฟล์ได้สูงสุด 70~85%",
  video_opt_extreme_desc: "เหมาะที่สุดสำหรับการส่งผ่านแอปแชท แนบอีเมล หรืออัปโหลดบนเว็บบอร์ด",
  video_opt_extreme_badge: "ขนาดเล็กที่สุด",
  video_opt_rec_title: "บีบอัดแนะนำ (สมดุลมาตรฐาน)",
  video_opt_rec_sub: "ลดขนาดไฟล์ประมาณ 40~60%",
  video_opt_rec_desc: "ตัวเลือกที่แนะนำมากที่สุด ซึ่งให้ความคมชัดและลดขนาดไฟล์ได้อย่างลงตัว",
  video_opt_rec_badge: "แนะนำเป็นพิเศษ",
  video_opt_less_title: "รักษาความคมชัดสูง (บีบอัดเล็กน้อย)",
  video_opt_less_sub: "ลดขนาดไฟล์ประมาณ 20~30%",
  video_opt_less_desc: "รักษาความละเอียดและรายละเอียดเดิมอย่างสมบูรณ์แบบ",
  video_opt_less_badge: "เน้นคุณภาพ",
  video_selected: "เลือกแล้ว",
  video_btn_compress: "เริ่มบีบอัดวิดีโอ",
  video_compressing: "กำลังบีบอัดวิดีโอ...",
  video_btn_reset: "บีบอัดวิดีโอใหม่",
  video_result_title: "บีบอัดวิดีโอสำเร็จ!",
  video_result_desc: "ขนาดไฟล์ลดลงอย่างมากด้วยการเร่งความเร็วในเบราว์เซอร์",
  video_original: "ขนาดต้นฉบับ",
  video_compressed: "ขนาดหลังบีบอัด",
  video_saved: "ประหยัดไปได้",
  howto_badge: "บทช่วยสอนด่วน",
  howto_heading_suffix: " — ใช้งานอย่างไร?",
  howto_subtitle: "ทำเสร็จง่ายๆ ใน 3 ขั้นตอนโดยไม่ต้องติดตั้งโปรแกรมเพิ่มเติม",
  faq_badge: "ถาม-ตอบ",
  faq_title: "คำถามที่พบบ่อย (FAQ)",
  faq_subtitle: "ค้นหาคำตอบเกี่ยวกับการใช้งานเครื่องมือและความเป็นส่วนตัว",
  guides_portal_badge: "คู่มืออย่างเป็นทางการของ mypickpdf",
  guides_portal_title: "เจาะลึกการใช้งาน PDF และเอกสาร (40+ บทความ)",
  guides_portal_subtitle: "ตั้งแต่การรวมเรซูเม่ ใบกำกับภาษี การใส่เลขหน้าวิทยานิพนธ์ ไปจนถึงความปลอดภัย เรียนรู้ทุกอย่างได้ที่นี่",
  guides_search_placeholder: "ค้นหาชื่อคู่มือหรือคำสำคัญ (เช่น รวมไฟล์, บีบอัด, มือถือ...)",
  guides_cat_all: "ทั้งหมด",
  guides_cat_edit: "การแก้ไข PDF",
  guides_cat_convert: "แปลงไฟล์ Office",
  guides_cat_security: "ความปลอดภัยและความเป็นส่วนตัว",
  guides_cat_media: "มีเดีย & GIF",
  guides_cat_mobile: "การใช้งานบนมือถือ",
  guides_read_article: "อ่านคู่มือ",
  guides_direct_tool: "เปิดเครื่องมือ",
  guides_back_to_list: "กลับไปยังรายการคู่มือ",
  guides_quick_cta_title: "ลองทำด้วยตัวเองตอนนี้เลย!",
  guides_share: "แชร์คู่มือนี้",
  guides_copied: "คัดลอกลิงก์สำเร็จ!",
  ad_label: "โฆษณา / ADVERTISEMENT",
  ad_placeholder_title: "พื้นที่โฆษณาที่สนับสนุน",
  ad_placeholder_desc: "พื้นที่แสดงโฆษณาเพื่อสนับสนุนการให้บริการฟรี",
  footer_security_title: "รับประกันความเป็นส่วนตัวและความปลอดภัยของเอกสารอย่างสมบูรณ์",
  footer_security_desc: "mypickpdf จะไม่ส่งหรือจัดเก็บไฟล์ของคุณบนเซิร์ฟเวอร์ระยะไกลใดๆ การแปลงทั้งหมดดำเนินการในเบราว์เซอร์ของคุณ 100%",
  footer_privacy_leak: "ข้อมูลรั่วไหลภายนอก 0%",
  footer_about: "บริการเว็บยูทิลิตี้รุ่นใหม่ร่วมกับแพนด้าแดงสุดน่ารัก ให้ทุกคนแก้ไขและแปลงไฟล์ PDF ได้ง่ายและรวดเร็วที่สุดโดยไม่ต้องเข้าสู่ระบบและไม่มีค่าใช้จ่าย",
  footer_col_tools: "เครื่องมือยอดนิยม",
  footer_col_tech: "เทคโนโลยีและความปลอดภัย",
  footer_col_legal: "ช่วยเหลือและข้อกำหนด",
  footer_privacy_link: "นโยบายความเป็นส่วนตัว",
  footer_terms_link: "เงื่อนไขการใช้บริการ",
  footer_contact_link: "ติดต่อเราและข้อเสนอแนะ",
  footer_rights: "All rights reserved. สงวนลิขสิทธิ์ทั้งหมด"
};

// --- MALAY (ms) ---
const ms = {
  brand_name: "mypickpdf (Panda Merah PDF)",
  nav_brand_tag: "Alatan PDF 100% Percuma & Selamat Bersama Panda Merah",
  nav_all_tools: "Semua Alatan PDF",
  nav_convert_pdf: "Tukar PDF",
  nav_to_pdf: "Tukar ke PDF",
  nav_from_pdf: "Tukar daripada PDF",
  nav_privacy_badge: "0% Storan Pelayan",
  nav_free_badge: "Percuma Tanpa Had, Tiada Daftar Masuk",
  nav_guides: "Panduan",
  nav_core_tools: "Alatan Suntingan PDF",
  nav_media_tools: "Alatan Video & Media",
  nav_select_lang: "Pilih Bahasa (Select Language)",
  nav_current_lang: "Bahasa Semasa",
  badge_free_utility: "Utiliti Percuma 100%",
  badge_no_server: "Tiada Penghantaran Pelayan (Pemprosesan Selamat Tempatan)",
  badge_no_login: "Tiada Daftar / Log Masuk Diperlukan",
  badge_unlimited_free: "Pantas Tanpa Had & Percuma",
  badge_client_engine: "Enjin Sisi Klien Pelayar 100%",
  badge_security: "Keselamatan",
  tool_merge: "Gabung PDF",
  tool_merge_desc: "Gabungkan beberapa fail PDF menjadi satu dokumen tunggal",
  tool_split: "Pisahkan PDF",
  tool_split_desc: "Ekstrak halaman tertentu atau asingkan setiap halaman",
  tool_compress: "Mampatkan PDF",
  tool_compress_desc: "Kurangkan saiz fail PDF sambil mengekalkan kualiti maksimum",
  tool_rotate: "Putar PDF",
  tool_rotate_desc: "Putar dokumen PDF sebanyak 90 atau 180 darjah",
  tool_ocr: "PDF OCR (Pengecaman Teks)",
  tool_ocr_desc: "Ekstrak teks daripada dokumen PDF atau imej yang diimbas",
  tool_page_numbers: "Tambah Nombor Halaman",
  tool_page_numbers_desc: "Sisipkan nombor halaman mengikut kedudukan pilihan anda",
  tool_watermark: "Tambah Tera Air",
  tool_watermark_desc: "Tambah teks atau tera air sulit ke dalam dokumen",
  tool_compress_video: "Mampatkan Video",
  tool_compress_video_desc: "Kecilkan saiz MP4/MOV sehingga 80% tanpa kehilangan kualiti ketara",
  tool_video_to_gif: "Video ke GIF",
  tool_video_to_gif_desc: "Tukar klip video kepada animasi GIF berkualiti tinggi",
  tool_img_to_pdf: "Imej ke PDF",
  tool_img_to_pdf_desc: "Tukar gambar JPG dan PNG kepada dokumen PDF berkualiti tinggi",
  tool_word_to_pdf: "Word ke PDF",
  tool_word_to_pdf_desc: "Tukar dokumen Word (.docx) kepada PDF dengan serta-merta",
  tool_ppt_to_pdf: "PowerPoint ke PDF",
  tool_ppt_to_pdf_desc: "Tukar slaid PowerPoint (.pptx) kepada dokumen PDF",
  tool_excel_to_pdf: "Excel ke PDF",
  tool_excel_to_pdf_desc: "Tukar helaian kerja Excel (.xlsx) kepada PDF kemas",
  tool_html_to_pdf: "HTML ke PDF",
  tool_html_to_pdf_desc: "Jadikan kod HTML laman web terus sebagai fail PDF",
  tool_pdf_to_img: "PDF ke Imej",
  tool_pdf_to_img_desc: "Simpan setiap halaman PDF sebagai imej JPG resolusi tinggi",
  tool_pdf_to_word: "PDF ke Word",
  tool_pdf_to_word_desc: "Ekstrak dokumen PDF kepada format Word (.docx) boleh disunting",
  tool_pdf_to_ppt: "PDF ke PowerPoint",
  tool_pdf_to_ppt_desc: "Tukar fail PDF kepada slaid pembentangan PowerPoint (.pptx)",
  tool_pdf_to_excel: "PDF ke Excel",
  tool_pdf_to_excel_desc: "Ekstrak jadual PDF kepada helaian kerja Excel (.xlsx)",
  tool_pdf_to_pdfa: "PDF ke PDF/A",
  tool_pdf_to_pdfa_desc: "Tukar ke format piawaian ISO PDF/A untuk pengarkiban jangka panjang",
  tool_pdf_to_hwp: "PDF ke HWP/HWPX",
  tool_pdf_to_hwp_desc: "Tukar PDF ke dokumen rasmi format Hangul (.hwpx / .hwp)",
  btn_select_files: "Pilih Fail",
  drop_title_default: "Seret & lepaskan fail di sini",
  drop_subtitle_default: "atau klik butang di bawah untuk memilih fail",
  drop_note_privacy: "🔒 100% pemprosesan pelayar tempatan (tiada storan pelayan)",
  drop_note_limit: "Sokongan saiz fail tanpa had",
  drop_badge_secure: "Muatnaik selamat tempatan 100%",
  drop_mascot_bubble: "Letakkan di sini! 🐾",
  drop_drag_title: "Lepaskan tetikus untuk muatkan fail serta-merta!",
  drop_drag_desc: "Sama ada pada butang atau kotak, fail diproses dengan pantas dan selamat",
  drop_action_drop: "Lepaskan fail di sini (Drop)",
  btn_download_again: "Muat Turun Fail",
  btn_reset: "Tetapkan Semula",
  btn_add_files: "Tambah Fail",
  processing_title: "Panda Merah sedang memproses dokumen anda dengan selamat...",
  processing_desc: "Sila tunggu sebentar. Muat turun akan bermula secara automatik setelah siap.",
  processing_badge: "100% pemprosesan memori pelayar tempatan",
  processing_complete: "Selesai",
  processing_bubble: "Sedang menyiapkan dokumen anda dengan kelajuan tinggi! 🐾",
  uploaded_card_success: "Fail telah dimuatkan dengan selamat dan berjaya!",
  uploaded_card_local_badge: "100% Muatan Tempatan",
  uploaded_card_change_file: "Tukar Fail",
  uploaded_card_and_more: "+ {count} lagi fail",
  uploaded_card_total_pages: "Jumlah {count} halaman",
  uploaded_card_file_size: "Saiz",
  uploaded_card_no_server: "Tiada Muat Naik Pelayan (Pengasingan Memori)",
  home_mascot_bubble: "Hai! Saya Panda Merah 🐾 Serahkan apa sahaja dokumen kepada saya!",
  home_hero_tag: "Penyelesaian PDF Dalam Pelayar 100% Percuma Bersama Panda Merah",
  home_hero_title1: "Paling Comel, Pantas & Paling Selamat",
  home_hero_title2: "Suit Dalam Talian mypickpdf",
  home_hero_desc: "Tukar, mampatkan dan sunting Word, Excel, PowerPoint dan imej ke/daripada PDF dengan mudah. 100% pemprosesan dalam pelayar peribadi yang meninggalkan 0 bait di pelayan.",
  home_tools_title: "Alatan Popular Disyorkan",
  home_tools_subtitle: "Pilih alatan yang anda perlukan dan mulakan dengan segera",
  home_use_now: "Guna Sekarang",
  home_convert_btn: "Tukar",
  home_extract_btn: "Ekstrak",
  sponsor_snack_btn: "Taja Snek Panda Merah ☕",
  home_why_title: "Mengapa berjuta pengguna memilih mypickpdf?",
  home_table_title: "Perbandingan Laman Berbayar Biasa vs mypickpdf",
  home_why_sec1_title: "100% Keselamatan Tempatan Sisi Klien",
  home_why_sec1_desc: "mypickpdf menggunakan WebAssembly untuk memproses dokumen terus dalam memori peranti anda. Fail sulit tidak pernah dihantar ke pelayan luaran.",
  home_why_sec2_title: "Pemprosesan Segera Tanpa Menunggu",
  home_why_sec2_desc: "Tiada masa menunggu muat naik rangkaian. Memanfaatkan kuasa peranti anda untuk memproses berpuluh halaman dalam 1-2 saat.",
  home_faq_title: "Soalan Lazim (FAQ)",
  home_faq_subtitle: "Garis panduan penggunaan dan dasar keselamatan mypickpdf",
  home_faq_q1: "Adakah mypickpdf benar-benar percuma tanpa perlu daftar masuk?",
  home_faq_a1: "Ya! mypickpdf percuma sepenuhnya selamanya tanpa sebarang pendaftaran, log masuk atau caj tersembunyi.",
  home_faq_q2: "Adakah fail dokumen yang ditukar disimpan di pelayan?",
  home_faq_a2: "Sama sekali tidak. Segala proses penukaran berjalan dalam ingatan peranti anda dan 0 bait dihantar ke pelayan luar.",
  home_faq_q3: "Bolehkah fail Office (Word, Excel, PPT) yang ditukar disunting?",
  home_faq_a3: "Ya! Fail Word, Excel dan PowerPoint yang diekstrak serasi sepenuhnya dengan Microsoft Office dan boleh diedit dengan bebas.",
  home_to_pdf_sub: "(Word, Excel, PPT, Imej ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, Imej, PDF/A, HWP)",
  share_title: "Ingin cadangkan kepada rakan & rakan sekerja? 🐾",
  share_desc: "Salin pautan dalam 1 saat & tandakan laman untuk akses pantas!",
  share_btn: "Kongsi Pautan",
  share_copied: "Berjaya Disalin! 🐾",
  share_bookmark: "Tanda Laman",
  share_bookmark_tip: "Tekan Ctrl + D (Mac: Cmd + D) untuk menanda buku laman ini serta-merta!",
  video_title: "Mampatkan Video (MP4 / MOV)",
  video_header_sub: "Kecilkan Saiz Fail MP4 / MOV",
  video_desc: "Kecilkan saiz video sehingga 80% untuk penghantaran chat atau e-mel tanpa kehilangan kualiti ketara. 100% dalam pelayar tempatan.",
  video_tag: "Ciri Baharu",
  video_drop_title: "Pilih fail video untuk dimampatkan",
  video_drop_subtitle: "Menyokong semua video MP4, MOV, WebM, MKV (tiada muat naik ke pelayan)",
  video_badge_local: "100% Pemprosesan Peranti Tempatan (Tiada Storan Pelayan)",
  video_badge_hardware: "Pengekodan Berkelajuan Tinggi Pecutan Perkakasan",
  video_badge_mobile: "Sokongan Penuh Telefon Pintar (iPhone/Android)",
  video_step_level: "Pilih Tahap Mampatan",
  video_step_level_desc: "Pilih tahap kualiti dan saiz fail mengikut keperluan anda",
  video_opt_extreme_title: "Mampatan Maksimum (untuk chat/emel)",
  video_opt_extreme_sub: "Penjimatan saiz sehingga 70~85%",
  video_opt_extreme_desc: "Sangat sesuai untuk perkongsian melalui aplikasi mesej dan lampiran e-mel.",
  video_opt_extreme_badge: "Saiz Terkecil",
  video_opt_rec_title: "Mampatan Seimbang (Disyorkan)",
  video_opt_rec_sub: "Penjimatan saiz sekitar 40~60%",
  video_opt_rec_desc: "Pilihan terbaik yang mengimbangi kualiti gambar jelas dengan pengurangan saiz yang ketara.",
  video_opt_rec_badge: "Paling Disyorkan",
  video_opt_less_title: "Kekalkan Kualiti Tinggi (Mampatan Ringan)",
  video_opt_less_sub: "Penjimatan saiz sekitar 20~30%",
  video_opt_less_desc: "Mengekalkan resolusi dan perincian asal secara optimum.",
  video_opt_less_badge: "Utamakan Kualiti",
  video_selected: "Dipilih",
  video_btn_compress: "Mampatkan Video Sekarang",
  video_compressing: "Sedang memampatkan video...",
  video_btn_reset: "Mampatkan Video Baharu",
  video_result_title: "Mampatan Video Selesai!",
  video_result_desc: "Saiz fail telah dikurangkan secara drastik dengan pecutan dalam pelayar.",
  video_original: "Saiz Asal",
  video_compressed: "Saiz Selepas Mampatan",
  video_saved: "Saiz Dijimatkan",
  howto_badge: "Tutorial Ringkas",
  howto_heading_suffix: " — Bagaimana Menggunakannya?",
  howto_subtitle: "Selesaikan tugasan anda dalam 3 langkah mudah tanpa perlu memasang perisian rumit.",
  faq_badge: "Soal Jawab",
  faq_title: "Soalan Lazim (FAQ)",
  faq_subtitle: "Dapatkan jawapan mengenai penggunaan alatan dan privasi data.",
  guides_portal_badge: "Buku Panduan Rasmi mypickpdf",
  guides_portal_title: "Kuasai Aliran Kerja PDF & Dokumen (40+ Panduan Praktikal)",
  guides_portal_subtitle: "Daripada penyatuan resume, invois cukai, penomboran tesis hingga keselamatan dokumen tempatan.",
  guides_search_placeholder: "Cari tajuk panduan atau kata kunci (cth: gabung, mampat, mudah alih...)",
  guides_cat_all: "Semua",
  guides_cat_edit: "Suntingan PDF",
  guides_cat_convert: "Penukaran Dokumen",
  guides_cat_security: "Keselamatan & Privasi",
  guides_cat_media: "Media & GIF",
  guides_cat_mobile: "Petua Mudah Alih",
  guides_read_article: "Baca Panduan",
  guides_direct_tool: "Buka Alatan",
  guides_back_to_list: "Kembali ke Senarai Panduan",
  guides_quick_cta_title: "Cuba Sendiri Sekarang!",
  guides_share: "Kongsi Panduan Ini",
  guides_copied: "Pautan Berjaya Disalin!",
  ad_label: "Iklan / ADVERTISEMENT",
  ad_placeholder_title: "Ruang Iklan Tajaan",
  ad_placeholder_desc: "Ruang paparan iklan untuk mengekalkan perkhidmatan percuma ini.",
  footer_security_title: "Jaminan Keselamatan Dokumen & Privasi Mutlak",
  footer_security_desc: "mypickpdf tidak akan memuat naik atau menyimpan fail anda di mana-mana pelayan jauh. Semua proses berjalan 100% dalam pelayar tempatan anda.",
  footer_privacy_leak: "0% Kebocoran Data Luaran",
  footer_about: "Perkhidmatan web generasi baharu bersama Panda Merah yang comel, membolehkan sesiapa sahaja menyunting dan menukar PDF dengan pantas tanpa pendaftaran.",
  footer_col_tools: "Alatan Popular",
  footer_col_tech: "Teknologi & Keselamatan",
  footer_col_legal: "Sokongan & Dasar",
  footer_privacy_link: "Dasar Privasi",
  footer_terms_link: "Syarat Perkhidmatan",
  footer_contact_link: "Hubungi & Cadangan",
  footer_rights: "All rights reserved. Hak cipta terpelihara."
};

// --- INDONESIAN (id) - Complete 185 keys ---
const id = {
  ...existing.id,
  nav_select_lang: "Pilih Bahasa (Select Language)",
  nav_current_lang: "Bahasa Saat Ini",
  badge_client_engine: "100% Mesin Sisi Klien Peramban",
  badge_security: "Keamanan",
  home_why_sec1_title: "100% Keamanan Lokal Sisi Klien",
  home_why_sec1_desc: "mypickpdf memproses file langsung di memori peramban Anda menggunakan WebAssembly. Dokumen rahasia Anda tidak pernah menyentuh server luar.",
  home_why_sec2_title: "Pemrosesan Instan Tanpa Menunggu",
  home_why_sec2_desc: "Tanpa waktu tunggu unggah jaringan. Memanfaatkan komputasi perangkat Anda untuk memproses puluhan halaman dalam 1-2 detik.",
  home_faq_title: "Pertanyaan yang Sering Diajukan (FAQ)",
  home_faq_subtitle: "Panduan penggunaan dan kebijakan keamanan mypickpdf",
  home_faq_q1: "Apakah mypickpdf benar-benar 100% gratis tanpa perlu mendaftar?",
  home_faq_a1: "Ya! mypickpdf sepenuhnya gratis selamanya tanpa registrasi, tanpa login, dan tanpa biaya tersembunyi.",
  home_faq_q2: "Apakah dokumen yang dikonversi disimpan di server?",
  home_faq_a2: "Sama sekali tidak. Semua dokumen diproses secara eksklusif dalam memori perangkat Anda dan nol bita yang ditransfer keluar.",
  home_faq_q3: "Apakah file Office (Word, Excel, PPT) yang dikonversi dapat diedit?",
  home_faq_a3: "Ya! File Word (.docx), Excel (.xlsx), dan PowerPoint (.pptx) yang diekstrak sepenuhnya dapat diedit di Microsoft Office dan perangkat lunak lainnya.",
  home_to_pdf_sub: "(Word, Excel, PPT, Gambar ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, Gambar, PDF/A, HWP)",
  share_title: "Ingin merekomendasikan ke teman & kolega? 🐾",
  share_desc: "Salin tautan dalam 1 detik & buat penanda untuk akses cepat!",
  share_btn: "Bagikan Tautan",
  share_copied: "Tersalin! 🐾",
  share_bookmark: "Penanda Halaman",
  share_bookmark_tip: "Tekan Ctrl + D (Mac: Cmd + D) untuk langsung menyimpan situs ini!",
  uploaded_card_success: "File berhasil dimuat dengan aman!",
  uploaded_card_local_badge: "100% Muatan Lokal",
  uploaded_card_change_file: "Ganti File",
  uploaded_card_and_more: "+ {count} lainnya",
  uploaded_card_total_pages: "Total {count} halaman",
  uploaded_card_file_size: "Ukuran",
  uploaded_card_no_server: "Tanpa Unggah Server (Isolasi Memori)",
  processing_complete: "Selesai",
  processing_bubble: "Menyiapkan dokumen Anda secepat kilat! 🐾",
  howto_badge: "Tutorial Cepat",
  howto_heading_suffix: " — Cara Menggunakan",
  howto_subtitle: "Selesaikan tugas dalam 3 langkah mudah tanpa perlu memasang perangkat lunak rumit.",
  faq_badge: "Tanya Jawab",
  faq_title: "Pertanyaan yang Sering Diajukan (FAQ)",
  faq_subtitle: "Temukan jawaban tentang penggunaan alat dan privasi dokumen Anda."
};

// --- VIETNAMESE (vi) - Complete 185 keys ---
const vi = {
  ...existing.vi,
  nav_select_lang: "Chọn ngôn ngữ (Select Language)",
  nav_current_lang: "Ngôn ngữ hiện tại",
  badge_client_engine: "100% Công nghệ Client-side Trình duyệt",
  badge_security: "Bảo mật",
  home_why_sec1_title: "100% Bảo mật Cục bộ Phía Máy khách",
  home_why_sec1_desc: "mypickpdf xử lý tài liệu trực tiếp trong bộ nhớ trình duyệt qua WebAssembly. Dữ liệu mật của bạn không bao giờ tải lên bất kỳ máy chủ nào.",
  home_why_sec2_title: "Xử lý tức thì không độ trễ",
  home_why_sec2_desc: "Không cần chờ đợi tải lên mạng. Tận dụng sức mạnh xử lý của thiết bị để hoàn tất hàng chục trang chỉ trong 1-2 giây.",
  home_faq_title: "Câu hỏi thường gặp (FAQ)",
  home_faq_subtitle: "Hướng dẫn sử dụng và chính sách bảo mật của mypickpdf",
  home_faq_q1: "mypickpdf có thực sự miễn phí 100% và không cần đăng nhập?",
  home_faq_a1: "Đúng vậy! mypickpdf hoàn toàn miễn phí trọn đời, không yêu cầu đăng ký, đăng nhập hay bất kỳ khoản phí nào.",
  home_faq_q2: "Tài liệu sau khi chuyển đổi có lưu trên máy chủ không?",
  home_faq_a2: "Tuyệt đối không. Toàn bộ quá trình chuyển đổi diễn ra trong bộ nhớ thiết bị của bạn, 0 byte dữ liệu gửi ra ngoài.",
  home_faq_q3: "Tệp Office (Word, Excel, PPT) sau chuyển đổi có chỉnh sửa được không?",
  home_faq_a3: "Có! Các tệp Word, Excel và PowerPoint được trích xuất hoàn toàn tương thích và chỉnh sửa tự do trên Microsoft Office.",
  home_to_pdf_sub: "(Word, Excel, PPT, Hình ảnh ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, Hình ảnh, PDF/A, HWP)",
  share_title: "Muốn chia sẻ cho bạn bè và đồng nghiệp? 🐾",
  share_desc: "Sao chép liên kết trong 1 giây & đánh dấu trang để truy cập nhanh chóng!",
  share_btn: "Chia sẻ liên kết",
  share_copied: "Đã sao chép! 🐾",
  share_bookmark: "Đánh dấu trang",
  share_bookmark_tip: "Nhấn Ctrl + D (Mac: Cmd + D) để lưu trang này ngay lập tức!",
  uploaded_card_success: "Tệp đã được tải lên an toàn và thành công!",
  uploaded_card_local_badge: "100% Tải cục bộ",
  uploaded_card_change_file: "Đổi tệp khác",
  uploaded_card_and_more: "và {count} tệp khác",
  uploaded_card_total_pages: "Tổng {count} trang",
  uploaded_card_file_size: "Kích thước",
  uploaded_card_no_server: "Không tải lên máy chủ (Cách ly bộ nhớ)",
  processing_complete: "Hoàn tất",
  processing_bubble: "Đang xử lý tài liệu của bạn với tốc độ cực nhanh! 🐾",
  howto_badge: "Hướng dẫn nhanh",
  howto_heading_suffix: " — Cách sử dụng",
  howto_subtitle: "Hoàn thành công việc chỉ với 3 bước đơn giản mà không cần cài đặt phần mềm phức tạp.",
  faq_badge: "Hỏi & Đáp",
  faq_title: "Câu hỏi thường gặp (FAQ)",
  faq_subtitle: "Giải đáp các thắc mắc về tính năng và độ an toàn của mypickpdf."
};

fs.writeFileSync(path.join(outDir, 'th.ts'), `import { TranslationDictionary } from "./types";\n\nexport const th: TranslationDictionary = ${JSON.stringify(th, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'ms.ts'), `import { TranslationDictionary } from "./types";\n\nexport const ms: TranslationDictionary = ${JSON.stringify(ms, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'id.ts'), `import { TranslationDictionary } from "./types";\n\nexport const id: TranslationDictionary = ${JSON.stringify(id, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'vi.ts'), `import { TranslationDictionary } from "./types";\n\nexport const vi: TranslationDictionary = ${JSON.stringify(vi, null, 2)};\n`);

console.log('Generated th.ts, ms.ts, id.ts, vi.ts');
