const fs = require('fs');
const path = require('path');

const outDir = path.join(__dirname, '../src/lib/translations');
const existing = require('../existing_translations.json');

// --- SPANISH (es) ---
const es = {
  ...existing.es,
  nav_select_lang: "Seleccionar idioma (Select Language)",
  nav_current_lang: "Idioma actual",
  badge_client_engine: "Motor 100% en el navegador",
  badge_security: "Seguridad",
  home_why_sec1_title: "Seguridad 100% local en tu dispositivo",
  home_why_sec1_desc: "mypickpdf procesa los documentos directamente en la memoria de tu navegador con WebAssembly. Tus archivos confidenciales nunca tocan un servidor externo.",
  home_why_sec2_title: "Procesamiento instantáneo sin demoras",
  home_why_sec2_desc: "Sin esperas de subida a la red. Aprovecha la potencia de tu equipo para procesar decenas de páginas en 1-2 segundos.",
  home_faq_title: "Preguntas frecuentes (FAQ)",
  home_faq_subtitle: "Guía de uso y políticas de seguridad de mypickpdf",
  home_faq_q1: "¿mypickpdf es realmente 100% gratuito y sin registro?",
  home_faq_a1: "¡Sí! mypickpdf es totalmente gratuito para siempre. Sin registros, sin inicios de sesión y sin tarifas ocultas.",
  home_faq_q2: "¿Los documentos convertidos se almacenan en algún servidor?",
  home_faq_a2: "Nunca. Todo el procesamiento se realiza en la memoria de tu navegador y se transfieren 0 bytes a servidores externos.",
  home_faq_q3: "¿Los archivos de Office (Word, Excel, PPT) convertidos se pueden editar?",
  home_faq_a3: "¡Por supuesto! Los archivos Word (.docx), Excel (.xlsx) y PowerPoint (.pptx) extraídos se pueden abrir y editar con total libertad en Microsoft Office y otros programas.",
  home_to_pdf_sub: "(Word, Excel, PPT, Imágenes ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, Imágenes, PDF/A)",
  share_title: "¿Quieres recomendarlo a tus amigos y compañeros? 🐾",
  share_desc: "¡Copia el enlace en 1 segundo y guárdalo en marcadores para acceder más rápido!",
  share_btn: "Compartir enlace",
  share_copied: "¡Copiado! 🐾",
  share_bookmark: "Marcador",
  share_bookmark_tip: "¡Presiona Ctrl + D (Mac: Cmd + D) para añadir esta página a marcadores!",
  uploaded_card_success: "¡Archivos cargados con éxito y de forma segura!",
  uploaded_card_local_badge: "Carga 100% local",
  uploaded_card_change_file: "Cambiar archivo",
  uploaded_card_and_more: "+ {count} más",
  uploaded_card_total_pages: "Total {count} páginas",
  uploaded_card_file_size: "Tamaño",
  uploaded_card_no_server: "Cero subidas a servidores (Aislamiento en memoria)",
  processing_complete: "Completado",
  processing_bubble: "¡Procesando tus documentos a máxima velocidad! 🐾",
  howto_badge: "Tutorial rápido",
  howto_heading_suffix: " — ¿Cómo usarlo?",
  howto_subtitle: "Completa tu tarea en 3 sencillos pasos sin instalar software pesado.",
  faq_badge: "Preguntas y respuestas",
  faq_title: "Preguntas frecuentes (FAQ)",
  faq_subtitle: "Encuentra respuestas sobre el uso de las herramientas y la privacidad."
};

// --- FRENCH (fr) ---
const fr = {
  ...existing.fr,
  nav_select_lang: "Choisir la langue (Select Language)",
  nav_current_lang: "Langue actuelle",
  badge_client_engine: "Moteur 100% côté client",
  badge_security: "Sécurité",
  home_why_sec1_title: "Sécurité 100% locale sur votre appareil",
  home_why_sec1_desc: "mypickpdf traite vos fichiers directement dans la mémoire du navigateur grâce à WebAssembly. Aucun document ne transite par un serveur externe.",
  home_why_sec2_title: "Traitement instantané sans délai",
  home_why_sec2_desc: "Aucun temps d'attente lié au réseau. Utilise la puissance de calcul locale de votre appareil pour traiter des dizaines de pages en 1 à 2 secondes.",
  home_faq_title: "Foire Aux Questions (FAQ)",
  home_faq_subtitle: "Guide d'utilisation et politique de sécurité de mypickpdf",
  home_faq_q1: "mypickpdf est-il vraiment 100% gratuit sans inscription ?",
  home_faq_a1: "Oui ! mypickpdf est totalement gratuit et sans limitation. Aucune inscription, aucune connexion et aucun paiement requis.",
  home_faq_q2: "Les documents convertis sont-ils stockés sur un serveur ?",
  home_faq_a2: "Jamais. Vos documents sont traités exclusivement dans la mémoire vive de votre appareil : 0 octet n'est envoyé à l'extérieur.",
  home_faq_q3: "Les fichiers Office (Word, Excel, PPT) convertis sont-ils modifiables ?",
  home_faq_a3: "Oui ! Les fichiers Word (.docx), Excel (.xlsx) et PowerPoint (.pptx) générés sont entièrement modifiables sous Microsoft Office et autres logiciels.",
  home_to_pdf_sub: "(Word, Excel, PPT, Images ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, Images, PDF/A)",
  share_title: "Envie de le recommander à vos collègues et amis ? 🐾",
  share_desc: "Copiez le lien en 1 seconde et ajoutez-le à vos favoris !",
  share_btn: "Partager le lien",
  share_copied: "Copié ! 🐾",
  share_bookmark: "Favoris",
  share_bookmark_tip: "Appuyez sur Ctrl + D (Mac : Cmd + D) pour ajouter immédiatement cette page à vos favoris !",
  uploaded_card_success: "Fichiers chargés avec succès et en toute sécurité !",
  uploaded_card_local_badge: "Chargement 100% local",
  uploaded_card_change_file: "Changer de fichier",
  uploaded_card_and_more: "+ {count} autres",
  uploaded_card_total_pages: "Total {count} pages",
  uploaded_card_file_size: "Taille",
  uploaded_card_no_server: "Zéro envoi sur serveur (Mémoire isolée)",
  processing_complete: "Terminé",
  processing_bubble: "Préparation ultra-rapide de votre document en cours ! 🐾",
  howto_badge: "Tutoriel rapide",
  howto_heading_suffix: " — Mode d'emploi",
  howto_subtitle: "Réalisez vos tâches en 3 étapes simples sans aucun logiciel lourd.",
  faq_badge: "Q&R",
  faq_title: "Foire Aux Questions (FAQ)",
  faq_subtitle: "Découvrez toutes les réponses sur nos outils et la sécurité de vos données.",
  guides_portal_badge: "Guide officiel mypickpdf",
  guides_portal_title: "Maîtrisez les flux PDF & Bureautique (40+ Guides)",
  guides_portal_subtitle: "Fusion de CV, factures, numérotation de thèses et confidentialité : maîtrisez tous vos documents grâce à nos guides pratiques.",
  guides_search_placeholder: "Rechercher un guide ou mot-clé (ex: fusion, compression, mobile...)",
  guides_cat_all: "Tous",
  guides_cat_edit: "Édition PDF",
  guides_cat_convert: "Conversion Office",
  guides_cat_security: "Sécurité & Confidentialité",
  guides_cat_media: "Média & GIF",
  guides_cat_mobile: "Astuces Mobiles",
  guides_read_article: "Lire le guide",
  guides_direct_tool: "Ouvrir l'outil",
  guides_back_to_list: "Retour à la liste",
  guides_quick_cta_title: "Essayez par vous-même dès maintenant !",
  guides_share: "Partager ce guide",
  guides_copied: "Lien copié !"
};

// --- GERMAN (de) ---
const de = {
  ...existing.de,
  nav_select_lang: "Sprache wählen (Select Language)",
  nav_current_lang: "Aktuelle Sprache",
  badge_client_engine: "100% Client-seitige Browser-Engine",
  badge_security: "Sicherheit",
  home_why_sec1_title: "100% lokale Sicherheit auf Ihrem Gerät",
  home_why_sec1_desc: "mypickpdf verarbeitet Dokumente direkt im Arbeitsspeicher Ihres Browsers mit WebAssembly. Vertrauliche Dateien verlassen niemals Ihr Gerät.",
  home_why_sec2_title: "Sofortige Verarbeitung ohne Wartezeit",
  home_why_sec2_desc: "Keine zeitraubenden Uploads über das Internet. Nutzt die Rechenleistung Ihres Geräts, um Dutzende Seiten in 1-2 Sekunden zu verarbeiten.",
  home_faq_title: "Häufig gestellte Fragen (FAQ)",
  home_faq_subtitle: "Anleitung und Sicherheitsrichtlinien für mypickpdf",
  home_faq_q1: "Ist mypickpdf wirklich 100% kostenlos und ohne Anmeldung?",
  home_faq_a1: "Ja! mypickpdf ist dauerhaft kostenlos. Keine Registrierung, kein Login und keinerlei versteckte Kosten.",
  home_faq_q2: "Werden konvertierte Dokumente auf einem Server gespeichert?",
  home_faq_a2: "Niemals. Alle Dateien werden ausschließlich im lokalen Speicher Ihres Geräts verarbeitet; 0 Bytes werden nach außen übertragen.",
  home_faq_q3: "Sind konvertierte Office-Dateien (Word, Excel, PPT) bearbeitbar?",
  home_faq_a3: "Ja! Die extrahierten Word-, Excel- und PowerPoint-Dateien sind vollständig kompatibel und können in Microsoft Office bearbeitet werden.",
  home_to_pdf_sub: "(Word, Excel, PPT, Bilder ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, Bilder, PDF/A)",
  share_title: "Möchten Sie mypickpdf Freunden & Kollegen empfehlen? 🐾",
  share_desc: "Link in 1 Sekunde kopieren & als Lesezeichen speichern!",
  share_btn: "Link teilen",
  share_copied: "Kopiert! 🐾",
  share_bookmark: "Lesezeichen",
  share_bookmark_tip: "Drücken Sie Strg + D (Mac: Cmd + D), um diese Seite als Lesezeichen zu speichern!",
  uploaded_card_success: "Dateien sicher und erfolgreich geladen!",
  uploaded_card_local_badge: "100% lokal geladen",
  uploaded_card_change_file: "Datei ändern",
  uploaded_card_and_more: "+ {count} weitere",
  uploaded_card_total_pages: "Gesamt {count} Seiten",
  uploaded_card_file_size: "Größe",
  uploaded_card_no_server: "Kein Server-Upload (Isolierter Arbeitsspeicher)",
  processing_complete: "Fertig",
  processing_bubble: "Bearbeite Ihr Dokument in Höchstgeschwindigkeit! 🐾",
  howto_badge: "Kurzanleitung",
  howto_heading_suffix: " — Anleitung zur Nutzung",
  howto_subtitle: "Erledigen Sie Ihre Aufgabe in 3 einfachen Schritten ohne Software-Installation.",
  faq_badge: "F&A",
  faq_title: "Häufig gestellte Fragen (FAQ)",
  faq_subtitle: "Antworten zur Nutzung unserer Werkzeuge und zur Datensicherheit.",
  guides_portal_badge: "Offizielles mypickpdf Handbuch",
  guides_portal_title: "PDF & Dokumenten-Workflows meistern (40+ Leitfäden)",
  guides_portal_subtitle: "Von Lebensläufen und Rechnungen bis hin zu Seitenzahlen und lokaler Datensicherheit: lernen Sie alles in 40+ praktischen Artikeln.",
  guides_search_placeholder: "Leitfaden oder Stichwort suchen (z.B. Zusammenfügen, Komprimieren...)",
  guides_cat_all: "Alle",
  guides_cat_edit: "PDF bearbeiten",
  guides_cat_convert: "Office Konvertierung",
  guides_cat_security: "Sicherheit & Datenschutz",
  guides_cat_media: "Medien & GIF",
  guides_cat_mobile: "Mobile Tipps",
  guides_read_article: "Artikel lesen",
  guides_direct_tool: "Werkzeug öffnen",
  guides_back_to_list: "Zurück zur Übersicht",
  guides_quick_cta_title: "Jetzt gleich selbst ausprobieren!",
  guides_share: "Leitfaden teilen",
  guides_copied: "Link kopiert!"
};

// --- ITALIAN (it) ---
const it = {
  ...existing.it,
  nav_select_lang: "Seleziona lingua (Select Language)",
  nav_current_lang: "Lingua corrente",
  badge_client_engine: "Motore 100% Client-Side nel Browser",
  badge_security: "Sicurezza",
  home_why_sec1_title: "Sicurezza 100% locale sul tuo dispositivo",
  home_why_sec1_desc: "mypickpdf elabora i documenti direttamente nella memoria del tuo browser tramite WebAssembly. I file riservati non toccano mai server esterni.",
  home_why_sec2_title: "Elaborazione istantanea senza attese",
  home_why_sec2_desc: "Nessuna attesa di upload su rete. Sfrutta la potenza del tuo dispositivo per elaborare decine di pagine in 1-2 secondi.",
  home_faq_title: "Domande Frequenti (FAQ)",
  home_faq_subtitle: "Guida all'uso e policy di sicurezza di mypickpdf",
  home_faq_q1: "mypickpdf è davvero gratuito al 100% e senza registrazione?",
  home_faq_a1: "Sì! mypickpdf è completamente gratuito per sempre. Nessuna registrazione, nessun login e nessun costo nascosto.",
  home_faq_q2: "I documenti convertiti vengono salvati su qualche server?",
  home_faq_a2: "Assolutamente no. Tutti i documenti vengono elaborati unicamente nella memoria del tuo dispositivo con 0 byte inviati all'esterno.",
  home_faq_q3: "I file di Office (Word, Excel, PPT) convertiti sono modificabili?",
  home_faq_a3: "Sì! I file Word (.docx), Excel (.xlsx) e PowerPoint (.pptx) estratti possono essere aperti e modificati liberamente in Microsoft Office.",
  home_to_pdf_sub: "(Word, Excel, PPT, Immagini ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, Immagini, PDF/A)",
  share_title: "Vuoi consigliarlo ad amici e colleghi? 🐾",
  share_desc: "Copia il link in 1 secondo e aggiungi ai preferiti per un accesso rapidissimo!",
  share_btn: "Condividi link",
  share_copied: "Copiato! 🐾",
  share_bookmark: "Preferiti",
  share_bookmark_tip: "Premi Ctrl + D (Mac: Cmd + D) per salvare subito questa pagina tra i preferiti!",
  uploaded_card_success: "File caricati con successo e in totale sicurezza!",
  uploaded_card_local_badge: "Caricamento 100% locale",
  uploaded_card_change_file: "Cambia file",
  uploaded_card_and_more: "+ altri {count}",
  uploaded_card_total_pages: "Totale {count} pagine",
  uploaded_card_file_size: "Dimensione",
  uploaded_card_no_server: "Zero upload su server (Isolamento in memoria)",
  processing_complete: "Completato",
  processing_bubble: "Stiamo preparando il tuo documento a tutta velocità! 🐾",
  howto_badge: "Tutorial rapido",
  howto_heading_suffix: " — Come si usa",
  howto_subtitle: "Completa la tua operazione in 3 semplici passaggi senza installare software pesanti.",
  faq_badge: "D&R",
  faq_title: "Domande Frequenti (FAQ)",
  faq_subtitle: "Trova risposte sull'utilizzo degli strumenti e sulla riservatezza dei dati.",
  guides_portal_badge: "Manuale ufficiale mypickpdf",
  guides_portal_title: "Padroneggia i flussi di lavoro PDF & Ufficio (40+ Guide)",
  guides_portal_subtitle: "Da unione di CV e fatture fino a numeri di pagina e privacy locale: scopri tutto con oltre 40 guide pratiche.",
  guides_search_placeholder: "Cerca titolo o parola chiave (es: unisci, comprimi, mobile...)",
  guides_cat_all: "Tutti",
  guides_cat_edit: "Modifica PDF",
  guides_cat_convert: "Conversione Office",
  guides_cat_security: "Sicurezza & Privacy",
  guides_cat_media: "Media & GIF",
  guides_cat_mobile: "Suggerimenti Mobile",
  guides_read_article: "Leggi guida",
  guides_direct_tool: "Apri strumento",
  guides_back_to_list: "Torna alla lista",
  guides_quick_cta_title: "Provalo subito tu stesso!",
  guides_share: "Condividi guida",
  guides_copied: "Link copiato!"
};

// --- PORTUGUESE (pt) ---
const pt = {
  ...existing.pt,
  nav_select_lang: "Selecionar idioma (Select Language)",
  nav_current_lang: "Idioma atual",
  badge_client_engine: "Motor 100% no Navegador (Client-side)",
  badge_security: "Segurança",
  home_why_sec1_title: "Segurança 100% local no seu dispositivo",
  home_why_sec1_desc: "O mypickpdf processa arquivos diretamente na memória do seu navegador através do WebAssembly. Seus documentos sigilosos nunca vão para servidores externos.",
  home_why_sec2_title: "Processamento instantâneo sem esperas",
  home_why_sec2_desc: "Sem espera de upload pela rede. Utiliza o poder de processamento do seu próprio computador ou celular para processar dezenas de páginas em 1-2 segundos.",
  home_faq_title: "Perguntas Frequentes (FAQ)",
  home_faq_subtitle: "Diretrizes de uso e política de segurança do mypickpdf",
  home_faq_q1: "O mypickpdf é realmente 100% gratuito e sem necessidade de cadastro?",
  home_faq_a1: "Sim! O mypickpdf é totalmente gratuito para sempre. Sem cadastros, sem login e sem qualquer cobrança oculta.",
  home_faq_q2: "Os documentos convertidos são salvos em algum servidor?",
  home_faq_a2: "Nunca. O processamento ocorre exclusivamente na memória do seu dispositivo, com 0 bytes transmitidos para servidores externos.",
  home_faq_q3: "Os arquivos do Office (Word, Excel, PPT) convertidos podem ser editados?",
  home_faq_a3: "Sim! Os arquivos Word (.docx), Excel (.xlsx) e PowerPoint (.pptx) extraídos podem ser abertos e editados livremente no Microsoft Office e outros programas.",
  home_to_pdf_sub: "(Word, Excel, PPT, Imagens ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, Imagens, PDF/A)",
  share_title: "Deseja recomendar aos seus amigos e colegas? 🐾",
  share_desc: "Copie o link em 1 segundo e salve nos favoritos para acesso rápido!",
  share_btn: "Compartilhar link",
  share_copied: "Copiado! 🐾",
  share_bookmark: "Favoritos",
  share_bookmark_tip: "Pressione Ctrl + D (Mac: Cmd + D) para adicionar esta página aos favoritos!",
  uploaded_card_success: "Arquivos carregados com sucesso e segurança!",
  uploaded_card_local_badge: "Carregamento 100% local",
  uploaded_card_change_file: "Alterar arquivo",
  uploaded_card_and_more: "+ outros {count}",
  uploaded_card_total_pages: "Total de {count} páginas",
  uploaded_card_file_size: "Tamanho",
  uploaded_card_no_server: "Zero uploads no servidor (Isolamento em memória)",
  processing_complete: "Concluído",
  processing_bubble: "Finalizando seus documentos em velocidade máxima! 🐾",
  howto_badge: "Tutorial rápido",
  howto_heading_suffix: " — Como usar",
  howto_subtitle: "Conclua sua tarefa em 3 passos fáceis sem instalar softwares pesados.",
  faq_badge: "Perguntas & Respostas",
  faq_title: "Perguntas Frequentes (FAQ)",
  faq_subtitle: "Tire suas dúvidas sobre o uso das ferramentas e a segurança dos dados.",
  guides_portal_badge: "Guia Oficial mypickpdf",
  guides_portal_title: "Domine Fluxos de PDF & Documentos (40+ Guias Práticos)",
  guides_portal_subtitle: "Desde união de currículos e notas fiscais até numeração de teses e privacidade: aprenda tudo com mais de 40 tutoriais práticos.",
  guides_search_placeholder: "Buscar guia ou palavra-chave (ex: juntar, comprimir, celular...)",
  guides_cat_all: "Todos",
  guides_cat_edit: "Edição de PDF",
  guides_cat_convert: "Conversão Office",
  guides_cat_security: "Segurança & Privacidade",
  guides_cat_media: "Mídia & GIF",
  guides_cat_mobile: "Dicas para Celular",
  guides_read_article: "Ler artigo",
  guides_direct_tool: "Abrir ferramenta",
  guides_back_to_list: "Voltar para lista",
  guides_quick_cta_title: "Experimente agora mesmo!",
  guides_share: "Compartilhar guia",
  guides_copied: "Link copiado!"
};

// --- DUTCH (nl) ---
const nl = {
  brand_name: "mypickpdf (Rode Panda PDF)",
  nav_brand_tag: "100% Gratis & Veilige PDF Tools met de Rode Panda",
  nav_all_tools: "Alle PDF Tools",
  nav_convert_pdf: "PDF Converteren",
  nav_to_pdf: "Naar PDF converteren",
  nav_from_pdf: "Van PDF converteren",
  nav_privacy_badge: "0% Serveropslag",
  nav_free_badge: "Onbeperkt Gratis, Geen Login",
  nav_guides: "Handleidingen",
  nav_core_tools: "PDF Bewerkingstools",
  nav_media_tools: "Video- & Mediatools",
  nav_select_lang: "Selecteer taal (Select Language)",
  nav_current_lang: "Huidige taal",
  badge_free_utility: "100% Gratis Hulpprogramma",
  badge_no_server: "Geen serververzending (Veilige lokale verwerking)",
  badge_no_login: "Geen registratie of login vereist",
  badge_unlimited_free: "Supersnel & Onbeperkt Gratis",
  badge_client_engine: "100% Client-Side Browser Engine",
  badge_security: "Veiligheid",
  tool_merge: "PDF Samenvoegen",
  tool_merge_desc: "Voeg meerdere PDF-bestanden samen tot één document",
  tool_split: "PDF Splitsen",
  tool_split_desc: "Extraheer specifieke pagina's of splits elke pagina apart",
  tool_compress: "PDF Comprimeren",
  tool_compress_desc: "Verklein PDF-bestandsgrootte met behoud van maximale kwaliteit",
  tool_rotate: "PDF Draaien",
  tool_rotate_desc: "Draai uw PDF-document 90 of 180 graden",
  tool_ocr: "PDF OCR (Tekstherkenning)",
  tool_ocr_desc: "Haal bewerkbare tekst uit gescande PDF's en afbeeldingen",
  tool_page_numbers: "Paginanummers toevoegen",
  tool_page_numbers_desc: "Voeg paginanummers in op gewenste posities",
  tool_watermark: "Watermerk toevoegen",
  tool_watermark_desc: "Voeg een tekst- of beeldwatermerk toe aan uw documenten",
  tool_compress_video: "Video Comprimeren",
  tool_compress_video_desc: "Verklein MP4/MOV-video's tot 80% zonder kwaliteitsverlies",
  tool_video_to_gif: "Video naar GIF",
  tool_video_to_gif_desc: "Zet videoclips om in geanimeerde GIF-bestanden van hoge kwaliteit",
  tool_img_to_pdf: "Afbeelding naar PDF",
  tool_img_to_pdf_desc: "Converteer JPG en PNG naar hoogwaardige PDF-bestanden",
  tool_word_to_pdf: "Word naar PDF",
  tool_word_to_pdf_desc: "Converteer Word-documenten (.docx) direct naar PDF",
  tool_ppt_to_pdf: "PowerPoint naar PDF",
  tool_ppt_to_pdf_desc: "Converteer PowerPoint-presentaties (.pptx) naar PDF",
  tool_excel_to_pdf: "Excel naar PDF",
  tool_excel_to_pdf_desc: "Zet Excel-werkbladen (.xlsx) om in PDF",
  tool_html_to_pdf: "HTML naar PDF",
  tool_html_to_pdf_desc: "Render webpagina HTML-code direct als PDF",
  tool_pdf_to_img: "PDF naar Afbeelding",
  tool_pdf_to_img_desc: "Sla elke pagina van uw PDF op als scherpe JPG-afbeelding",
  tool_pdf_to_word: "PDF naar Word",
  tool_pdf_to_word_desc: "Zet PDF om naar een bewerkbaar Word-document (.docx)",
  tool_pdf_to_ppt: "PDF naar PowerPoint",
  tool_pdf_to_ppt_desc: "Converteer PDF naar bewerkbare PowerPoint-dia's (.pptx)",
  tool_pdf_to_excel: "PDF naar Excel",
  tool_pdf_to_excel_desc: "Extraheer PDF-tabellen naar een Excel-spreadsheet (.xlsx)",
  tool_pdf_to_pdfa: "PDF naar PDF/A",
  tool_pdf_to_pdfa_desc: "Converteer naar ISO-standaard PDF/A voor langdurige archivering",
  tool_pdf_to_hwp: "PDF naar HWP/HWPX",
  tool_pdf_to_hwp_desc: "Converteer PDF naar standaard Koreaanse documenten (.hwpx / .hwp)",
  btn_select_files: "Bestanden Selecteren",
  drop_title_default: "Sleep bestanden hierheen",
  drop_subtitle_default: "of klik op de knop hieronder om bestanden te kiezen",
  drop_note_privacy: "🔒 100% lokale browserverwerking (geen serveropslag)",
  drop_note_limit: "Onbeperkte bestandsgrootte ondersteund",
  drop_badge_secure: "100% Veilig Lokaal Laden",
  drop_mascot_bubble: "Laat maar hier vallen! 🐾",
  drop_drag_title: "Laat los om direct te laden!",
  drop_drag_desc: "Laat bestanden op de knop of in het vak vallen voor directe verwerking",
  drop_action_drop: "Plaats bestanden hier (Drop)",
  btn_download_again: "Bestand downloaden",
  btn_reset: "Alles opnieuw instellen",
  btn_add_files: "Bestanden toevoegen",
  processing_title: "De Rode Panda verwerkt uw document veilig...",
  processing_desc: "Even geduld. Zodra het klaar is, start de download automatisch.",
  processing_badge: "100% lokale verwerking in browsermemory",
  processing_complete: "Voltooid",
  processing_bubble: "Uw document wordt met topsnelheid verwerkt! 🐾",
  uploaded_card_success: "Bestanden veilig en succesvol geladen!",
  uploaded_card_local_badge: "100% Lokaal Geladen",
  uploaded_card_change_file: "Ander bestand kiezen",
  uploaded_card_and_more: "+ nog {count}",
  uploaded_card_total_pages: "Totaal {count} pagina's",
  uploaded_card_file_size: "Grootte",
  uploaded_card_no_server: "Nul uploads naar server (Geheugenisolatie)",
  home_mascot_bubble: "Hoi! Ik ben de Rode Panda 🐾 Laat elk document maar aan mij over!",
  home_hero_tag: "100% Gratis in-browser PDF-oplossing met de Rode Panda",
  home_hero_title1: "De Schattigste, Snelste & Veiligste",
  home_hero_title2: "mypickpdf Online Suite",
  home_hero_desc: "Converteer, comprimeer en bewerk Word, Excel, PowerPoint en afbeeldingen van en naar PDF met onze Rode Panda. 100% veilige browserverwerking die 0 bytes achterlaat op servers.",
  home_tools_title: "Aanbevolen Populaire PDF Tools",
  home_tools_subtitle: "Kies uw gewenste tool en begin direct",
  home_use_now: "Nu gebruiken",
  home_convert_btn: "Converteren",
  home_extract_btn: "Extraheren",
  sponsor_snack_btn: "Trakteer de Rode Panda op een snack ☕",
  home_why_title: "Waarom kiezen miljoenen gebruikers voor mypickpdf?",
  home_table_title: "Vergelijking: Betaalde sites vs mypickpdf",
  home_why_sec1_title: "100% Lokale Beveiliging aan Client-zijde",
  home_why_sec1_desc: "mypickpdf verwerkt documenten rechtstreeks in uw browsergeheugen via WebAssembly. Vertrouwelijke documenten worden nooit naar externe servers verzonden.",
  home_why_sec2_title: "Directe Verwerking Zonder Vertraging",
  home_why_sec2_desc: "Geen wachttijd voor netwerkuploads. Gebruikt de rekenkracht van uw eigen apparaat om tientallen pagina's binnen 1-2 seconden te verwerken.",
  home_faq_title: "Veelgestelde Vragen (FAQ)",
  home_faq_subtitle: "Gebruikershandleiding en beveiligingsbeleid van mypickpdf",
  home_faq_q1: "Is mypickpdf echt 100% gratis zonder registratie?",
  home_faq_a1: "Ja! mypickpdf is voor altijd volledig gratis. Geen registratie, geen login en geen verborgen kosten.",
  home_faq_q2: "Worden geconverteerde documenten op een server bewaard?",
  home_faq_a2: "Absoluut nooit. Alle documenten worden uitsluitend in het geheugen van uw apparaat verwerkt en er worden 0 bytes geüpload.",
  home_faq_q3: "Zijn geconverteerde Office-bestanden (Word, Excel, PPT) bewerkbaar?",
  home_faq_a3: "Ja! Geëxtraheerde Word-, Excel- en PowerPoint-bestanden kunnen probleemloos worden geopend en bewerkt in Microsoft Office en andere software.",
  home_to_pdf_sub: "(Word, Excel, PPT, Afbeeldingen ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, Afbeeldingen, PDF/A)",
  share_title: "Wil je mypickpdf aanbevelen aan vrienden of collega's? 🐾",
  share_desc: "Kopieer de link in 1 seconde & voeg toe aan bladwijzers!",
  share_btn: "Link delen",
  share_copied: "Gekopieerd! 🐾",
  share_bookmark: "Bladwijzer",
  share_bookmark_tip: "Druk op Ctrl + D (Mac: Cmd + D) om deze pagina direct op te slaan!",
  video_title: "Video Comprimeren (MP4 / MOV)",
  video_header_sub: "Verklein MP4 / MOV bestandsgrootte",
  video_desc: "Verklein video's tot 80% voor e-mail of chat zonder kwaliteitsverlies. 100% lokale browserverwerking.",
  video_tag: "Nieuwe Functie",
  video_drop_title: "Kies videobestand om te comprimeren",
  video_drop_subtitle: "Ondersteunt MP4, MOV, WebM, MKV (geen serverupload)",
  video_badge_local: "100% Lokale Apparaatverwerking (Geen Serveropslag)",
  video_badge_hardware: "Hardware-versnelde High-Speed Codering",
  video_badge_mobile: "Volledige Smartphone Ondersteuning (iPhone/Android)",
  video_step_level: "Kies Compressieniveau",
  video_step_level_desc: "Selecteer de gewenste balans tussen kwaliteit en bestandsgrootte",
  video_opt_extreme_title: "Maximale Compressie (voor chat & mail)",
  video_opt_extreme_sub: "Tot 70~85% kleiner bestand",
  video_opt_extreme_desc: "Zeer geschikt voor het delen via chatapps en e-mailbijlagen.",
  video_opt_extreme_badge: "Kleinste Formaat",
  video_opt_rec_title: "Aanbevolen Balans (Standaard)",
  video_opt_rec_sub: "Circa 40~60% kleiner bestand",
  video_opt_rec_desc: "De meest aanbevolen optie met heldere videokwaliteit en aanzienlijke gewichtsbesparing.",
  video_opt_rec_badge: "Meest Aanbevolen",
  video_opt_less_title: "Hoge Kwaliteit Behouden (Lichte Compressie)",
  video_opt_less_sub: "Circa 20~30% kleiner bestand",
  video_opt_less_desc: "Behoudt maximale scherpte en details.",
  video_opt_less_badge: "Kwaliteit Eerst",
  video_selected: "Geselecteerd",
  video_btn_compress: "Video nu comprimeren",
  video_compressing: "Video comprimeren...",
  video_btn_reset: "Nieuwe video comprimeren",
  video_result_title: "Video Compressie Voltooid!",
  video_result_desc: "De bestandsgrootte is aanzienlijk verkleind met browserversnelling.",
  video_original: "Oorspronkelijke grootte",
  video_compressed: "Grootte na compressie",
  video_saved: "Bespaarde ruimte",
  howto_badge: "Snelle Handleiding",
  howto_heading_suffix: " — Hoe te gebruiken?",
  howto_subtitle: "Voltooi uw taak in 3 eenvoudige stappen zonder zware software te installeren.",
  faq_badge: "Vraag & Antwoord",
  faq_title: "Veelgestelde Vragen (FAQ)",
  faq_subtitle: "Vind antwoorden over het gebruik van onze tools en gegevensbescherming.",
  guides_portal_badge: "Officieel mypickpdf Handboek",
  guides_portal_title: "Beheers PDF- en Documentwerkstromen (40+ Gidsen)",
  guides_portal_subtitle: "Van het samenvoegen van cv's en facturen tot paginanummers en lokale privacy: leer alles in 40+ praktische gidsen.",
  guides_search_placeholder: "Zoek handleiding of trefwoord (bijv. samenvoegen, comprimeren, mobiel...)",
  guides_cat_all: "Alle",
  guides_cat_edit: "PDF Bewerken",
  guides_cat_convert: "Office Conversie",
  guides_cat_security: "Veiligheid & Privacy",
  guides_cat_media: "Media & GIF",
  guides_cat_mobile: "Mobiele Tips",
  guides_read_article: "Lees gids",
  guides_direct_tool: "Open tool",
  guides_back_to_list: "Terug naar overzicht",
  guides_quick_cta_title: "Probeer het nu zelf uit!",
  guides_share: "Deel deze handleiding",
  guides_copied: "Link gekopieerd!",
  ad_label: "Advertentie / ADVERTISEMENT",
  ad_placeholder_title: "Gesponsorde Advertentieruimte",
  ad_placeholder_desc: "Advertentieruimte om deze dienst gratis te houden.",
  footer_security_title: "Garantie voor Absolute Privacy & Documentveiligheid",
  footer_security_desc: "mypickpdf uploadt of bewaart uw bestanden nooit op externe servers. Alle bewerkingen worden 100% in uw browser uitgevoerd.",
  footer_privacy_leak: "0% Datalekken naar buiten",
  footer_about: "Een moderne webutility samen met de schattige Rode Panda waarmee iedereen zonder inloggen en gratis PDF's kan bewerken en converteren.",
  footer_col_tools: "Populaire Tools",
  footer_col_tech: "Technologie & Veiligheid",
  footer_col_legal: "Ondersteuning & Voorwaarden",
  footer_privacy_link: "Privacybeleid",
  footer_terms_link: "Algemene Voorwaarden",
  footer_contact_link: "Contact & Feedback",
  footer_rights: "All rights reserved. Alle rechten voorbehouden."
};

// --- CATALAN (ca) ---
const ca = {
  brand_name: "mypickpdf (Panda Vermell PDF)",
  nav_brand_tag: "Eines PDF 100% Gratuïtes i Segures amb el Panda Vermell",
  nav_all_tools: "Totes les eines PDF",
  nav_convert_pdf: "Convertir PDF",
  nav_to_pdf: "Convertir a PDF",
  nav_from_pdf: "Convertir des de PDF",
  nav_privacy_badge: "0% Emmagatzematge al Servidor",
  nav_free_badge: "Gratuït Il·limitat, Sense Registre",
  nav_guides: "Guies",
  nav_core_tools: "Eines d'Edició PDF",
  nav_media_tools: "Eines de Vídeo i Multimèdia",
  nav_select_lang: "Seleccionar idioma (Select Language)",
  nav_current_lang: "Idioma actual",
  badge_free_utility: "Utilitat 100% Gratuïta",
  badge_no_server: "Sense transmissió al servidor (Seguretat local)",
  badge_no_login: "Sense registre ni inici de sessió",
  badge_unlimited_free: "Superràpid i Il·limitat",
  badge_client_engine: "Motor 100% al navegador de l'usuari",
  badge_security: "Seguretat",
  tool_merge: "Unir PDF",
  tool_merge_desc: "Combina diversos fitxers PDF en un sol document",
  tool_split: "Dividir PDF",
  tool_split_desc: "Extreu pàgines seleccionades o separa cada pàgina",
  tool_compress: "Comprimir PDF",
  tool_compress_desc: "Redueix la mida del PDF mantenint la màxima qualitat",
  tool_rotate: "Girar PDF",
  tool_rotate_desc: "Gira el document PDF 90 o 180 graus",
  tool_ocr: "OCR PDF (Reconeixement de text)",
  tool_ocr_desc: "Extreu text editable de documents i imatges escanejades",
  tool_page_numbers: "Afegir números de pàgina",
  tool_page_numbers_desc: "Insereix la numeració de pàgines a la posició desitjada",
  tool_watermark: "Afegir marca d'aigua",
  tool_watermark_desc: "Afegeix una marca d'aigua de text o imatge als teus documents",
  tool_compress_video: "Comprimir vídeo",
  tool_compress_video_desc: "Redueix la mida de vídeos MP4 i MOV fins a un 80% sense perdre qualitat",
  tool_video_to_gif: "Vídeo a GIF",
  tool_video_to_gif_desc: "Converteix clips de vídeo en animacions GIF d'alta qualitat",
  tool_img_to_pdf: "Imatge a PDF",
  tool_img_to_pdf_desc: "Converteix imatges JPG i PNG a documents PDF",
  tool_word_to_pdf: "Word a PDF",
  tool_word_to_pdf_desc: "Converteix documents Word (.docx) a PDF a l'instant",
  tool_ppt_to_pdf: "PowerPoint a PDF",
  tool_ppt_to_pdf_desc: "Converteix presentacions PowerPoint (.pptx) a PDF",
  tool_excel_to_pdf: "Excel a PDF",
  tool_excel_to_pdf_desc: "Transforma fulls de càlcul Excel (.xlsx) a PDF",
  tool_html_to_pdf: "HTML a PDF",
  tool_html_to_pdf_desc: "Renderitza codi web HTML directament a PDF",
  tool_pdf_to_img: "PDF a Imatge",
  tool_pdf_to_img_desc: "Desa cada pàgina del PDF com a imatge JPG d'alta resolució",
  tool_pdf_to_word: "PDF a Word",
  tool_pdf_to_word_desc: "Converteix PDF a un document Word editable (.docx)",
  tool_pdf_to_ppt: "PDF a PowerPoint",
  tool_pdf_to_ppt_desc: "Converteix PDF a diapositives PowerPoint editables (.pptx)",
  tool_pdf_to_excel: "PDF a Excel",
  tool_pdf_to_excel_desc: "Extreu taules PDF a fulls de càlcul Excel (.xlsx)",
  tool_pdf_to_pdfa: "PDF a PDF/A",
  tool_pdf_to_pdfa_desc: "Converteix al format estàndard ISO PDF/A per a l'arxiu a llarg termini",
  tool_pdf_to_hwp: "PDF a HWP/HWPX",
  tool_pdf_to_hwp_desc: "Converteix PDF a format estàndard coreà (.hwpx / .hwp)",
  btn_select_files: "Seleccionar fitxers",
  drop_title_default: "Arrossega els fitxers aquí",
  drop_subtitle_default: "o fes clic al botó inferior per triar fitxers",
  drop_note_privacy: "🔒 Processament 100% local al navegador (sense desar al servidor)",
  drop_note_limit: "Mida de fitxer il·limitada",
  drop_badge_secure: "Càrrega local 100% segura",
  drop_mascot_bubble: "Deixa'ls anar aquí! 🐾",
  drop_drag_title: "Deixa anar per carregar a l'instant!",
  drop_drag_desc: "Sigui al botó o a la caixa, es processarà de manera ràpida i segura",
  drop_action_drop: "Deixa anar aquí (Drop)",
  btn_download_again: "Descarregar fitxer",
  btn_reset: "Reiniciar-ho tot",
  btn_add_files: "Afegir fitxers",
  processing_title: "El Panda Vermell està processant el teu document amb seguretat...",
  processing_desc: "Si us plau, espera. La descàrrega s'iniciarà automàticament en acabar.",
  processing_badge: "Processament 100% a la memòria del navegador",
  processing_complete: "Completat",
  processing_bubble: "Processant el teu document a màxima velocitat! 🐾",
  uploaded_card_success: "Fitxers carregats correctament i de manera segura!",
  uploaded_card_local_badge: "Càrrega 100% local",
  uploaded_card_change_file: "Canviar de fitxer",
  uploaded_card_and_more: "+ {count} més",
  uploaded_card_total_pages: "Total {count} pàgines",
  uploaded_card_file_size: "Mida",
  uploaded_card_no_server: "Zero càrregues al servidor (Aïllament a la memòria)",
  home_mascot_bubble: "Hola! Sóc el Panda Vermell 🐾 Deixa'm qualsevol document a les meves mans!",
  home_hero_tag: "Solució PDF al navegador 100% Gratuïta amb el Panda Vermell",
  home_hero_title1: "El més adorable, ràpid i segur",
  home_hero_title2: "mypickpdf Online Suite",
  home_hero_desc: "Converteix, comprimeix i edita Word, Excel, PowerPoint i imatges des de i cap a PDF amb el nostre Panda Vermell. Processament 100% privat que deixa 0 bytes als servidors.",
  home_tools_title: "Eines Populars Recomanades",
  home_tools_subtitle: "Tria l'eina que necessites i comença immediatament",
  home_use_now: "Utilitzar ara",
  home_convert_btn: "Convertir",
  home_extract_btn: "Extreure",
  sponsor_snack_btn: "Convida el Panda a un berenar ☕",
  home_why_title: "Per què milions d'usuaris trien mypickpdf?",
  home_table_title: "Comparativa: Llocs de pagament vs mypickpdf",
  home_why_sec1_title: "Seguretat 100% local al navegador",
  home_why_sec1_desc: "mypickpdf processa els fitxers a la memòria del teu navegador mitjançant WebAssembly. Cap fitxer confidencial no s'envia a cap servidor extern.",
  home_why_sec2_title: "Processament immediat sense cues",
  home_why_sec2_desc: "Sense esperes de pujada a internet. Utilitza la potència del teu propi dispositiu per processar desenes de pàgines en 1-2 segons.",
  home_faq_title: "Preguntes Més Freqüents (FAQ)",
  home_faq_subtitle: "Guia d'ús i polítiques de seguretat de mypickpdf",
  home_faq_q1: "mypickpdf és realment 100% gratuït i sense registre?",
  home_faq_a1: "Sí! mypickpdf és completament gratuït per sempre, sense registres, sense comptes i sense costos ocults.",
  home_faq_q2: "Es guarden els documents convertits a algun servidor?",
  home_faq_a2: "Mai de la vida. Tot es processa a la memòria del teu dispositiu i s'envien exactament 0 bytes fora.",
  home_faq_q3: "Els fitxers d'Office (Word, Excel, PPT) convertits es poden editar?",
  home_faq_a3: "I tant! Els fitxers Word, Excel i PowerPoint extrets es poden obrir i editar lliurement a Microsoft Office i altres aplicacions.",
  home_to_pdf_sub: "(Word, Excel, PPT, Imatges ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, Imatges, PDF/A)",
  share_title: "Vols recomanar-ho a amics i companys? 🐾",
  share_desc: "Copia l'enllaç en 1 segon i desa'l a les teves adreces d'interès!",
  share_btn: "Compartir enllaç",
  share_copied: "Copiat! 🐾",
  share_bookmark: "Adreça d'interès",
  share_bookmark_tip: "Prem Ctrl + D (Mac: Cmd + D) per desar aquesta pàgina als teus marcadors!",
  video_title: "Comprimir vídeo (MP4 / MOV)",
  video_header_sub: "Redueix la mida de fitxers MP4 / MOV",
  video_desc: "Redueix la mida de vídeos fins a un 80% per compartir per xat o correu sense perdre qualitat. 100% local al navegador.",
  video_tag: "Nova Funció",
  video_drop_title: "Tria el fitxer de vídeo a comprimir",
  video_drop_subtitle: "Compatible amb MP4, MOV, WebM, MKV (sense pujar a cap servidor)",
  video_badge_local: "Processament 100% al dispositiu (Sense emmagatzematge al servidor)",
  video_badge_hardware: "Codificació d'alta velocitat accelerada per maquinari",
  video_badge_mobile: "Compatibilitat total amb mòbils (iPhone/Android)",
  video_step_level: "Tria el nivell de compressió",
  video_step_level_desc: "Tria l'equilibri que necessites entre qualitat i mida de fitxer",
  video_opt_extreme_title: "Compressió màxima (per a xat i correu)",
  video_opt_extreme_sub: "Fins a un 70~85% d'estalvi de mida",
  video_opt_extreme_desc: "Ideal per enviar per aplicacions de missatgeria o adjuntar al correu.",
  video_opt_extreme_badge: "Mida mínima",
  video_opt_rec_title: "Compressió equilibrada (Recomanada)",
  video_opt_rec_sub: "Al voltant del 40~60% d'estalvi de mida",
  video_opt_rec_desc: "L'opció més recomanada, amb una imatge nítida i una reducció de pes excel·lent.",
  video_opt_rec_badge: "Més recomanat",
  video_opt_less_title: "Mantenir alta qualitat (Compressió lleugera)",
  video_opt_less_sub: "Al voltant del 20~30% d'estalvi de mida",
  video_opt_less_desc: "Preserva al màxim la resolució i el detall originals.",
  video_opt_less_badge: "Prioritat qualitat",
  video_selected: "Seleccionat",
  video_btn_compress: "Comprimir vídeo ara",
  video_compressing: "Comprimint el vídeo...",
  video_btn_reset: "Comprimir un nou vídeo",
  video_result_title: "Compressió de vídeo completada!",
  video_result_desc: "La mida del fitxer s'ha reduït notablement gràcies a l'acceleració al navegador.",
  video_original: "Mida original",
  video_compressed: "Mida després de comprimir",
  video_saved: "Espai estalviat",
  howto_badge: "Tutorial ràpid",
  howto_heading_suffix: " — Com s'utilitza?",
  howto_subtitle: "Completa la feina en 3 senzills passos sense haver d'instal·lar programes pesants.",
  faq_badge: "Preguntes i respostes",
  faq_title: "Preguntes Més Freqüents (FAQ)",
  faq_subtitle: "Troba respostes sobre l'ús de les eines i la privadesa de les teves dades.",
  guides_portal_badge: "Guia Oficial mypickpdf",
  guides_portal_title: "Domina el treball amb documents i PDF (40+ Guies)",
  guides_portal_subtitle: "Des de la unió de currículums i factures fins a la numeració de tesis i privadesa: aprèn-ho tot amb més de 40 guies pràctiques.",
  guides_search_placeholder: "Cerca una guia o paraula clau (ex: unir, comprimir, mòbil...)",
  guides_cat_all: "Totes",
  guides_cat_edit: "Edició de PDF",
  guides_cat_convert: "Conversió d'Office",
  guides_cat_security: "Seguretat i Privadesa",
  guides_cat_media: "Mèdia i GIF",
  guides_cat_mobile: "Consells per a mòbils",
  guides_read_article: "Llegir guia",
  guides_direct_tool: "Obrir eina",
  guides_back_to_list: "Tornar a la llista de guies",
  guides_quick_cta_title: "Prova-ho tu mateix ara!",
  guides_share: "Compartir aquesta guia",
  guides_copied: "Enllaç copiat!",
  ad_label: "Publicitat / ADVERTISEMENT",
  ad_placeholder_title: "Espai publicitari patrocinat",
  ad_placeholder_desc: "Espai d'anuncis per mantenir el servei 100% gratuït.",
  footer_security_title: "Garantia de Privadesa i Seguretat Absoluta dels Documents",
  footer_security_desc: "mypickpdf no puja ni emmagatzema mai els teus fitxers en servidors remots. Totes les operacions es realitzen 100% al teu navegador.",
  footer_privacy_leak: "0% Fugues de dades externes",
  footer_about: "Una utilitat web moderna amb l'adorable Panda Vermell perquè qualsevol pugui editar i convertir PDF fàcilment, de franc i sense registrar-se.",
  footer_col_tools: "Eines Populars",
  footer_col_tech: "Tecnologia i Seguretat",
  footer_col_legal: "Ajuda i Condicions",
  footer_privacy_link: "Política de Privadesa",
  footer_terms_link: "Condicions del Servei",
  footer_contact_link: "Contacte i Suggeriments",
  footer_rights: "All rights reserved. Tots els drets reservats."
};

fs.writeFileSync(path.join(outDir, 'es.ts'), `import { TranslationDictionary } from "./types";\n\nexport const es: TranslationDictionary = ${JSON.stringify(es, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'fr.ts'), `import { TranslationDictionary } from "./types";\n\nexport const fr: TranslationDictionary = ${JSON.stringify(fr, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'de.ts'), `import { TranslationDictionary } from "./types";\n\nexport const de: TranslationDictionary = ${JSON.stringify(de, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'it.ts'), `import { TranslationDictionary } from "./types";\n\nexport const it: TranslationDictionary = ${JSON.stringify(it, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'pt.ts'), `import { TranslationDictionary } from "./types";\n\nexport const pt: TranslationDictionary = ${JSON.stringify(pt, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'nl.ts'), `import { TranslationDictionary } from "./types";\n\nexport const nl: TranslationDictionary = ${JSON.stringify(nl, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'ca.ts'), `import { TranslationDictionary } from "./types";\n\nexport const ca: TranslationDictionary = ${JSON.stringify(ca, null, 2)};\n`);

console.log('Generated es.ts, fr.ts, de.ts, it.ts, pt.ts, nl.ts, ca.ts');
