const fs = require('fs');
const path = require('path');

const outDir = path.join(__dirname, '../src/lib/translations');
const existing = require('../existing_translations.json');

// --- RUSSIAN (ru) ---
const ru = {
  ...existing.ru,
  nav_select_lang: "Выбор языка (Select Language)",
  nav_current_lang: "Текущий язык",
  badge_client_engine: "100% клиентский движок в браузере",
  badge_security: "Безопасность",
  home_why_sec1_title: "100% локальная безопасность на устройстве",
  home_why_sec1_desc: "mypickpdf обрабатывает документы прямо в оперативной памяти браузера с помощью WebAssembly. Ваши файлы никогда не отправляются на внешние серверы.",
  home_why_sec2_title: "Мгновенная обработка без задержек",
  home_why_sec2_desc: "Никакого ожидания загрузки по сети. Использует вычислительную мощность вашего устройства для обработки десятков страниц за 1–2 секунды.",
  home_faq_title: "Часто задаваемые вопросы (FAQ)",
  home_faq_subtitle: "Руководство по использованию и политика конфиденциальности mypickpdf",
  home_faq_q1: "mypickpdf действительно бесплатен и не требует регистрации?",
  home_faq_a1: "Да! mypickpdf полностью и навсегда бесплатен. Никаких регистраций, авторизаций и скрытых платежей.",
  home_faq_q2: "Сохраняются ли преобразованные документы на сервере?",
  home_faq_a2: "Никогда. Все файлы обрабатываются строго в памяти вашего браузера, во внешнюю сеть передается ровно 0 байт.",
  home_faq_q3: "Можно ли редактировать преобразованные файлы Office (Word, Excel, PPT)?",
  home_faq_a3: "Да! Извлеченные документы Word (.docx), Excel (.xlsx) и PowerPoint (.pptx) полностью поддерживаются и свободно редактируются в Microsoft Office.",
  home_to_pdf_sub: "(Word, Excel, PPT, Изображения ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, Изображения, PDF/A)",
  share_title: "Хотите порекомендовать друзьям и коллегам? 🐾",
  share_desc: "Скопируйте ссылку за 1 секунду и добавьте в закладки для быстрого доступа!",
  share_btn: "Поделиться ссылкой",
  share_copied: "Скопировано! 🐾",
  share_bookmark: "В закладки",
  share_bookmark_tip: "Нажмите Ctrl + D (Mac: Cmd + D), чтобы сразу добавить страницу в закладки!",
  uploaded_card_success: "Файлы безопасно и успешно загружены!",
  uploaded_card_local_badge: "100% локальная загрузка",
  uploaded_card_change_file: "Изменить файл",
  uploaded_card_and_more: "+ еще {count}",
  uploaded_card_total_pages: "Всего {count} стр.",
  uploaded_card_file_size: "Размер",
  uploaded_card_no_server: "Без отправки на сервер (Изолированная память)",
  processing_complete: "Готово",
  processing_bubble: "Обрабатываем документ на сверхскорости! 🐾",
  howto_badge: "Быстрое руководство",
  howto_heading_suffix: " — Как использовать",
  howto_subtitle: "Выполните задачу всего за 3 простых шага без установки тяжелых программ.",
  faq_badge: "Вопросы и ответы",
  faq_title: "Часто задаваемые вопросы (FAQ)",
  faq_subtitle: "Узнайте всё о работе наших инструментов и защите данных.",
  guides_portal_badge: "Официальное руководство mypickpdf",
  guides_portal_title: "Мастерство работы с PDF и документами (40+ статей)",
  guides_portal_subtitle: "От объединения резюме и счетов до нумерации диссертаций и локальной безопасности: изучите всё в 40+ практических руководствах.",
  guides_search_placeholder: "Поиск статьи или ключевого слова (напр: объединить, сжать, телефон...)",
  guides_cat_all: "Все",
  guides_cat_edit: "Редактирование PDF",
  guides_cat_convert: "Конвертация Office",
  guides_cat_security: "Безопасность и приватность",
  guides_cat_media: "Медиа и GIF",
  guides_cat_mobile: "Мобильные советы",
  guides_read_article: "Читать статью",
  guides_direct_tool: "Открыть инструмент",
  guides_back_to_list: "Назад к списку",
  guides_quick_cta_title: "Попробуйте прямо сейчас!",
  guides_share: "Поделиться статьей",
  guides_copied: "Ссылка скопирована!"
};

// --- UKRAINIAN (uk) ---
const uk = {
  brand_name: "mypickpdf (Червона Панда PDF)",
  nav_brand_tag: "100% Безкоштовні та Безпечні Інструменти PDF з Червоною Пандою",
  nav_all_tools: "Всі інструменти PDF",
  nav_convert_pdf: "Конвертувати PDF",
  nav_to_pdf: "Конвертувати в PDF",
  nav_from_pdf: "Конвертувати з PDF",
  nav_privacy_badge: "0% Збереження на Сервері",
  nav_free_badge: "Безлімітно Безкоштовно, Без Реєстрації",
  nav_guides: "Посібники",
  nav_core_tools: "Інструменти Редагування PDF",
  nav_media_tools: "Інструменти Відео та Медіа",
  nav_select_lang: "Вибір мови (Select Language)",
  nav_current_lang: "Поточна мова",
  badge_free_utility: "100% Безкоштовна Утиліта",
  badge_no_server: "Без передачі на сервер (Локальна безпека)",
  badge_no_login: "Без реєстрації та входу",
  badge_unlimited_free: "Швидко і Безлімітно Безкоштовно",
  badge_client_engine: "100% Клієнтський движок у браузері",
  badge_security: "Безпека",
  tool_merge: "Об'єднати PDF",
  tool_merge_desc: "З'єднайте кілька файлів PDF в один документ",
  tool_split: "Розділити PDF",
  tool_split_desc: "Витягуйте окремі сторінки або розділяйте кожну сторінку",
  tool_compress: "Стиснути PDF",
  tool_compress_desc: "Зменшуйте розмір файлу PDF із збереженням максимальної якості",
  tool_rotate: "Повернути PDF",
  tool_rotate_desc: "Повертайте документ PDF на 90 або 180 градусів",
  tool_ocr: "OCR PDF (Розпізнавання тексту)",
  tool_ocr_desc: "Витягуйте текст зі скан-копій PDF та зображень",
  tool_page_numbers: "Додати номери сторінок",
  tool_page_numbers_desc: "Вставляйте нумерацію сторінок у вибрані позиції",
  tool_watermark: "Додати водяний знак",
  tool_watermark_desc: "Додавайте текстовий або графічний водяний знак",
  tool_compress_video: "Стиснути відео",
  tool_compress_video_desc: "Зменшуйте розмір MP4 та MOV до 80% без видимої втрати якості",
  tool_video_to_gif: "Відео в GIF",
  tool_video_to_gif_desc: "Перетворюйте відеокліпи на якісні анімовані GIF",
  tool_img_to_pdf: "Зображення в PDF",
  tool_img_to_pdf_desc: "Конвертуйте JPG та PNG у якісні документи PDF",
  tool_word_to_pdf: "Word в PDF",
  tool_word_to_pdf_desc: "Швидко конвертуйте документи Word (.docx) у PDF",
  tool_ppt_to_pdf: "PowerPoint в PDF",
  tool_ppt_to_pdf_desc: "Перетворюйте презентації PowerPoint (.pptx) на PDF",
  tool_excel_to_pdf: "Excel в PDF",
  tool_excel_to_pdf_desc: "Перетворюйте таблиці Excel (.xlsx) на охайні PDF",
  tool_html_to_pdf: "HTML в PDF",
  tool_html_to_pdf_desc: "Рендеринг веб-сторінок HTML безпосередньо у формат PDF",
  tool_pdf_to_img: "PDF у зображення",
  tool_pdf_to_img_desc: "Зберігайте кожну сторінку PDF як якісне зображення JPG",
  tool_pdf_to_word: "PDF у Word",
  tool_pdf_to_word_desc: "Перетворюйте PDF на редагований документ Word (.docx)",
  tool_pdf_to_ppt: "PDF у PowerPoint",
  tool_pdf_to_ppt_desc: "Конвертуйте PDF у слайди презентації PowerPoint (.pptx)",
  tool_pdf_to_excel: "PDF в Excel",
  tool_pdf_to_excel_desc: "Витягуйте таблиці з PDF у таблицю Excel (.xlsx)",
  tool_pdf_to_pdfa: "PDF у PDF/A",
  tool_pdf_to_pdfa_desc: "Конвертуйте в стандартний формат ISO PDF/A для тривалого зберігання",
  tool_pdf_to_hwp: "PDF у HWP/HWPX",
  tool_pdf_to_hwp_desc: "Конвертуйте PDF у стандартні корейські документи (.hwpx / .hwp)",
  btn_select_files: "Вибрати файли",
  drop_title_default: "Перетягніть файли сюди",
  drop_subtitle_default: "або натисніть кнопку нижче, щоб вибрати файли",
  drop_note_privacy: "🔒 100% обробка в локальному браузері (без збереження на сервері)",
  drop_note_limit: "Підтримка необмеженого розміру файлів",
  drop_badge_secure: "100% безпечне локальне завантаження",
  drop_mascot_bubble: "Кидайте прямо сюди! 🐾",
  drop_drag_title: "Відпустіть кнопку миші для миттєвого завантаження!",
  drop_drag_desc: "У поле чи на кнопку — файл відкриється надійно та швидко",
  drop_action_drop: "Кинути сюди (Drop)",
  btn_download_again: "Завантажити файл",
  btn_reset: "Скинути все",
  btn_add_files: "Додати файли",
  processing_title: "Червона Панда безпечно конвертує ваш документ...",
  processing_desc: "Будь ласка, зачекайте. Завантаження розпочнеться автоматично.",
  processing_badge: "100% локальна обробка в пам'яті браузера",
  processing_complete: "Завершено",
  processing_bubble: "Готуємо документ на шаленій швидкості! 🐾",
  uploaded_card_success: "Файли безпечно та успішно завантажено!",
  uploaded_card_local_badge: "100% локальне завантаження",
  uploaded_card_change_file: "Змінити файл",
  uploaded_card_and_more: "+ ще {count}",
  uploaded_card_total_pages: "Всього {count} стор.",
  uploaded_card_file_size: "Розмір",
  uploaded_card_no_server: "Без надсилання на сервер (Ізольована пам'ять)",
  home_mascot_bubble: "Привіт! Я Червона Панда 🐾 Довірте мені будь-який документ!",
  home_hero_tag: "100% Безкоштовне рішення для PDF у браузері разом з Червоною Пандою",
  home_hero_title1: "Наймиліший, найшвидший та найбезпечніший",
  home_hero_title2: "Онлайн-набір mypickpdf",
  home_hero_desc: "Конвертуйте, стискайте та редагуйте Word, Excel, PowerPoint та зображення з/в PDF разом з нашою пандою. 100% приватна обробка в браузері, що залишає 0 байтів на серверах.",
  home_tools_title: "Популярні інструменти, які ми рекомендуємо",
  home_tools_subtitle: "Виберіть потрібну дію та почніть роботу негайно",
  home_use_now: "Використати зараз",
  home_convert_btn: "Конвертувати",
  home_extract_btn: "Витягти",
  sponsor_snack_btn: "Пригостити панду смаколиком ☕",
  home_why_title: "Чому мільйони користувачів обирають mypickpdf?",
  home_table_title: "Порівняння: Платні сервіси проти mypickpdf",
  home_why_sec1_title: "100% Локальна Безпека на Вашому Пристрої",
  home_why_sec1_desc: "mypickpdf обробляє файли безпосередньо в оперативній пам'яті браузера через WebAssembly. Конфіденційні документи ніколи не потраплять на чужі сервери.",
  home_why_sec2_title: "Миттєва Обробка Без Очікування",
  home_why_sec2_desc: "Жодного очікування передачі через мережу. Використовує потужність вашого пристрою для обробки десятків сторінок за 1-2 секунди.",
  home_faq_title: "Часті запитання (FAQ)",
  home_faq_subtitle: "Посібник користувача та політика безпеки mypickpdf",
  home_faq_q1: "mypickpdf дійсно на 100% безкоштовний і не вимагає входу?",
  home_faq_a1: "Так! mypickpdf завжди повністю безкоштовний. Жодних реєстрацій, авторизацій чи прихованих платежів.",
  home_faq_q2: "Чи зберігаються конвертовані документи на сервері?",
  home_faq_a2: "Ніколи. Всі файли обробляються виключно в пам'яті вашого браузера і передається рівно 0 байтів.",
  home_faq_q3: "Чи можна редагувати конвертовані файли Office (Word, Excel, PPT)?",
  home_faq_a3: "Звісно! Отримані файли Word, Excel та PowerPoint повністю сумісні з Microsoft Office та іншими редакторами.",
  home_to_pdf_sub: "(Word, Excel, PPT, Зображення ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, Зображення, PDF/A)",
  share_title: "Бажаєте порекомендувати друзям і колегам? 🐾",
  share_desc: "Скопіюйте посилання за 1 секунду та додайте у закладки для швидкого доступу!",
  share_btn: "Поділитися посиланням",
  share_copied: "Скопійовано! 🐾",
  share_bookmark: "Закладка",
  share_bookmark_tip: "Натисніть Ctrl + D (Mac: Cmd + D), щоб миттєво зберегти цю сторінку!",
  video_title: "Стиснути відео (MP4 / MOV)",
  video_header_sub: "Зменшити розмір MP4 / MOV",
  video_desc: "Зменшуйте розмір відео до 80% для чатів чи пошти без втрати якості. 100% локально в браузері.",
  video_tag: "Нова Функція",
  video_drop_title: "Виберіть відеофайл для стиснення",
  video_drop_subtitle: "Підтримуються всі відео MP4, MOV, WebM, MKV (без завантаження на сервер)",
  video_badge_local: "100% Локальна Обробка (Без збереження на сервері)",
  video_badge_hardware: "Швидкісне апаратне кодування",
  video_badge_mobile: "Повна підтримка смартфонів (iPhone/Android)",
  video_step_level: "Виберіть рівень стиснення",
  video_step_level_desc: "Оберіть баланс між чіткістю зображення та розміром файлу",
  video_opt_extreme_title: "Максимальне стиснення (для чатів та пошти)",
  video_opt_extreme_sub: "Економія розміру до 70~85%",
  video_opt_extreme_desc: "Ідеально підходить для надсилання в месенджерах та поштових додатках.",
  video_opt_extreme_badge: "Мінімальний розмір",
  video_opt_rec_title: "Збалансоване стиснення (Рекомендовано)",
  video_opt_rec_sub: "Економія розміру близько 40~60%",
  video_opt_rec_desc: "Оптимальне співвідношення високої якості картинки та суттєвого зменшення ваги.",
  video_opt_rec_badge: "Найкращий вибір",
  video_opt_less_title: "Зберегти високу якість (Легке стиснення)",
  video_opt_less_sub: "Економія розміру близько 20~30%",
  video_opt_less_desc: "Максимально зберігає роздільну здатність і деталі оригіналу.",
  video_opt_less_badge: "Пріоритет якості",
  video_selected: "Вибрано",
  video_btn_compress: "Стиснути відео зараз",
  video_compressing: "Стиснення відео...",
  video_btn_reset: "Стиснути нове відео",
  video_result_title: "Стиснення відео завершено!",
  video_result_desc: "Розмір файлу суттєво зменшено завдяки апаратному прискоренню.",
  video_original: "Початковий розмір",
  video_compressed: "Розмір після стиснення",
  video_saved: "Збережено місця",
  howto_badge: "Швидкий посібник",
  howto_heading_suffix: " — Як цим користуватися?",
  howto_subtitle: "Виконайте завдання за 3 прості кроки без встановлення програм.",
  faq_badge: "Питання та відповіді",
  faq_title: "Часті запитання (FAQ)",
  faq_subtitle: "Відповіді на запитання щодо роботи сервісу та безпеки ваших файлів.",
  guides_portal_badge: "Офіційний посібник mypickpdf",
  guides_portal_title: "Опануйте роботу з PDF та документами (40+ статей)",
  guides_portal_subtitle: "Від об'єднання резюме та рахунків до нумерації дисертацій та безпеки: навчіться всьому у 40+ практичних інструкціях.",
  guides_search_placeholder: "Пошук статті чи слова (напр: об'єднати, стиснути, мобільний...)",
  guides_cat_all: "Всі",
  guides_cat_edit: "Редагування PDF",
  guides_cat_convert: "Конвертація Office",
  guides_cat_security: "Безпека та приватність",
  guides_cat_media: "Медіа та GIF",
  guides_cat_mobile: "Поради для смартфонів",
  guides_read_article: "Читати статтю",
  guides_direct_tool: "Відкрити інструмент",
  guides_back_to_list: "Назад до списку",
  guides_quick_cta_title: "Спробуйте самі просто зараз!",
  guides_share: "Поділитися посібником",
  guides_copied: "Посилання скопійовано!",
  ad_label: "Реклама / ADVERTISEMENT",
  ad_placeholder_title: "Спонсорський рекламний блок",
  ad_placeholder_desc: "Місце для розміщення реклами, яка допомагає підтримувати сервіс безкоштовним.",
  footer_security_title: "Гарантія повної приватності та безпеки документів",
  footer_security_desc: "mypickpdf ніколи не надсилає і не зберігає ваші файли на віддалених серверах. Всі операції виконуються на 100% у вашому браузері.",
  footer_privacy_leak: "0% Витоку даних назовні",
  footer_about: "Сучасний веб-сервіс із милою Червоною Пандою, який дозволяє будь-кому безкоштовно та без реєстрації швидко редагувати та конвертувати PDF.",
  footer_col_tools: "Популярні інструменти",
  footer_col_tech: "Технології та безпека",
  footer_col_legal: "Підтримка та умови",
  footer_privacy_link: "Політика конфіденційності",
  footer_terms_link: "Умови надання послуг",
  footer_contact_link: "Зв'язок та пропозиції",
  footer_rights: "All rights reserved. Всі права захищено."
};

// --- POLISH (pl) ---
const pl = {
  brand_name: "mypickpdf (Czerwona Panda PDF)",
  nav_brand_tag: "100% Darmowe i Bezpieczne Narzędzia PDF z Czerwoną Pandą",
  nav_all_tools: "Wszystkie narzędzia PDF",
  nav_convert_pdf: "Konwertuj PDF",
  nav_to_pdf: "Konwertuj do PDF",
  nav_from_pdf: "Konwertuj z PDF",
  nav_privacy_badge: "0% Zapisywania na Serwerze",
  nav_free_badge: "Nielimitowane i Darmowe, Bez Logowania",
  nav_guides: "Przewodniki",
  nav_core_tools: "Narzędzia Edycji PDF",
  nav_media_tools: "Narzędzia Wideo i Mediów",
  nav_select_lang: "Wybierz język (Select Language)",
  nav_current_lang: "Bieżący język",
  badge_free_utility: "100% Darmowe Narzędzie",
  badge_no_server: "Brak przesyłania na serwer (Bezpieczne przetwarzanie lokalne)",
  badge_no_login: "Bez rejestracji i logowania",
  badge_unlimited_free: "Superszybkie i Zawsze Darmowe",
  badge_client_engine: "100% Silnik w przeglądarce klienta",
  badge_security: "Bezpieczeństwo",
  tool_merge: "Scal PDF",
  tool_merge_desc: "Połącz kilka plików PDF w jeden kompletny dokument",
  tool_split: "Podziel PDF",
  tool_split_desc: "Wyodrębnij wybrane strony lub podziel każdą stronę osobno",
  tool_compress: "Kompresuj PDF",
  tool_compress_desc: "Zmniejsz rozmiar pliku PDF, zachowując maksymalną jakość",
  tool_rotate: "Obróć PDF",
  tool_rotate_desc: "Obróć dokument PDF o 90 lub 180 stopni",
  tool_ocr: "OCR PDF (Rozpoznawanie tekstu)",
  tool_ocr_desc: "Wyodrębnij edytowalny tekst ze skanów dokumentów i obrazów",
  tool_page_numbers: "Dodaj numery stron",
  tool_page_numbers_desc: "Wstawiaj numery stron w wybranych miejscach i formatach",
  tool_watermark: "Dodaj znak wodny",
  tool_watermark_desc: "Dodaj znak wodny z tekstem lub obrazem do dokumentu",
  tool_compress_video: "Kompresuj wideo",
  tool_compress_video_desc: "Zmniejsz rozmiar plików MP4 i MOV nawet o 80% bez widocznej straty jakości",
  tool_video_to_gif: "Wideo do GIF",
  tool_video_to_gif_desc: "Konwertuj klipy wideo na wysokiej jakości animowane pliki GIF",
  tool_img_to_pdf: "Obraz do PDF",
  tool_img_to_pdf_desc: "Konwertuj obrazy JPG i PNG na dokumenty PDF",
  tool_word_to_pdf: "Word do PDF",
  tool_word_to_pdf_desc: "Błyskawicznie konwertuj dokumenty Word (.docx) do PDF",
  tool_ppt_to_pdf: "PowerPoint do PDF",
  tool_ppt_to_pdf_desc: "Konwertuj prezentacje PowerPoint (.pptx) na PDF",
  tool_excel_to_pdf: "Excel do PDF",
  tool_excel_to_pdf_desc: "Zamień arkusze kalkulacyjne Excel (.xlsx) na PDF",
  tool_html_to_pdf: "HTML do PDF",
  tool_html_to_pdf_desc: "Renderuj kod stron internetowych HTML bezpośrednio do PDF",
  tool_pdf_to_img: "PDF do obrazu",
  tool_pdf_to_img_desc: "Zapisz każdą stronę PDF jako obraz JPG w wysokiej rozdzielczości",
  tool_pdf_to_word: "PDF do Word",
  tool_pdf_to_word_desc: "Konwertuj PDF na edytowalny dokument Word (.docx)",
  tool_pdf_to_ppt: "PDF do PowerPoint",
  tool_pdf_to_ppt_desc: "Konwertuj PDF na slajdy prezentacji PowerPoint (.pptx)",
  tool_pdf_to_excel: "PDF do Excel",
  tool_pdf_to_excel_desc: "Wyodrębnij tabele z PDF do arkusza Excel (.xlsx)",
  tool_pdf_to_pdfa: "PDF do PDF/A",
  tool_pdf_to_pdfa_desc: "Konwertuj do formatu ISO PDF/A na potrzeby długoterminowej archiwizacji",
  tool_pdf_to_hwp: "PDF do HWP/HWPX",
  tool_pdf_to_hwp_desc: "Konwertuj PDF do koreańskiego formatu dokumentów urzędowych",
  btn_select_files: "Wybierz pliki",
  drop_title_default: "Przeciągnij i upuść pliki tutaj",
  drop_subtitle_default: "lub kliknij przycisk poniżej, aby wybrać pliki z dysku",
  drop_note_privacy: "🔒 100% lokalnego przetwarzania w przeglądarce (brak zapisu na serwerze)",
  drop_note_limit: "Obsługa plików o nielimitowanym rozmiarze",
  drop_badge_secure: "100% Bezpieczne Ładowanie Lokalne",
  drop_mascot_bubble: "Upuść plik tutaj! 🐾",
  drop_drag_title: "Puść przycisk myszy, aby natychmiast załadować plik!",
  drop_drag_desc: "W pole lub na przycisk — plik zostanie bezpiecznie otwarty",
  drop_action_drop: "Upuść tutaj (Drop)",
  btn_download_again: "Pobierz plik",
  btn_reset: "Resetuj wszystko",
  btn_add_files: "Dodaj pliki",
  processing_title: "Czerwona Panda bezpiecznie przetwarza Twój dokument...",
  processing_desc: "Proszę czekać. Pobieranie rozpocznie się automatycznie po zakończeniu.",
  processing_badge: "100% lokalne przetwarzanie w pamięci przeglądarki",
  processing_complete: "Zakończono",
  processing_bubble: "Przygotowujemy Twój dokument z zawrotną prędkością! 🐾",
  uploaded_card_success: "Pliki zostały bezpiecznie i pomyślnie załadowane!",
  uploaded_card_local_badge: "100% Załadowano Lokalnie",
  uploaded_card_change_file: "Zmień plik",
  uploaded_card_and_more: "+ jeszcze {count}",
  uploaded_card_total_pages: "Łącznie {count} stron",
  uploaded_card_file_size: "Rozmiar",
  uploaded_card_no_server: "Zero wysyłania na serwer (Izolacja pamięci)",
  home_mascot_bubble: "Cześć! Jestem Czerwoną Pandą 🐾 Zostaw mi każdy dokument!",
  home_hero_tag: "100% Darmowy pakiet narzędzi PDF w przeglądarce z Czerwoną Pandą",
  home_hero_title1: "Najbardziej uroczy, najszybszy i najbezpieczniejszy",
  home_hero_title2: "Pakiet online mypickpdf",
  home_hero_desc: "Konwertuj, kompresuj i edytuj pliki Word, Excel, PowerPoint i obrazy do/z PDF z naszą pandą. 100% prywatne przetwarzanie w przeglądarce, które zostawia 0 bajtów na serwerach.",
  home_tools_title: "Polecane Popularne Narzędzia",
  home_tools_subtitle: "Wybierz potrzebne narzędzie i zacznij natychmiast",
  home_use_now: "Użyj teraz",
  home_convert_btn: "Konwertuj",
  home_extract_btn: "Wyodrębnij",
  sponsor_snack_btn: "Kup przekąskę Czerwonej Pandzie ☕",
  home_why_title: "Dlaczego miliony użytkowników wybierają mypickpdf?",
  home_table_title: "Porównanie: Płatne serwisy vs mypickpdf",
  home_why_sec1_title: "100% Lokalne Bezpieczeństwo po Stronie Klienta",
  home_why_sec1_desc: "mypickpdf przetwarza pliki bezpośrednio w pamięci podręcznej przeglądarki dzięki WebAssembly. Poufne dokumenty nigdy nie trafiają na zewnętrzne serwery.",
  home_why_sec2_title: "Błyskawiczne Przetwarzanie Bez Czekania",
  home_why_sec2_desc: "Bez oczekiwania na transfer internetowy. Wykorzystuje moc Twojego urządzenia, przetwarzając dziesiątki stron w 1-2 sekundy.",
  home_faq_title: "Często Zadawane Pytania (FAQ)",
  home_faq_subtitle: "Zasady korzystania i polityka bezpieczeństwa mypickpdf",
  home_faq_q1: "Czy mypickpdf jest naprawdę w 100% darmowy i bez rejestracji?",
  home_faq_a1: "Tak! mypickpdf jest całkowicie darmowy na zawsze. Bez rejestracji, bez logowania i bez ukrytych opłat.",
  home_faq_q2: "Czy przekonwertowane dokumenty są zapisywane na serwerze?",
  home_faq_a2: "Nigdy. Wszystkie operacje odbywają się wyłącznie w pamięci Twojego urządzenia i przesyłane jest 0 bajtów na zewnątrz.",
  home_faq_q3: "Czy przekonwertowane pliki Office (Word, Excel, PPT) można edytować?",
  home_faq_a3: "Oczywiście! Wyodrębnione pliki Word, Excel i PowerPoint można bez problemu otwierać i modyfikować w Microsoft Office.",
  home_to_pdf_sub: "(Word, Excel, PPT, Obrazy ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, Obrazy, PDF/A)",
  share_title: "Chcesz polecić nas znajomym i współpracownikom? 🐾",
  share_desc: "Skopiuj link w 1 sekundę i dodaj do zakładek, aby mieć szybki dostęp!",
  share_btn: "Udostępnij link",
  share_copied: "Skopiowano! 🐾",
  share_bookmark: "Zakładka",
  share_bookmark_tip: "Naciśnij Ctrl + D (Mac: Cmd + D), aby natychmiast dodać stronę do zakładek!",
  video_title: "Kompresuj wideo (MP4 / MOV)",
  video_header_sub: "Zmniejsz rozmiar MP4 / MOV",
  video_desc: "Zmniejsz rozmiar wideo nawet o 80% do wysyłki na czacie lub e-mailem bez widocznej straty jakości. 100% lokalnie.",
  video_tag: "Nowość",
  video_drop_title: "Wybierz plik wideo do skompresowania",
  video_drop_subtitle: "Obsługuje wszystkie formaty MP4, MOV, WebM, MKV (bez wysyłania na serwer)",
  video_badge_local: "100% Przetwarzanie Lokalne (Brak zapisu na serwerze)",
  video_badge_hardware: "Szybkie kodowanie z akceleracją sprzętową",
  video_badge_mobile: "Pełne wsparcie dla smartfonów (iPhone/Android)",
  video_step_level: "Wybierz poziom kompresji",
  video_step_level_desc: "Wybierz odpowiedni balans między jakością obrazu a rozmiarem pliku",
  video_opt_extreme_title: "Maksymalna kompresja (na czat i e-mail)",
  video_opt_extreme_sub: "Oszczędność rozmiaru do 70~85%",
  video_opt_extreme_desc: "Idealne do szybkiego przesyłania w komunikatorach internetowych i załącznikach.",
  video_opt_extreme_badge: "Najmniejszy plik",
  video_opt_rec_title: "Optymalna kompresja (Polecane)",
  video_opt_rec_sub: "Oszczędność rozmiaru około 40~60%",
  video_opt_rec_desc: "Najlepszy balans między wyrazistym obrazem a znaczną redukcją wagi pliku.",
  video_opt_rec_badge: "Najczęściej wybierane",
  video_opt_less_title: "Wysoka jakość (Lekka kompresja)",
  video_opt_less_sub: "Oszczędność rozmiaru około 20~30%",
  video_opt_less_desc: "Maksymalnie zachowuje oryginalne detale i rozdzielczość.",
  video_opt_less_badge: "Priorytet jakości",
  video_selected: "Wybrano",
  video_btn_compress: "Kompresuj wideo teraz",
  video_compressing: "Trwa kompresowanie...",
  video_btn_reset: "Kompresuj kolejne wideo",
  video_result_title: "Kompresja wideo zakończona!",
  video_result_desc: "Rozmiar pliku został znacznie zredukowany dzięki akceleracji w przeglądarce.",
  video_original: "Rozmiar początkowy",
  video_compressed: "Rozmiar po kompresji",
  video_saved: "Zaoszczędzono",
  howto_badge: "Szybki samouczek",
  howto_heading_suffix: " — Jak tego używać?",
  howto_subtitle: "Wykonaj zadanie w 3 prostych krokach bez instalowania uciążliwego oprogramowania.",
  faq_badge: "Pytania i odpowiedzi",
  faq_title: "Często Zadawane Pytania (FAQ)",
  faq_subtitle: "Poznaj odpowiedzi na pytania o korzystanie z narzędzi i ochronę danych.",
  guides_portal_badge: "Oficjalny poradnik mypickpdf",
  guides_portal_title: "Opanuj pracę z dokumentami i PDF (40+ Poradników)",
  guides_portal_subtitle: "Od łączenia CV i faktur po numerację prac dyplomowych i prywatność: dowiedz się wszystkiego z naszych poradników.",
  guides_search_placeholder: "Szukaj artykułu lub słowa kluczowego (np. połącz, kompresuj, telefon...)",
  guides_cat_all: "Wszystkie",
  guides_cat_edit: "Edycja PDF",
  guides_cat_convert: "Konwersja Office",
  guides_cat_security: "Bezpieczeństwo i Prywatność",
  guides_cat_media: "Media i GIF",
  guides_cat_mobile: "Wskazówki Mobilne",
  guides_read_article: "Czytaj artykuł",
  guides_direct_tool: "Otwórz narzędzie",
  guides_back_to_list: "Wróć do listy",
  guides_quick_cta_title: "Wypróbuj sam już teraz!",
  guides_share: "Udostępnij poradnik",
  guides_copied: "Link został skopiowany!",
  ad_label: "Reklama / ADVERTISEMENT",
  ad_placeholder_title: "Strefa reklam sponsorowanych",
  ad_placeholder_desc: "Miejsce na reklamy, dzięki którym usługa pozostaje bezpłatna.",
  footer_security_title: "Gwarancja Pełnej Prywatności i Bezpieczeństwa Dokumentów",
  footer_security_desc: "mypickpdf nigdy nie przesyła ani nie zapisuje Twoich plików na zdalnych serwerach. Wszystkie operacje odbywają się w 100% w Twojej przeglądarce.",
  footer_privacy_leak: "0% Wycieku danych na zewnątrz",
  footer_about: "Nowoczesne narzędzie internetowe z uroczą Czerwoną Pandą, które pozwala każdemu bezpłatnie i bez logowania edytować oraz konwertować pliki PDF.",
  footer_col_tools: "Popularne Narzędzia",
  footer_col_tech: "Technologia i Bezpieczeństwo",
  footer_col_legal: "Pomoc i Regulaminy",
  footer_privacy_link: "Polityka Prywatności",
  footer_terms_link: "Regulamin Świadczenia Usług",
  footer_contact_link: "Kontakt i Opinie",
  footer_rights: "All rights reserved. Wszelkie prawa zastrzeżone."
};

// --- TURKISH (tr) ---
const tr = {
  brand_name: "mypickpdf (Kızıl Panda PDF)",
  nav_brand_tag: "Kızıl Panda ile %100 Ücretsiz ve Güvenli PDF Araçları",
  nav_all_tools: "Tüm PDF Araçları",
  nav_convert_pdf: "PDF Dönüştür",
  nav_to_pdf: "PDF'e Dönüştür",
  nav_from_pdf: "PDF'den Dönüştür",
  nav_privacy_badge: "%0 Sunucu Depolaması",
  nav_free_badge: "Sınırsız Ücretsiz, Giriş Yok",
  nav_guides: "Rehberler",
  nav_core_tools: "PDF Düzenleme Araçları",
  nav_media_tools: "Video ve Medya Araçları",
  nav_select_lang: "Dil Seç (Select Language)",
  nav_current_lang: "Mevcut Dil",
  badge_free_utility: "%100 Ücretsiz Hizmet",
  badge_no_server: "Sunucuya aktarım yok (Yerel güvenli işlem)",
  badge_no_login: "Kayıt veya Giriş Gerekmez",
  badge_unlimited_free: "Süper Hızlı ve Sınırsız Ücretsiz",
  badge_client_engine: "%100 Tarayıcı İstemci Motoru",
  badge_security: "Güvenlik",
  tool_merge: "PDF Birleştir",
  tool_merge_desc: "Birden çok PDF dosyasını tek bir belgede birleştirin",
  tool_split: "PDF Böl",
  tool_split_desc: "Belirli sayfaları ayıklayın veya sayfaları tek tek bölün",
  tool_compress: "PDF Sıkıştır",
  tool_compress_desc: "En yüksek kaliteyi korurken PDF dosya boyutunu küçültün",
  tool_rotate: "PDF Döndür",
  tool_rotate_desc: "PDF belgenizi 90 veya 180 derece döndürün",
  tool_ocr: "PDF OCR (Metin Tanıma)",
  tool_ocr_desc: "Taranmış PDF ve görsellerden düzenlenebilir metin çıkarın",
  tool_page_numbers: "Sayfa Numarası Ekle",
  tool_page_numbers_desc: "İstediğiniz konuma sayfa numaraları ekleyin",
  tool_watermark: "Filigran Ekle",
  tool_watermark_desc: "Belgelerinize metin veya görsel filigranı ekleyin",
  tool_compress_video: "Video Sıkıştır",
  tool_compress_video_desc: "Kalite kaybı olmadan MP4 ve MOV boyutunu %80'e kadar küçültün",
  tool_video_to_gif: "Videodan GIF'e",
  tool_video_to_gif_desc: "Video kliplerini yüksek kaliteli hareketli GIF'lere dönüştürün",
  tool_img_to_pdf: "Görselden PDF'e",
  tool_img_to_pdf_desc: "JPG ve PNG görsellerini PDF belgesine dönüştürün",
  tool_word_to_pdf: "Word'den PDF'e",
  tool_word_to_pdf_desc: "Word (.docx) belgelerini anında PDF'e dönüştürün",
  tool_ppt_to_pdf: "PowerPoint'ten PDF'e",
  tool_ppt_to_pdf_desc: "PowerPoint sunumlarını (.pptx) PDF'e dönüştürün",
  tool_excel_to_pdf: "Excel'den PDF'e",
  tool_excel_to_pdf_desc: "Excel tablolarını (.xlsx) PDF'e aktarın",
  tool_html_to_pdf: "HTML'den PDF'e",
  tool_html_to_pdf_desc: "Web sayfası HTML kodunu doğrudan PDF olarak kaydedin",
  tool_pdf_to_img: "PDF'den Görsele",
  tool_pdf_to_img_desc: "PDF sayfalarını yüksek çözünürlüklü JPG olarak kaydedin",
  tool_pdf_to_word: "PDF'den Word'e",
  tool_pdf_to_word_desc: "PDF'i düzenlenebilir Word (.docx) belgesine dönüştürün",
  tool_pdf_to_ppt: "PDF'den PowerPoint'e",
  tool_pdf_to_ppt_desc: "PDF'i düzenlenebilir PowerPoint slaytlarına dönüştürün",
  tool_pdf_to_excel: "PDF'den Excel'e",
  tool_pdf_to_excel_desc: "PDF tablolarını Excel (.xlsx) çalışma sayfasına aktarın",
  tool_pdf_to_pdfa: "PDF'den PDF/A'ya",
  tool_pdf_to_pdfa_desc: "Uzun vadeli arşivleme için ISO standardı PDF/A formatına dönüştürün",
  tool_pdf_to_hwp: "PDF'den HWP'ye",
  tool_pdf_to_hwp_desc: "PDF'i resmi standart Korece belge formatına dönüştürün",
  btn_select_files: "Dosyaları Seç",
  drop_title_default: "Dosyaları buraya sürükleyip bırakın",
  drop_subtitle_default: "veya dosya seçmek için aşağıdaki butona tıklayın",
  drop_note_privacy: "🔒 %100 yerel tarayıcıda işleme (sunucuda saklanmaz)",
  drop_note_limit: "Sınırsız dosya boyutu desteği",
  drop_badge_secure: "%100 Güvenli Yerel Yükleme",
  drop_mascot_bubble: "Buraya bırakabilirsin! 🐾",
  drop_drag_title: "Anında yüklemek için fareyi bırakın!",
  drop_drag_desc: "Butona veya kutuya bırakın, belgeniz güvenle ve hızla açılır",
  drop_action_drop: "Buraya Bırak (Drop)",
  btn_download_again: "Dosyayı İndir",
  btn_reset: "Tümünü Sıfırla",
  btn_add_files: "Dosya Ekle",
  processing_title: "Kızıl Panda belgenizi güvenle dönüştürüyor...",
  processing_desc: "Lütfen bekleyin. İşlem tamamlandığında indirme otomatik başlar.",
  processing_badge: "%100 tarayıcı belleğinde yerel işleme",
  processing_complete: "Tamamlandı",
  processing_bubble: "Belgenizi süper hızda hazırlıyoruz! 🐾",
  uploaded_card_success: "Dosyalar güvenle ve başarıyla yüklendi!",
  uploaded_card_local_badge: "%100 Yerel Yüklendi",
  uploaded_card_change_file: "Dosyayı Değiştir",
  uploaded_card_and_more: "+ {count} dosya daha",
  uploaded_card_total_pages: "Toplam {count} sayfa",
  uploaded_card_file_size: "Boyut",
  uploaded_card_no_server: "Sunucuya yükleme yok (Bellek yalıtımı)",
  home_mascot_bubble: "Merhaba! Ben Kızıl Panda 🐾 Her türlü belgeyi bana bırak!",
  home_hero_tag: "Kızıl Panda ile %100 Ücretsiz Tarayıcı İçi PDF Çözümü",
  home_hero_title1: "En Sevimli, En Hızlı ve En Güvenli",
  home_hero_title2: "mypickpdf Çevrimiçi Paketi",
  home_hero_desc: "Word, Excel, PowerPoint ve görselleri PDF'e dönüştürün, sıkıştırın ve düzenleyin. Sunucularda 0 bayt bırakan %100 gizli tarayıcı içi işleme.",
  home_tools_title: "Önerilen Popüler PDF Araçları",
  home_tools_subtitle: "İhtiyacınız olan aracı seçin ve hemen başlayın",
  home_use_now: "Şimdi Kullan",
  home_convert_btn: "Dönüştür",
  home_extract_btn: "Ayıkla",
  sponsor_snack_btn: "Kızıl Pandaya atıştırmalık ısmarla ☕",
  home_why_title: "Milyonlarca kullanıcı neden mypickpdf'i seçiyor?",
  home_table_title: "Karşılaştırma: Ücretli siteler vs mypickpdf",
  home_why_sec1_title: "%100 İstemci Tarafı Yerel Güvenlik",
  home_why_sec1_desc: "mypickpdf, belgeleri WebAssembly ile doğrudan tarayıcınızın belleğinde işler. Gizli dosyalarınız asla harici bir sunucuya gitmez.",
  home_why_sec2_title: "Beklemeden Anında İşleme",
  home_why_sec2_desc: "İnternet yükleme beklemesi yok. Onlarca sayfayı 1-2 saniyede işlemek için cihazınızın kendi gücünü kullanır.",
  home_faq_title: "Sıkça Sorulan Sorular (FAQ)",
  home_faq_subtitle: "mypickpdf kullanım kılavuzu ve güvenlik politikaları",
  home_faq_q1: "mypickpdf gerçekten kayıt gerektirmeden %100 ücretsiz mi?",
  home_faq_a1: "Evet! mypickpdf sonsuza kadar tamamen ücretsizdir. Kayıt, giriş ve gizli ücretler yoktur.",
  home_faq_q2: "Dönüştürülen belgeler sunucuda saklanıyor mu?",
  home_faq_a2: "Asla. Tüm işlemler yalnızca cihazınızın belleğinde gerçekleşir ve dışarıya 0 bayt aktarılır.",
  home_faq_q3: "Dönüştürülen Office dosyaları (Word, Excel, PPT) düzenlenebilir mi?",
  home_faq_a3: "Evet! Çıkarılan Word, Excel ve PowerPoint dosyaları Microsoft Office ve diğer programlarda serbestçe düzenlenebilir.",
  home_to_pdf_sub: "(Word, Excel, PPT, Görseller ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, Görseller, PDF/A)",
  share_title: "Arkadaşlarınıza ve iş arkadaşlarınıza önermek ister misiniz? 🐾",
  share_desc: "Hızlı erişim için bağlantıyı 1 saniyede kopyalayın ve yer imlerine ekleyin!",
  share_btn: "Bağlantıyı Paylaş",
  share_copied: "Kopyalandı! 🐾",
  share_bookmark: "Yer İmi",
  share_bookmark_tip: "Bu sayfayı hemen yer imlerine kaydetmek için Ctrl + D (Mac: Cmd + D) tuşlarına basın!",
  video_title: "Video Sıkıştır (MP4 / MOV)",
  video_header_sub: "MP4 / MOV dosya boyutunu küçültün",
  video_desc: "Kalite kaybı olmadan videoları sohbet veya e-posta için %80'e kadar küçültün. %100 yerel tarayıcıda.",
  video_tag: "Yeni Özellik",
  video_drop_title: "Sıkıştırılacak video dosyasını seçin",
  video_drop_subtitle: "MP4, MOV, WebM, MKV formatları desteklenir (sunucuya yükleme yok)",
  video_badge_local: "%100 Yerel Cihazda İşleme (Sunucu depolaması yok)",
  video_badge_hardware: "Donanım Hızlandırmalı Yüksek Hızlı Kodlama",
  video_badge_mobile: "Akıllı Telefon Desteği (iPhone/Android)",
  video_step_level: "Sıkıştırma Seviyesini Seçin",
  video_step_level_desc: "Görüntü kalitesi ile dosya boyutu arasındaki dengeyi seçin",
  video_opt_extreme_title: "Maksimum Sıkıştırma (sohbet ve e-posta için)",
  video_opt_extreme_sub: "%70~85'e varan boyut tasarrufu",
  video_opt_extreme_desc: "Mesajlaşma uygulamaları ve e-posta ekleri için idealdir.",
  video_opt_extreme_badge: "En Küçük Boyut",
  video_opt_rec_title: "Dengeli Sıkıştırma (Önerilen)",
  video_opt_rec_sub: "Yaklaşık %40~60 boyut tasarrufu",
  video_opt_rec_desc: "Net görüntü kalitesi ve belirgin boyut tasarrufu sunan en dengeli seçenek.",
  video_opt_rec_badge: "En Çok Önerilen",
  video_opt_less_title: "Yüksek Kaliteyi Koru (Hafif Sıkıştırma)",
  video_opt_less_sub: "Yaklaşık %20~30 boyut tasarrufu",
  video_opt_less_desc: "Orijinal çözünürlüğü ve detayları en üst düzeyde korur.",
  video_opt_less_badge: "Kalite Öncelikli",
  video_selected: "Seçildi",
  video_btn_compress: "Videoyu Şimdi Sıkıştır",
  video_compressing: "Video sıkıştırılıyor...",
  video_btn_reset: "Yeni Video Sıkıştır",
  video_result_title: "Video Sıkıştırma Tamamlandı!",
  video_result_desc: "Tarayıcı donanım ivmesiyle dosya boyutu büyük oranda küçültüldü.",
  video_original: "Orijinal Boyut",
  video_compressed: "Sıkıştırma Sonrası Boyut",
  video_saved: "Tasarruf Edilen Alan",
  howto_badge: "Hızlı Eğitim",
  howto_heading_suffix: " — Nasıl Kullanılır?",
  howto_subtitle: "Ağır programlar yüklemeden sadece 3 adımda işleminizi tamamlayın.",
  faq_badge: "Soru & Cevap",
  faq_title: "Sıkça Sorulan Sorular (FAQ)",
  faq_subtitle: "Araçlarımızın kullanımı ve veri gizliliği hakkında bilgi alın.",
  guides_portal_badge: "Resmi mypickpdf Kılavuzu",
  guides_portal_title: "PDF ve Belge İş Akışlarında Uzmanlaşın (40+ Rehber)",
  guides_portal_subtitle: "Özgeçmiş birleştirmeden faturalara, tez numaralandırmadan yerel gizliliğe kadar 40'tan fazla pratik rehberle her şeyi öğrenin.",
  guides_search_placeholder: "Rehber veya anahtar kelime ara (örn: birleştir, sıkıştır, mobil...)",
  guides_cat_all: "Tümü",
  guides_cat_edit: "PDF Düzenleme",
  guides_cat_convert: "Office Dönüştürme",
  guides_cat_security: "Güvenlik ve Gizlilik",
  guides_cat_media: "Medya ve GIF",
  guides_cat_mobile: "Mobil İpuçları",
  guides_read_article: "Rehberi Oku",
  guides_direct_tool: "Aracı Aç",
  guides_back_to_list: "Rehber Listesine Dön",
  guides_quick_cta_title: "Şimdi kendiniz deneyin!",
  guides_share: "Rehberi Paylaş",
  guides_copied: "Bağlantı kopyalandı!",
  ad_label: "Reklam / ADVERTISEMENT",
  ad_placeholder_title: "Sponsorlu Reklam Alanı",
  ad_placeholder_desc: "Hizmetin ücretsiz kalmasını sağlayan reklam alanı.",
  footer_security_title: "Mutlak Gizlilik ve Belge Güvenliği Garantisi",
  footer_security_desc: "mypickpdf dosyalarınızı asla uzak sunuculara göndermez veya kaydetmez. Tüm işlemler %100 kendi tarayıcınızda gerçekleştirilir.",
  footer_privacy_leak: "%0 Dış Veri Sızıntısı",
  footer_about: "Sevimli Kızıl Panda ile herkesin giriş yapmadan, ücretsiz ve hızlıca PDF düzenleyebileceği yeni nesil web aracı.",
  footer_col_tools: "Popüler Araçlar",
  footer_col_tech: "Teknoloji ve Güvenlik",
  footer_col_legal: "Destek ve Şartlar",
  footer_privacy_link: "Gizlilik Politikası",
  footer_terms_link: "Kullanım Koşulları",
  footer_contact_link: "İletişim ve Öneriler",
  footer_rights: "All rights reserved. Tüm hakları saklıdır."
};

// --- SWEDISH (sv) ---
const sv = {
  brand_name: "mypickpdf (Röd Panda PDF)",
  nav_brand_tag: "100% Gratis & Säkra PDF-verktyg med Röda Pandan",
  nav_all_tools: "Alla PDF-verktyg",
  nav_convert_pdf: "Konvertera PDF",
  nav_to_pdf: "Konvertera till PDF",
  nav_from_pdf: "Konvertera från PDF",
  nav_privacy_badge: "0% Serverlagring",
  nav_free_badge: "Obegränsat Gratis, Ingen Inloggning",
  nav_guides: "Guider",
  nav_core_tools: "PDF-redigeringsverktyg",
  nav_media_tools: "Video- & Medieverktyg",
  nav_select_lang: "Välj språk (Select Language)",
  nav_current_lang: "Aktuellt språk",
  badge_free_utility: "100% Gratis Verktyg",
  badge_no_server: "Ingen serveröverföring (Lokal säkerhet)",
  badge_no_login: "Ingen registrering eller inloggning krävs",
  badge_unlimited_free: "Blixtsnabbt & Obegränsat Gratis",
  badge_client_engine: "100% Klientmotor i webbläsaren",
  badge_security: "Säkerhet",
  tool_merge: "Slå ihop PDF",
  tool_merge_desc: "Slå ihop flera PDF-filer till ett enda dokument",
  tool_split: "Dela PDF",
  tool_split_desc: "Extrahera utvalda sidor eller dela varje sida för sig",
  tool_compress: "Komprimera PDF",
  tool_compress_desc: "Minska PDF-filstorleken med bibehållen maximal kvalitet",
  tool_rotate: "Rotera PDF",
  tool_rotate_desc: "Rotera ditt PDF-dokument 90 eller 180 grader",
  tool_ocr: "PDF OCR (Textigenkänning)",
  tool_ocr_desc: "Extrahera redigerbar text från skannade PDF-filer och bilder",
  tool_page_numbers: "Lägg till sidnummer",
  tool_page_numbers_desc: "Infoga sidnummer på önskade platser och format",
  tool_watermark: "Lägg till vattenstämpel",
  tool_watermark_desc: "Lägg till en text- eller bildvattenstämpel på dina dokument",
  tool_compress_video: "Komprimera video",
  tool_compress_video_desc: "Minska storleken på MP4- och MOV-videor med upp till 80% utan kvalitetsförlust",
  tool_video_to_gif: "Video till GIF",
  tool_video_to_gif_desc: "Förvandla videoklipp till högkvalitativa animerade GIF-bilder",
  tool_img_to_pdf: "Bild till PDF",
  tool_img_to_pdf_desc: "Konvertera JPG- och PNG-bilder till PDF-dokument",
  tool_word_to_pdf: "Word till PDF",
  tool_word_to_pdf_desc: "Konvertera Word-dokument (.docx) till PDF direkt",
  tool_ppt_to_pdf: "PowerPoint till PDF",
  tool_ppt_to_pdf_desc: "Konvertera PowerPoint-presentationer (.pptx) till PDF",
  tool_excel_to_pdf: "Excel till PDF",
  tool_excel_to_pdf_desc: "Konvertera Excel-kalkylblad (.xlsx) till snygga PDF-filer",
  tool_html_to_pdf: "HTML till PDF",
  tool_html_to_pdf_desc: "Rendera webbsidors HTML-kod direkt till PDF",
  tool_pdf_to_img: "PDF till bild",
  tool_pdf_to_img_desc: "Spara varje sida i din PDF som en högupplöst JPG-bild",
  tool_pdf_to_word: "PDF till Word",
  tool_pdf_to_word_desc: "Konvertera PDF till ett redigerbart Word-dokument (.docx)",
  tool_pdf_to_ppt: "PDF till PowerPoint",
  tool_pdf_to_ppt_desc: "Konvertera PDF till redigerbara PowerPoint-bilder (.pptx)",
  tool_pdf_to_excel: "PDF till Excel",
  tool_pdf_to_excel_desc: "Extrahera PDF-tabeller till ett Excel-kalkylblad (.xlsx)",
  tool_pdf_to_pdfa: "PDF till PDF/A",
  tool_pdf_to_pdfa_desc: "Konvertera till ISO-standard PDF/A för långtidsarkivering",
  tool_pdf_to_hwp: "PDF till HWP/HWPX",
  tool_pdf_to_hwp_desc: "Konvertera PDF till officiellt koreanskt dokumentformat",
  btn_select_files: "Välj filer",
  drop_title_default: "Dra och släpp filer här",
  drop_subtitle_default: "eller klicka på knappen nedan för att välja filer",
  drop_note_privacy: "🔒 100% lokal bearbetning i webbläsaren (ingen serverlagring)",
  drop_note_limit: "Obegränsad filstorlek stöds",
  drop_badge_secure: "100% Säker Lokal Laddning",
  drop_mascot_bubble: "Släpp filerna här! 🐾",
  drop_drag_title: "Släpp för att ladda filen direkt!",
  drop_drag_desc: "Oavsett om det är på knappen eller rutan öppnas filen snabbt och säkert",
  drop_action_drop: "Släpp här (Drop)",
  btn_download_again: "Ladda ner fil",
  btn_reset: "Återställ allt",
  btn_add_files: "Lägg till filer",
  processing_title: "Röda Pandan bearbetar ditt dokument säkert...",
  processing_desc: "Vänligen vänta. Nedladdningen startar automatiskt när den är klar.",
  processing_badge: "100% lokal bearbetning i webbläsarens minne",
  processing_complete: "Klart",
  processing_bubble: "Färdigställer ditt dokument i blixtfart! 🐾",
  uploaded_card_success: "Filer har laddats upp säkert och framgångsrikt!",
  uploaded_card_local_badge: "100% Lokalt Laddat",
  uploaded_card_change_file: "Byt fil",
  uploaded_card_and_more: "+ {count} till",
  uploaded_card_total_pages: "Totalt {count} sidor",
  uploaded_card_file_size: "Storlek",
  uploaded_card_no_server: "Noll uppladdningar till server (Isolerat minne)",
  home_mascot_bubble: "Hej! Jag är Röda Pandan 🐾 Lämna alla dina dokument till mig!",
  home_hero_tag: "100% Gratis PDF-verktyg i webbläsaren med Röda Pandan",
  home_hero_title1: "Det gulligaste, snabbaste och säkraste",
  home_hero_title2: "mypickpdf Onlinesystemet",
  home_hero_desc: "Konvertera, komprimera och redigera Word, Excel, PowerPoint och bilder till och från PDF med vår söta panda. 100% privat bearbetning som lämnar 0 byte på servrar.",
  home_tools_title: "Populära Rekommenderade PDF-verktyg",
  home_tools_subtitle: "Välj verktyget du behöver och kom igång direkt",
  home_use_now: "Använd nu",
  home_convert_btn: "Konvertera",
  home_extract_btn: "Extrahera",
  sponsor_snack_btn: "Bjud Röda Pandan på fika ☕",
  home_why_title: "Varför väljer miljontals användare mypickpdf?",
  home_table_title: "Jämförelse: Betalsajter vs mypickpdf",
  home_why_sec1_title: "100% Lokal Säkerhet på Klientnivå",
  home_why_sec1_desc: "mypickpdf bearbetar dokument direkt i webbläsarens arbetsminne via WebAssembly. Dina konfidentiella filer når aldrig externa servrar.",
  home_why_sec2_title: "Omedelbar Bearbetning Utan Fördröjning",
  home_why_sec2_desc: "Ingen väntetid på nätverksuppladdningar. Använder din egen enhets beräkningskraft för att bearbeta dussintals sidor på 1-2 sekunder.",
  home_faq_title: "Vanliga Frågor (FAQ)",
  home_faq_subtitle: "Användarguide och säkerhetspolicy för mypickpdf",
  home_faq_q1: "Är mypickpdf verkligen 100% gratis utan inloggning?",
  home_faq_a1: "Ja! mypickpdf är helt gratis för alltid. Ingen registrering, ingen inloggning och inga dolda avgifter.",
  home_faq_q2: "Sparas konverterade dokument på någon server?",
  home_faq_a2: "Aldrig någonsin. Alla dokument bearbetas enbart i din enhets minne och 0 byte överförs utåt.",
  home_faq_q3: "Är konverterade Office-filer (Word, Excel, PPT) redigerbara?",
  home_faq_a3: "Självklart! De exporterade Word-, Excel- och PowerPoint-filerna kan öppnas och redigeras fritt i Microsoft Office.",
  home_to_pdf_sub: "(Word, Excel, PPT, Bilder ➔ PDF)",
  home_from_pdf_sub: "(PDF ➔ Word, Excel, PPT, Bilder, PDF/A)",
  share_title: "Vill du rekommendera oss till vänner och kollegor? 🐾",
  share_desc: "Kopiera länken på 1 sekund och bokmärk sidan för snabb åtkomst!",
  share_btn: "Dela länk",
  share_copied: "Kopierat! 🐾",
  share_bookmark: "Bokmärke",
  share_bookmark_tip: "Tryck på Ctrl + D (Mac: Cmd + D) för att bokmärka den här sidan direkt!",
  video_title: "Komprimera video (MP4 / MOV)",
  video_header_sub: "Minska filstorleken på MP4 / MOV",
  video_desc: "Minska videostorleken med upp till 80% för chatt eller e-post utan märkbar kvalitetsförlust. 100% lokalt i webbläsaren.",
  video_tag: "Ny Funktion",
  video_drop_title: "Välj videofil att komprimera",
  video_drop_subtitle: "Stöd för MP4, MOV, WebM, MKV (ingen serveruppladdning)",
  video_badge_local: "100% Lokal Bearbetning (Ingen serverlagring)",
  video_badge_hardware: "Hårdvaruaccelererad Höghastighetskodning",
  video_badge_mobile: "Fullt stöd för smartphones (iPhone/Android)",
  video_step_level: "Välj Komprimeringsnivå",
  video_step_level_desc: "Välj den perfekta balansen mellan bildkvalitet och filstorlek",
  video_opt_extreme_title: "Maximal Komprimering (för chatt & e-post)",
  video_opt_extreme_sub: "Upp till 70~85% storleksminskning",
  video_opt_extreme_desc: "Perfekt för att skicka i meddelandeappar och e-postbilagor.",
  video_opt_extreme_badge: "Minsta Storlek",
  video_opt_rec_title: "Balanserad Komprimering (Rekommenderad)",
  video_opt_rec_sub: "Cirka 40~60% storleksminskning",
  video_opt_rec_desc: "Vårt bästa val med skarp bildkvalitet och betydande platsbesparing.",
  video_opt_rec_badge: "Bästa Valet",
  video_opt_less_title: "Behåll Hög Kvalitet (Lätt Komprimering)",
  video_opt_less_sub: "Cirka 20~30% storleksminskning",
  video_opt_less_desc: "Bevarar maximal skärpa och ursprungliga detaljer.",
  video_opt_less_badge: "Kvalitet Först",
  video_selected: "Vald",
  video_btn_compress: "Komprimera video nu",
  video_compressing: "Komprimerar video...",
  video_btn_reset: "Komprimera ny video",
  video_result_title: "Videokomprimering Klar!",
  video_result_desc: "Filstorleken har minskats avsevärt tack vare hårdvaruacceleration.",
  video_original: "Ursprunglig storlek",
  video_compressed: "Storlek efter komprimering",
  video_saved: "Sparat utrymme",
  howto_badge: "Snabbguide",
  howto_heading_suffix: " — Hur man använder",
  howto_subtitle: "Slutför uppgiften i 3 enkla steg utan att installera tunga program.",
  faq_badge: "Frågor & Svar",
  faq_title: "Vanliga Frågor (FAQ)",
  faq_subtitle: "Hitta svar om hur våra verktyg fungerar och hur din data skyddas.",
  guides_portal_badge: "Officiell mypickpdf Handbok",
  guides_portal_title: "Bemästra PDF- och Dokumentarbetsflöden (40+ Guider)",
  guides_portal_subtitle: "Från sammanfogning av CV och fakturor till sidnumrering och lokal säkerhet: lär dig allt i våra praktiska guider.",
  guides_search_placeholder: "Sök guide eller nyckelord (t.ex. slå ihop, komprimera, mobil...)",
  guides_cat_all: "Alla",
  guides_cat_edit: "PDF-redigering",
  guides_cat_convert: "Office-konvertering",
  guides_cat_security: "Säkerhet & Integritet",
  guides_cat_media: "Media & GIF",
  guides_cat_mobile: "Mobiltips",
  guides_read_article: "Läs guiden",
  guides_direct_tool: "Öppna verktyget",
  guides_back_to_list: "Tillbaka till listan",
  guides_quick_cta_title: "Prova själv nu direkt!",
  guides_share: "Dela denna guide",
  guides_copied: "Länken har kopierats!",
  ad_label: "Annons / ADVERTISEMENT",
  ad_placeholder_title: "Sponsrad Annonsplats",
  ad_placeholder_desc: "Annonsplats för att hålla tjänsten gratis.",
  footer_security_title: "Garanti för Total Sekretess & Dokumentsäkerhet",
  footer_security_desc: "mypickpdf laddar aldrig upp eller sparar dina filer på externa servrar. Alla operationer utförs 100% i din egen webbläsare.",
  footer_privacy_leak: "0% Externa Dataläckor",
  footer_about: "Ett modernt webbverktyg tillsammans med den söta Röda Pandan som låter alla redigera och konvertera PDF-filer gratis och utan registrering.",
  footer_col_tools: "Populära Verktyg",
  footer_col_tech: "Teknik & Säkerhet",
  footer_col_legal: "Hjälp & Villkor",
  footer_privacy_link: "Integritetspolicy",
  footer_terms_link: "Användarvillkor",
  footer_contact_link: "Kontakt & Feedback",
  footer_rights: "All rights reserved. Alla rättigheter förbehållna."
};

fs.writeFileSync(path.join(outDir, 'ru.ts'), `import { TranslationDictionary } from "./types";\n\nexport const ru: TranslationDictionary = ${JSON.stringify(ru, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'uk.ts'), `import { TranslationDictionary } from "./types";\n\nexport const uk: TranslationDictionary = ${JSON.stringify(uk, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'pl.ts'), `import { TranslationDictionary } from "./types";\n\nexport const pl: TranslationDictionary = ${JSON.stringify(pl, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'tr.ts'), `import { TranslationDictionary } from "./types";\n\nexport const tr: TranslationDictionary = ${JSON.stringify(tr, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, 'sv.ts'), `import { TranslationDictionary } from "./types";\n\nexport const sv: TranslationDictionary = ${JSON.stringify(sv, null, 2)};\n`);

console.log('Generated ru.ts, uk.ts, pl.ts, tr.ts, sv.ts');
