const fs = require('fs');
const path = require('path');

const outDir = path.join(__dirname, '../src/lib/translations');

// Helper to load file and parse
function loadDict(filename) {
  const content = fs.readFileSync(path.join(outDir, filename), 'utf8');
  const jsonStr = content.replace(/import[\s\S]*?export const [a-zA-Z0-9]+: TranslationDictionary = /, '').replace(/;\s*$/, '');
  return eval('(' + jsonStr + ')');
}

function saveDict(filename, varName, dict) {
  fs.writeFileSync(
    path.join(outDir, filename),
    `import { TranslationDictionary } from "./types";\n\nexport const ${varName}: TranslationDictionary = ${JSON.stringify(dict, null, 2)};\n`
  );
}

// 1. GERMAN (de)
const deExtra = {
  ad_label: "Werbung / ADVERTISEMENT",
  ad_placeholder_title: "Gesponserte Werbefläche",
  ad_placeholder_desc: "Werbefläche zur Erhaltung des kostenlosen Dienstes.",
  badge_free_utility: "100% Kostenloses Dienstprogramm",
  badge_no_login: "Keine Registrierung erforderlich",
  badge_no_server: "Keine Serverübertragung (Lokale Sicherheit)",
  badge_unlimited_free: "Superschnell & Unbegrenzt Kostenlos",
  footer_col_legal: "Hilfe & Richtlinien",
  footer_col_tech: "Technik & Sicherheit",
  footer_col_tools: "Beliebte Werkzeuge",
  home_convert_btn: "Konvertieren",
  home_extract_btn: "Extrahieren",
  home_mascot_bubble: "Hallo! Ich bin der Rote Panda 🐾 Überlassen Sie mir jedes Dokument!",
  home_table_title: "Vergleich: Kostenpflichtige Seiten vs mypickpdf",
  home_why_title: "Warum Millionen von Nutzern mypickpdf wählen?",
  nav_core_tools: "PDF-Bearbeitungswerkzeuge",
  nav_media_tools: "Video- & Medienwerkzeuge",
  sponsor_snack_btn: "Roter Panda Snack-Spende ☕",
  video_badge_hardware: "Hardwarebeschleunigte Highspeed-Kodierung",
  video_badge_local: "100% lokale Geräteverarbeitung (Keine Serverspeicherung)",
  video_badge_mobile: "Volle Smartphone-Unterstützung (iPhone/Android)",
  video_btn_compress: "Video jetzt komprimieren",
  video_btn_reset: "Neues Video komprimieren",
  video_compressed: "Größe nach Komprimierung",
  video_compressing: "Video wird komprimiert...",
  video_desc: "Verkleinern Sie Videos um bis zu 80% für Chats oder E-Mails ohne Qualitätsverlust. 100% lokal im Browser.",
  video_drop_subtitle: "Unterstützt alle Formate MP4, MOV, WebM, MKV (kein Server-Upload)",
  video_drop_title: "Videodatei zum Komprimieren auswählen",
  video_header_sub: "MP4 / MOV Dateigröße reduzieren",
  video_opt_extreme_badge: "Kleinste Größe",
  video_opt_extreme_desc: "Optimal für Messenger-Dienste und E-Mail-Anhänge.",
  video_opt_extreme_sub: "Bis zu 70~85% Platzersparnis",
  video_opt_extreme_title: "Maximale Komprimierung (für Chat & Mail)",
  video_opt_less_badge: "Qualität zuerst",
  video_opt_less_desc: "Erhält maximale Bildschärfe und ursprüngliche Details.",
  video_opt_less_sub: "Ca. 20~30% Platzersparnis",
  video_opt_less_title: "Hohe Qualität beibehalten (Leichte Komprimierung)",
  video_opt_rec_badge: "Sehr empfohlen",
  video_opt_rec_desc: "Beste Balance zwischen klarer Bildqualität und deutlicher Größenreduzierung.",
  video_opt_rec_sub: "Ca. 40~60% Platzersparnis",
  video_opt_rec_title: "Ausgewogene Komprimierung (Empfohlen)",
  video_original: "Ursprüngliche Größe",
  video_result_desc: "Die Dateigröße wurde dank Browserbeschleunigung erheblich reduziert.",
  video_result_title: "Videokomprimierung abgeschlossen!",
  video_saved: "Gesparter Speicherplatz",
  video_selected: "Ausgewählt",
  video_step_level: "Komprimierungsstufe wählen",
  video_step_level_desc: "Wählen Sie die ideale Balance aus Bildqualität und Dateigröße",
  video_tag: "Neue Funktion",
  video_title: "Video komprimieren (MP4 / MOV)"
};
const de = { ...loadDict('de.ts'), ...deExtra };
saveDict('de.ts', 'de', de);

// 2. FRENCH (fr)
const frExtra = {
  ad_label: "Publicité / ADVERTISEMENT",
  ad_placeholder_title: "Espace publicitaire sponsorisé",
  ad_placeholder_desc: "Espace d'annonces permettant de maintenir le service gratuit.",
  badge_free_utility: "Utilitaire 100% Gratuit",
  badge_no_login: "Sans inscription ni connexion",
  badge_no_server: "Aucun envoi sur serveur (Traitement local)",
  badge_unlimited_free: "Ultra-rapide et Illimité",
  footer_col_legal: "Support & Conditions",
  footer_col_tech: "Technologie & Sécurité",
  footer_col_tools: "Outils populaires",
  home_convert_btn: "Convertir",
  home_extract_btn: "Extraire",
  home_mascot_bubble: "Bonjour ! Je suis le Panda Roux 🐾 Confiez-moi tous vos documents !",
  home_table_title: "Comparatif : Sites payants vs mypickpdf",
  home_why_title: "Pourquoi des millions d'utilisateurs choisissent mypickpdf ?",
  nav_core_tools: "Outils d'édition PDF",
  nav_media_tools: "Outils Vidéo & Médias",
  sponsor_snack_btn: "Offrir un goûter au Panda Roux ☕",
  video_badge_hardware: "Encodage rapide avec accélération matérielle",
  video_badge_local: "Traitement 100% local sur l'appareil (Aucun stockage)",
  video_badge_mobile: "Compatibilité totale mobile (iPhone/Android)",
  video_btn_compress: "Compresser la vidéo maintenant",
  video_btn_reset: "Compresser une autre vidéo",
  video_compressed: "Taille après compression",
  video_compressing: "Compression de la vidéo en cours...",
  video_desc: "Réduisez la taille de vos vidéos jusqu'à 80% pour chat ou e-mail sans perte de qualité visible. 100% local.",
  video_drop_subtitle: "Prend en charge tous formats MP4, MOV, WebM, MKV (sans téléversement)",
  video_drop_title: "Sélectionnez le fichier vidéo à compresser",
  video_header_sub: "Réduire la taille de fichier MP4 / MOV",
  video_opt_extreme_badge: "Taille minimale",
  video_opt_extreme_desc: "Idéal pour l'envoi sur messageries instantanées et pièces jointes.",
  video_opt_extreme_sub: "Jusqu'à 70~85% d'espace économisé",
  video_opt_extreme_title: "Compression maximale (pour chat & email)",
  video_opt_less_badge: "Priorité qualité",
  video_opt_less_desc: "Préserve au maximum la résolution et les détails originaux.",
  video_opt_less_sub: "Environ 20~30% d'espace économisé",
  video_opt_less_title: "Conserver haute qualité (Compression légère)",
  video_opt_rec_badge: "Recommandé",
  video_opt_rec_desc: "Le meilleur compromis entre netteté visuelle et allègement significatif.",
  video_opt_rec_sub: "Environ 40~60% d'espace économisé",
  video_opt_rec_title: "Compression équilibrée (Standard recommandé)",
  video_original: "Taille d'origine",
  video_result_desc: "La taille du fichier a été considérablement réduite grâce à l'accélération navigateur.",
  video_result_title: "Compression vidéo terminée !",
  video_saved: "Espace économisé",
  video_selected: "Sélectionné",
  video_step_level: "Choisir le niveau de compression",
  video_step_level_desc: "Sélectionnez l'équilibre parfait entre qualité d'image et taille de fichier",
  video_tag: "Nouveau",
  video_title: "Compresser vidéo (MP4 / MOV)"
};
const fr = { ...loadDict('fr.ts'), ...frExtra };
saveDict('fr.ts', 'fr', fr);

// 3. ITALIAN (it)
const itExtra = {
  ad_label: "Pubblicità / ADVERTISEMENT",
  ad_placeholder_title: "Spazio pubblicitario sponsorizzato",
  ad_placeholder_desc: "Spazio pubblicitario per mantenere il servizio gratuito.",
  badge_free_utility: "Utility 100% Gratuita",
  badge_no_login: "Nessuna registrazione o login",
  badge_no_server: "Nessun invio al server (Sicurezza locale)",
  badge_unlimited_free: "Velocissimo e Illimitato",
  footer_col_legal: "Supporto & Termini",
  footer_col_tech: "Tecnologia & Sicurezza",
  footer_col_tools: "Strumenti più usati",
  home_convert_btn: "Converti",
  home_extract_btn: "Estrai",
  home_mascot_bubble: "Ciao! Sono il Panda Rosso 🐾 Affidami qualsiasi documento!",
  home_table_title: "Confronto: Siti a pagamento vs mypickpdf",
  home_why_title: "Perché milioni di utenti scelgono mypickpdf?",
  nav_core_tools: "Strumenti di Modifica PDF",
  nav_media_tools: "Strumenti Video & Media",
  sponsor_snack_btn: "Offri uno snack al Panda Rosso ☕",
  video_badge_hardware: "Codifica ad alta velocità con accelerazione hardware",
  video_badge_local: "Elaborazione 100% locale sul dispositivo (Nessun server)",
  video_badge_mobile: "Supporto totale smartphone (iPhone/Android)",
  video_btn_compress: "Comprimi video adesso",
  video_btn_reset: "Comprimi nuovo video",
  video_compressed: "Dimensione dopo la compressione",
  video_compressing: "Compressione video in corso...",
  video_desc: "Riduci le dimensioni dei video fino all'80% per chat o email senza perdita visibile di qualità. 100% locale.",
  video_drop_subtitle: "Supporta tutti i formati MP4, MOV, WebM, MKV (senza upload al server)",
  video_drop_title: "Seleziona il file video da comprimere",
  video_header_sub: "Riduci dimensione file MP4 / MOV",
  video_opt_extreme_badge: "Dimensione minima",
  video_opt_extreme_desc: "Perfetto per l'invio su chat e allegati e-mail.",
  video_opt_extreme_sub: "Fino al 70~85% di spazio risparmiato",
  video_opt_extreme_title: "Compressione massima (per chat ed email)",
  video_opt_less_badge: "Priorità qualità",
  video_opt_less_desc: "Mantiene al massimo la risoluzione e i dettagli originali.",
  video_opt_less_sub: "Circa 20~30% di spazio risparmiato",
  video_opt_less_title: "Mantieni alta qualità (Compressione leggera)",
  video_opt_rec_badge: "Più consigliato",
  video_opt_rec_desc: "Il miglior equilibrio tra nitidezza dell'immagine e notevole riduzione di peso.",
  video_opt_rec_sub: "Circa 40~60% di spazio risparmiato",
  video_opt_rec_title: "Compressione bilanciata (Consigliata)",
  video_original: "Dimensione iniziale",
  video_result_desc: "La dimensione del file è stata notevolmente ridotta grazie all'accelerazione nel browser.",
  video_result_title: "Compressione video completata!",
  video_saved: "Spazio risparmiato",
  video_selected: "Selezionato",
  video_step_level: "Scegli livello di compressione",
  video_step_level_desc: "Seleziona il perfetto equilibrio tra qualità video e dimensione del file",
  video_tag: "Nuova funzione",
  video_title: "Comprimi video (MP4 / MOV)"
};
const it = { ...loadDict('it.ts'), ...itExtra };
saveDict('it.ts', 'it', it);

// 4. PORTUGUESE (pt)
const ptExtra = {
  ad_label: "Anúncio / ADVERTISEMENT",
  ad_placeholder_title: "Espaço publicitário patrocinado",
  ad_placeholder_desc: "Espaço de anúncio para manter este serviço gratuito.",
  badge_free_utility: "Utilitário 100% Gratuito",
  badge_no_login: "Sem cadastro ou login",
  badge_no_server: "Sem envio para servidor (Processamento local)",
  badge_unlimited_free: "Super rápido e Ilimitado",
  footer_col_legal: "Suporte & Termos",
  footer_col_tech: "Tecnologia & Segurança",
  footer_col_tools: "Ferramentas Populares",
  home_convert_btn: "Converter",
  home_extract_btn: "Extrair",
  home_mascot_bubble: "Olá! Sou o Panda Vermelho 🐾 Deixe qualquer documento comigo!",
  home_table_title: "Comparação: Sites pagos vs mypickpdf",
  home_why_title: "Por que milhões de usuários escolhem o mypickpdf?",
  nav_core_tools: "Ferramentas de Edição de PDF",
  nav_media_tools: "Ferramentas de Vídeo & Mídia",
  sponsor_snack_btn: "Pagar um lanche para o Panda ☕",
  video_badge_hardware: "Codificação ultrarrápida com aceleração de hardware",
  video_badge_local: "Processamento 100% local no dispositivo (Sem servidores)",
  video_badge_mobile: "Compatibilidade total com celular (iPhone/Android)",
  video_btn_compress: "Comprimir vídeo agora",
  video_btn_reset: "Comprimir novo vídeo",
  video_compressed: "Tamanho após compressão",
  video_compressing: "Comprimindo vídeo...",
  video_desc: "Reduza o tamanho de vídeos em até 80% para chat ou e-mail sem perder qualidade perceptível. 100% local.",
  video_drop_subtitle: "Suporta todos os formatos MP4, MOV, WebM, MKV (sem upload)",
  video_drop_title: "Selecione o arquivo de vídeo para comprimir",
  video_header_sub: "Reduzir tamanho de arquivo MP4 / MOV",
  video_opt_extreme_badge: "Menor tamanho",
  video_opt_extreme_desc: "Ideal para compartilhamento em aplicativos de mensagens e e-mails.",
  video_opt_extreme_sub: "Economia de até 70~85% de espaço",
  video_opt_extreme_title: "Compressão máxima (para chat e e-mail)",
  video_opt_less_badge: "Qualidade primeiro",
  video_opt_less_desc: "Preserva a resolução e os detalhes originais ao máximo.",
  video_opt_less_sub: "Economia de cerca de 20~30% de espaço",
  video_opt_less_title: "Manter alta qualidade (Compressão leve)",
  video_opt_rec_badge: "Mais recomendado",
  video_opt_rec_desc: "O equilíbrio perfeito entre imagem nítida e alívio significativo de peso.",
  video_opt_rec_sub: "Economia de cerca de 40~60% de espaço",
  video_opt_rec_title: "Compressão equilibrada (Recomendado)",
  video_original: "Tamanho original",
  video_result_desc: "O tamanho do arquivo foi drasticamente reduzido com aceleração no navegador.",
  video_result_title: "Compressão de vídeo concluída!",
  video_saved: "Espaço economizado",
  video_selected: "Selecionado",
  video_step_level: "Escolha o nível de compressão",
  video_step_level_desc: "Escolha o equilíbrio ideal entre qualidade de imagem e tamanho de arquivo",
  video_tag: "Novo Recurso",
  video_title: "Comprimir vídeo (MP4 / MOV)"
};
const pt = { ...loadDict('pt.ts'), ...ptExtra };
saveDict('pt.ts', 'pt', pt);

// 5. RUSSIAN (ru)
const ruExtra = {
  ad_label: "Реклама / ADVERTISEMENT",
  ad_placeholder_title: "Спонсорский рекламный блок",
  ad_placeholder_desc: "Рекламное место для поддержания сервиса бесплатным.",
  badge_free_utility: "100% Бесплатная Утилита",
  badge_no_login: "Без регистрации и входа",
  badge_no_server: "Без отправки на сервер (Локальная безопасность)",
  badge_unlimited_free: "Сверхбыстро и Безлимитно Бесплатно",
  footer_col_legal: "Поддержка и Условия",
  footer_col_tech: "Технологии и Безопасность",
  footer_col_tools: "Популярные Инструменты",
  home_convert_btn: "Конвертировать",
  home_extract_btn: "Извлечь",
  home_mascot_bubble: "Привет! Я Красная Панда 🐾 Доверьте мне любой документ!",
  home_table_title: "Сравнение: Платные сервисы против mypickpdf",
  home_why_title: "Почему миллионы пользователей выбирают mypickpdf?",
  nav_core_tools: "Инструменты Редактирования PDF",
  nav_media_tools: "Инструменты Видео и Медиа",
  sponsor_snack_btn: "Угостить Красную Панду лакомством ☕",
  video_badge_hardware: "Аппаратное ускорение высокоскоростного кодирования",
  video_badge_local: "100% Локальная обработка на устройстве (Без серверов)",
  video_badge_mobile: "Полная поддержка смартфонов (iPhone/Android)",
  video_btn_compress: "Сжать видео сейчас",
  video_btn_reset: "Сжать новое видео",
  video_compressed: "Размер после сжатия",
  video_compressing: "Сжатие видео...",
  video_desc: "Уменьшите размер видео до 80% для чатов или почты без потери качества. 100% локально в браузере.",
  video_drop_subtitle: "Поддержка всех форматов MP4, MOV, WebM, MKV (без загрузки на сервер)",
  video_drop_title: "Выберите видеофайл для сжатия",
  video_header_sub: "Уменьшить размер MP4 / MOV",
  video_opt_extreme_badge: "Минимальный размер",
  video_opt_extreme_desc: "Идеально подходит для мессенджеров и вложений в почту.",
  video_opt_extreme_sub: "Экономия размера до 70~85%",
  video_opt_extreme_title: "Максимальное сжатие (для чатов и почты)",
  video_opt_less_badge: "Приоритет качества",
  video_opt_less_desc: "Максимально сохраняет исходное разрешение и детали.",
  video_opt_less_sub: "Экономия размера около 20~30%",
  video_opt_less_title: "Сохранить высокое качество (Легкое сжатие)",
  video_opt_rec_badge: "Рекомендуется",
  video_opt_rec_desc: "Лучший баланс между четкой картинкой и значительным снижением веса.",
  video_opt_rec_sub: "Экономия размера около 40~60%",
  video_opt_rec_title: "Сбалансированное сжатие (Стандарт)",
  video_original: "Исходный размер",
  video_result_desc: "Размер файла значительно уменьшен благодаря аппаратному ускорению браузера.",
  video_result_title: "Сжатие видео завершено!",
  video_saved: "Сэкономлено места",
  video_selected: "Выбрано",
  video_step_level: "Выберите уровень сжатия",
  video_step_level_desc: "Выберите баланс между качеством картинки и размером файла",
  video_tag: "Новинка",
  video_title: "Сжатие видео (MP4 / MOV)"
};
const ru = { ...loadDict('ru.ts'), ...ruExtra };
saveDict('ru.ts', 'ru', ru);

// 6. ARABIC (ar)
const arExtra = {
  ad_label: "إعلان / ADVERTISEMENT",
  ad_placeholder_title: "مساحة إعلانية برعاية",
  ad_placeholder_desc: "مساحة إعلانية للحفاظ على الخدمة مجانية للجميع.",
  badge_free_utility: "أداة مجانية 100%",
  badge_no_login: "لا حاجة لتسجيل أو دخول",
  badge_no_server: "بدون نقل إلى الخادم (معالجة محلية آمنة)",
  badge_unlimited_free: "فائق السرعة ومجاني بلا حدود",
  footer_col_legal: "الدعم والشروط",
  footer_col_tech: "التقنية والأمان",
  footer_col_tools: "الأدوات الشائعة",
  home_convert_btn: "تحويل",
  home_extract_btn: "استخراج",
  home_mascot_bubble: "مرحبًا! أنا الباندا الأحمر 🐾 اترك أي مستند لي!",
  home_table_title: "مقارنة: المواقع المدفوعة مقابل mypickpdf",
  home_why_title: "لماذا يختار ملايين المستخدمين mypickpdf؟",
  nav_core_tools: "أدوات تعديل PDF",
  nav_media_tools: "أدوات الفيديو والوسائط",
  sponsor_snack_btn: "تقديم وجبة خفيفة للباندا ☕",
  video_badge_hardware: "ترميز عالي السرعة مدعوم بالعتاد",
  video_badge_local: "معالجة محلية 100% على الجهاز (بدون خوادم)",
  video_badge_mobile: "دعم كامل للهواتف الذكية (iPhone/Android)",
  video_btn_compress: "ضغط الفيديو الآن",
  video_btn_reset: "ضغط فيديو جديد",
  video_compressed: "الحجم بعد الضغط",
  video_compressing: "جارٍ ضغط الفيديو...",
  video_desc: "قلل حجم الفيديو حتى 80% للدردشة أو البريد دون فقد ملحوظ في الجودة. 100% محلياً في المتصفح.",
  video_drop_subtitle: "يدعم جميع صيغ MP4, MOV, WebM, MKV (بدون رفع إلى أي خادم)",
  video_drop_title: "اختر ملف الفيديو لضغطه",
  video_header_sub: "تقليل حجم ملفات MP4 / MOV",
  video_opt_extreme_badge: "أصغر حجم",
  video_opt_extreme_desc: "مثالي للمشاركة في تطبيقات المحادثة ومرفقات البريد الإلكتروني.",
  video_opt_extreme_sub: "توفير في الحجم يصل إلى 70~85%",
  video_opt_extreme_title: "أقصى ضغط (للدردشة والبريد)",
  video_opt_less_badge: "الجودة أولاً",
  video_opt_less_desc: "يحافظ على الدقة والتفاصيل الأصلية إلى أقصى حد.",
  video_opt_less_sub: "توفير في الحجم حوالي 20~30%",
  video_opt_less_title: "الحفاظ على جودة عالية (ضغط خفيف)",
  video_opt_rec_badge: "الأكثر تفضيلاً",
  video_opt_rec_desc: "أفضل توازن موصى به بين وضوح الصورة وتخفيض الحجم بشكل كبير.",
  video_opt_rec_sub: "توفير في الحجم حوالي 40~60%",
  video_opt_rec_title: "ضغط متوازن (الخيار القياسي الموصى به)",
  video_original: "الحجم الأصلي",
  video_result_desc: "تم تقليص حجم الملف بشكل كبير بفضل التسريع داخل المتصفح.",
  video_result_title: "اكتمل ضغط الفيديو بنجاح!",
  video_saved: "المساحة الموفرة",
  video_selected: "تم الاختيار",
  video_step_level: "اختر مستوى الضغط",
  video_step_level_desc: "اختر التوازن المناسب بين جودة الفيديو وحجم الملف",
  video_tag: "ميزة جديدة",
  video_title: "ضغط الفيديو (MP4 / MOV)"
};
const ar = { ...loadDict('ar.ts'), ...arExtra };
saveDict('ar.ts', 'ar', ar);

// 7. INDONESIAN (id)
const idExtra = {
  ad_label: "Iklan / ADVERTISEMENT",
  ad_placeholder_title: "Ruang Iklan Bersponsor",
  ad_placeholder_desc: "Ruang iklan untuk menjaga layanan ini tetap gratis bagi semua orang.",
  badge_free_utility: "Utilitas 100% Gratis",
  badge_no_login: "Tanpa daftar atau login",
  badge_no_server: "Tanpa transfer server (Keamanan lokal)",
  badge_unlimited_free: "Super Cepat & Gratis Tanpa Batas",
  footer_col_legal: "Dukungan & Ketentuan",
  footer_col_tech: "Teknologi & Keamanan",
  footer_col_tools: "Alat Populer",
  guides_back_to_list: "Kembali ke daftar panduan",
  guides_cat_all: "Semua",
  guides_cat_convert: "Konversi Office",
  guides_cat_edit: "Edit PDF",
  guides_cat_media: "Media & GIF",
  guides_cat_mobile: "Tips Seluler",
  guides_cat_security: "Keamanan & Privasi",
  guides_copied: "Tautan berhasil disalin!",
  guides_direct_tool: "Buka alat",
  guides_portal_badge: "Buku Panduan Resmi mypickpdf",
  guides_portal_subtitle: "Dari menggabungkan resume dan faktur hingga penomoran tesis dan privasi lokal: pelajari semuanya di sini.",
  guides_portal_title: "Kuasai Alur Kerja PDF & Dokumen (40+ Panduan)",
  guides_quick_cta_title: "Coba sendiri sekarang juga!",
  guides_read_article: "Baca panduan",
  guides_search_placeholder: "Cari panduan atau kata kunci (misal: gabung, kompres, seluler...)",
  guides_share: "Bagikan panduan ini",
  home_convert_btn: "Konversi",
  home_extract_btn: "Ekstrak",
  home_mascot_bubble: "Halo! Saya Panda Merah 🐾 Serahkan dokumen apa pun kepada saya!",
  home_table_title: "Perbandingan: Situs Berbayar vs mypickpdf",
  home_why_title: "Mengapa jutaan pengguna memilih mypickpdf?",
  nav_core_tools: "Alat Pengeditan PDF",
  nav_media_tools: "Alat Video & Media",
  sponsor_snack_btn: "Traktir camilan untuk Panda Merah ☕",
  video_badge_hardware: "Pengkodean berkecepatan tinggi akselerasi perangkat keras",
  video_badge_local: "100% Pemrosesan Perangkat Lokal (Tanpa penyimpanan server)",
  video_badge_mobile: "Dukungan penuh ponsel pintar (iPhone/Android)",
  video_btn_compress: "Kompres video sekarang",
  video_btn_reset: "Kompres video baru",
  video_compressed: "Ukuran setelah kompresi",
  video_compressing: "Mengompresi video...",
  video_desc: "Kecilkan ukuran video hingga 80% untuk obrolan atau email tanpa kehilangan kualitas yang nyata. 100% lokal di browser.",
  video_drop_subtitle: "Mendukung semua video MP4, MOV, WebM, MKV (tanpa unggah ke server)",
  video_drop_title: "Pilih file video yang ingin dikompres",
  video_header_sub: "Perkecil Ukuran File MP4 / MOV",
  video_opt_extreme_badge: "Ukuran Terkecil",
  video_opt_extreme_desc: "Sangat pas untuk dikirim melalui aplikasi perpesanan dan lampiran email.",
  video_opt_extreme_sub: "Hemat ukuran hingga 70~85%",
  video_opt_extreme_title: "Kompresi Maksimal (untuk chat & email)",
  video_opt_less_badge: "Utamakan Kualitas",
  video_opt_less_desc: "Menjaga ketajaman dan detail asli dengan sangat baik.",
  video_opt_less_sub: "Hemat ukuran sekitar 20~30%",
  video_opt_less_title: "Pertahankan Kualitas Tinggi (Kompresi Ringan)",
  video_opt_rec_badge: "Paling Direkomendasikan",
  video_opt_rec_desc: "Keseimbangan terbaik antara gambar yang tajam dan pengurangan ukuran yang signifikan.",
  video_opt_rec_sub: "Hemat ukuran sekitar 40~60%",
  video_opt_rec_title: "Kompresi Seimbang (Standar)",
  video_original: "Ukuran asli",
  video_result_desc: "Ukuran file berkurang secara signifikan berkat akselerasi dalam browser.",
  video_result_title: "Kompresi video selesai!",
  video_saved: "Ruang yang dihemat",
  video_selected: "Dipilih",
  video_step_level: "Pilih Tingkat Kompresi",
  video_step_level_desc: "Tentukan keseimbangan antara kualitas video dan ukuran file",
  video_tag: "Fitur Baru",
  video_title: "Kompres Video (MP4 / MOV)"
};
const id = { ...loadDict('id.ts'), ...idExtra };
saveDict('id.ts', 'id', id);

// 8. VIETNAMESE (vi)
const viExtra = {
  ad_label: "Quảng cáo / ADVERTISEMENT",
  ad_placeholder_title: "Khu vực quảng cáo tài trợ",
  ad_placeholder_desc: "Khu vực quảng cáo giúp duy trì dịch vụ hoàn toàn miễn phí.",
  badge_free_utility: "Tiện ích 100% Miễn phí",
  badge_no_login: "Không cần đăng ký hoặc đăng nhập",
  badge_no_server: "Không truyền lên máy chủ (Xử lý an toàn tại chỗ)",
  badge_unlimited_free: "Siêu tốc & Miễn phí Vô hạn",
  footer_col_legal: "Hỗ trợ & Điều khoản",
  footer_col_tech: "Công nghệ & Bảo mật",
  footer_col_tools: "Công cụ phổ biến",
  guides_back_to_list: "Quay lại danh sách hướng dẫn",
  guides_cat_all: "Tất cả",
  guides_cat_convert: "Chuyển đổi Office",
  guides_cat_edit: "Chỉnh sửa PDF",
  guides_cat_media: "Đa phương tiện & GIF",
  guides_cat_mobile: "Mẹo cho Di động",
  guides_cat_security: "Bảo mật & Quyền riêng tư",
  guides_copied: "Đã sao chép liên kết thành công!",
  guides_direct_tool: "Mở công cụ",
  guides_portal_badge: "Cẩm nang chính thức mypickpdf",
  guides_portal_subtitle: "Từ hợp nhất CV và hóa đơn đến đánh số trang luận văn và bảo mật cục bộ: làm chủ mọi thao tác tài liệu.",
  guides_portal_title: "Làm chủ Quy trình PDF & Tài liệu (40+ Hướng dẫn)",
  guides_quick_cta_title: "Hãy tự mình trải nghiệm ngay bây giờ!",
  guides_read_article: "Đọc hướng dẫn",
  guides_search_placeholder: "Tìm kiếm hướng dẫn hoặc từ khóa (vd: ghép, nén, di động...)",
  guides_share: "Chia sẻ hướng dẫn này",
  home_convert_btn: "Chuyển đổi",
  home_extract_btn: "Trích xuất",
  home_mascot_bubble: "Xin chào! Tôi là Gấu Trúc Đỏ 🐾 Hãy giao mọi tài liệu cho tôi!",
  home_table_title: "So sánh: Các trang trả phí vs mypickpdf",
  home_why_title: "Tại sao hàng triệu người dùng chọn mypickpdf?",
  nav_core_tools: "Công cụ Chỉnh sửa PDF",
  nav_media_tools: "Công cụ Video & Đa phương tiện",
  sponsor_snack_btn: "Mời Gấu Trúc Đỏ một bữa ăn nhẹ ☕",
  video_badge_hardware: "Mã hóa tốc độ cao được tăng tốc phần cứng",
  video_badge_local: "100% Xử lý Thiết bị Cục bộ (Không lưu trên máy chủ)",
  video_badge_mobile: "Hỗ trợ đầy đủ cho điện thoại thông minh (iPhone/Android)",
  video_btn_compress: "Nén video ngay",
  video_btn_reset: "Nén video mới",
  video_compressed: "Kích thước sau khi nén",
  video_compressing: "Đang nén video...",
  video_desc: "Giảm tới 80% kích thước video cho tin nhắn hoặc email mà không làm giảm chất lượng rõ rệt. 100% cục bộ trên trình duyệt.",
  video_drop_subtitle: "Hỗ trợ mọi định dạng MP4, MOV, WebM, MKV (không tải lên máy chủ)",
  video_drop_title: "Chọn tệp video cần nén",
  video_header_sub: "Thu nhỏ dung lượng tệp MP4 / MOV",
  video_opt_extreme_badge: "Kích thước nhỏ nhất",
  video_opt_extreme_desc: "Rất phù hợp để gửi qua ứng dụng nhắn tin và đính kèm email.",
  video_opt_extreme_sub: "Tiết kiệm tới 70~85% dung lượng",
  video_opt_extreme_title: "Nén tối đa (dành cho chat & email)",
  video_opt_less_badge: "Ưu tiên chất lượng",
  video_opt_less_desc: "Giữ độ sắc nét và chi tiết gốc ở mức cao nhất.",
  video_opt_less_sub: "Tiết kiệm khoảng 20~30% dung lượng",
  video_opt_less_title: "Giữ chất lượng cao (Nén nhẹ)",
  video_opt_rec_badge: "Khuyên dùng nhất",
  video_opt_rec_desc: "Sự cân bằng tốt nhất giữa hình ảnh rõ nét và giảm đáng kể dung lượng tệp.",
  video_opt_rec_sub: "Tiết kiệm khoảng 40~60% dung lượng",
  video_opt_rec_title: "Nén cân bằng (Tiêu chuẩn đề xuất)",
  video_original: "Kích thước ban đầu",
  video_result_desc: "Kích thước tệp đã giảm đáng kể nhờ khả năng tăng tốc của trình duyệt.",
  video_result_title: "Đã hoàn thành nén video!",
  video_saved: "Dung lượng tiết kiệm",
  video_selected: "Đã chọn",
  video_step_level: "Chọn mức độ nén",
  video_step_level_desc: "Lựa chọn mức cân bằng lý tưởng giữa chất lượng hình ảnh và kích thước tệp",
  video_tag: "Tính năng mới",
  video_title: "Nén video (MP4 / MOV)"
};
const vi = { ...loadDict('vi.ts'), ...viExtra };
saveDict('vi.ts', 'vi', vi);

console.log('Patched all 8 languages successfully!');
